### PR TITLE
Scrum rotation

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #7869

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hol353 @ric394 @par456 any idea why my pull request is failing with the PO process.  The error message is not very helpful.

**Comment by hol353** [comment]
The POStats database was full. This happens every 8-10 months or so. Empty now.

retest this please jenkins.

**Comment by HamishBrownPFR** [comment]
@hol353 @ric394 @par456 please review and merge if OK

**Pull request merged**
