### PR TITLE
Fixed soil wat generating millions of warnings.

### LINKED ISSUE #1418: Warnings for incorrect soil properties
I had an experiment where SAT > total porosity.  It created millions of warnings and a DB file that was about 1GB.  That caused APSIM to run out of memory.
Really, the error doesn't need to be echoed endlessly, in fact, it could simply be changed to a fatal error.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #1418

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 how did this get merged? It didn't run green on jenkins as far as I can tell

**Comment by hol353** [comment]
It was green so I merged it.

**Pull request merged**
