### PR TITLE
Fixed soil errors

### PR DESCRIPTION
**Pull request by mpandreucci**
@hol430 please let me know if you still get any errors from AgPasture.
Working on #1418 
Retest this please Jenkins

### CODE REVIEW

**Comment by hol430** [comment]
Cheers - will do.

**Comment by hol353** [comment]
@mpandreucci You need to put a working on #???? (where ???? is an issue number) in the top comment box. You can edit the top comment box by clicking ... and choose edit. Once you've done that then tell jenkins to retest your pull request.

**Comment by mpandreucci** [comment]
Yeah I tried adding it but I wasn't sure which issue number was it.

**Comment by mpandreucci** [comment]
retest please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
