### PR TITLE
Purchase resources fix to include finances

### LINKED ISSUE #7473: Resource buy activity not creating financial transaction
The ResourceActivityBuy activity is not creating the financial transaction

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7473

### CODE REVIEW

**Comment by hol353** [comment]
retest this please jenkins

**Comment by lie112** [comment]
Retest please Jenkins

**Comment by lie112** [comment]
no idea how to address this.. is it just a matter of trying jenkins again and again while getting different issues?

**Comment by hol353** [comment]
retest this please jenkins.

These unit test fails seem to happen about 1 in 10 PRs. Need to fix it one day.

**Pull request merged**
