### PR TITLE
Ag pasture dev

### PR DESCRIPTION
**Pull request by mpandreucci**
working on #3689

### CODE REVIEW

**Comment by hol353** [comment]
Good work @mpandreucci. It ran green. But...
Can you remove the PDF files? We don't commit them.

**Comment by mpandreucci** [comment]
Yup, I’ll do that. I ended up staging everything at one point and that’s why they ended up there. Sorry

**Comment by mpandreucci** [comment]
@hol353 how do I take the pdf file out of it? I asked Laura but she didn't know how to do it through source tree. Do I need to delete it from my prototypes folder?

**Comment by jbrider** [comment]
@mpandreucci in Sourcetree, there should be a 'stop tracking' option when right clicking on the file in the staging window - that would be the easiest way.
Alternatively - if you remove the file from the folder it should show up in Sourcetree as removed - you can then commit that file as being removed.

**Comment by mpandreucci** [comment]
Hi @jbrider . I'll have a go at removing it and then committing the change because I couldn't find out how to 'Stop tracking' it.
Thanks for that.

**Comment by hol353** [comment]
@mpandreucci :There are still 2 pdf files in here. Look at the 'Files changed' tab in the pull request.

**Comment by mpandreucci** [comment]
I'll delete them too (not sure how they ended up there since they have nothing to do with agpasture). Sorry about that

**Pull request closed without merging**
