### PR TITLE
Refactor generic organ

### LINKED ISSUE #3000: Refactor Organ/Arbitrator interface
Currently DM and N supplies and demands are methods that do a whole lot of calcualtions.  They should really be properties with private sets in each organ on a specific event to reduce redundant calculation

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #3000

### CODE REVIEW

**Comment by hol353** [comment]
Can you get rid of the .apsimx file in this pull request?

**Comment by hol353** [comment]
Sorry accidentally hit the close button rather than the comment button

**Comment by HamishBrownPFR** [comment]
Yep,

**Comment by HamishBrownPFR** [comment]
@hol353 I will close this pull request and open a fresh one as my origin repo seems to have lost track of this pull request

**Pull request closed without merging**
