### PR TITLE
Simple water uptake KL damage function

### LINKED ISSUE #8843: We need a pest/disease plant water update damage function
### Describe the new feature

This could be done simply by modifying KL.

### PR DESCRIPTION
**Pull request by hol353**
Resolves #8843

### CODE REVIEW

**Comment by ric394** [comment]
Are you able to write tests for this one @hol353?

**Comment by hol353** [comment]
Yes, good question. I was thinking about unit tests as well. The only bit of new code is:

```c#
        [EventSubscribe("StartOfSimulation")]
        private void OnStartOfSimulation(object sender, EventArgs e)
        {
            if (SoilCrop == null)
                throw new Exception($"No soil/crop specified in {Name}");
            SoilCrop = Soil.FindDescendant<SoilCrop>(SoilCrop.Name);
            initialKL = SoilCrop.KL.Clone() as double[];
        }

        [EventSubscribe("DoPestDiseaseDamage")]
        private void DoPestDiseaseDamage(object sender, EventArgs e)
        {
            SoilCrop.KL = MathUtilities.Multiply_Value(initialKL, reduction.Value());
        }
```

All I'm doing is setting KL by using MathUtilities.Multiply_Value method, which is already tested. Not much else to test.

**Comment by KeLiu7** [comment]
@hol353 @ric394 Does this also apply to soil acid, alkaline and saline limitations on KL and XF?

**Comment by hol353** [comment]
Nope. This is purely to allow a pest or disease model to modify KL in whatever way they want.

**Pull request merged**
