### PR TITLE
Reduce the cohort population instead of max leaf area

### LINKED ISSUE #3090: Cohort population vs max area in the flag leaf
@HamishBrownPFR  In the leaf cohort model, FinalFraction is applied to reduce the max leaf area of flag leaf. Consequently, the maximum tiller number will be really sensitive to the time of terminal spikelet. 

I would suggest to reduce the cohort population of flag leaf, instead of max leaf area. The dynamic of flag leaf should be the same in the per square meter.

### PR DESCRIPTION
**Pull request by byzheng**
resolves #3090

### CODE REVIEW

**Comment by hol430** [comment]
Retest this please jenkins

**Comment by hol353** [comment]
@HamishBrownPFR Can you have a look at this small change? The diffs in performance stats are only very minor.

**Comment by HamishBrownPFR** [comment]
@byzheng has run me through this.  He had implemented a good solution to the problem here and this should be merged

**Comment by hol353** [comment]
Ok. I'll rerun it first as it is quite old.

Retest this please jenkins

**Pull request merged**
