### PR TITLE
Multi paddock management #68

### PR DESCRIPTION
**Pull request by josharp22**
Final draft of a multi-paddock, multi-zone irrigator setup. Learning how to do pull requests with Hamish, this may require a few attempts! :-) working on #68 .

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by josharp22** [comment]
Are you asking me or someone else? Not clear who the message was sent to.

**Comment by hol353** [comment]
The message actually came from Jenkins asking me if josharp22 is allowed to submit a change. Jenkins doesn't know you yet. I'll respond to it.

**Comment by hol353** [comment]
Jo

Can you add the words "working on #..." (where ... refers to the issue that you're working on) to the initial pull request text. There is a pencil icon to let you edit it. Jenkins won't run correctly unless you reference an issue number in the text.

**Comment by josharp22** [comment]
Thanks for clarifying Dean, hopefully that works. Appreciate your help.

**Comment by hol353** [comment]
add to whitelist Jenkins.

**Pull request merged**
