### PR TITLE
Reduce use of Windows.Forms. Resolves #637.

### LINKED ISSUE #637: Reduce the number of units using the System.Windows.Forms namespace
Ideally, only Views code in the UserInterface should need to make use of anything in Windows.Forms. This makes porting code to other windowing platforms a lot easier.

### PR DESCRIPTION
**Pull request by zur003**
working on #637

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
Hi Eric.  For Jenkins to run the tests on pull requests you need to have a valid issue number in the description and the words 'working on' or 'resolves'  See https://github.com/APSIMInitiative/ApsimX/blob/master/CONTRIBUTING.md.

Dean will also have to add you to the list of trusted contributors before Jenkins will run tests.

**Comment by hol353** [comment]
Add to whitelist

**Comment by zur003** [comment]
working on #637

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
Need to say resolving with a # character and the issue number in the first edit box Eric.

**Comment by zur003** [comment]
“resolving”? I thought it had to be “resolves” or “working on”.

In any case, the log on Jenkins (http://apsrunet.apsim.info/JenkinsCI/job/2.%20Compile/587/console) seems to indicate a failure building the Models project, but I don’t see how my changes could have caused that. The only change to Models code was the removal of an unneeded “using System.Windows.Forms” from Manager.cs.

Eric Zurcher
Software developer | GrazPlan Project
CSIRO Agriculture

E Eric.Zurcher@csiro.au T +61 2 6246 5143 M 0415 631 421
GPO Box 1600, Canberra ACT 2601
www.csiro.au | www.grazplan.csiro.au

PLEASE NOTE
The information contained in this email may be confidential or privileged. Any unauthorised use or disclosure is prohibited. If you have received this email in error, please delete it immediately and notify the sender by return email. Thank you. To the extent permitted by law, CSIRO does not represent, warrant and/or guarantee that the integrity of this communication has been maintained or that the communication is free of errors, virus, interception or interference.

Please consider the environment before printing this email.

**Comment by zur003** [comment]
Also, can you clarify what you mean by the “first” edit box? Is that the description of the pull request, or the comment on it?

Eric Zurcher
Software developer | GrazPlan Project
CSIRO Agriculture

E Eric.Zurcher@csiro.au T +61 2 6246 5143 M 0415 631 421
GPO Box 1600, Canberra ACT 2601
www.csiro.au | www.grazplan.csiro.au

PLEASE NOTE
The information contained in this email may be confidential or privileged. Any unauthorised use or disclosure is prohibited. If you have received this email in error, please delete it immediately and notify the sender by return email. Thank you. To the extent permitted by law, CSIRO does not represent, warrant and/or guarantee that the integrity of this communication has been maintained or that the communication is free of errors, virus, interception or interference.

Please consider the environment before printing this email.

**Comment by HamishBrownPFR** [comment]
It needs to be 'resolves #637' or 'working on #637' (the former will close the issue when merged and the later keeps the issue open) and they need to be in the first message box (which is currently blank on this pull request).  So edit the top box to include one of these key phrases.  If jenkens can't find one of these he will not compile the build and is shows up as a failure so don't worry you won't have broken anything.

**Comment by hol353** [comment]
The comment box has to have a 'Resolves' followed by a # followed by an issue number. The issue number forms part of the APSIM version number (yyyy.mm.dd.issue). Without this, APSIMX will not compile.

**Comment by zur003** [comment]
retest this please Jenkins

**Comment by zur003** [comment]
I've added a "working on" comment, then tried a "retest this please Jenkins", but nothing happened. Does this require an admin?

**Comment by hol353** [comment]
retest this please Jenkins

**Pull request merged**
