### PR TITLE
Tip to appear

### PR DESCRIPTION
**Pull request by RobZys**
solved #2232 

Added           Structure.TipToAppear = 0; to clear() in Leaf.cs

### CODE REVIEW

**Comment by rcichota** [comment]
Retest this please, Jenkins

**Comment by hol353** [comment]
Sorry Rob this is now conflicted due to @HamishBrownPFR changes. Also there are a lot of file changes here which don't look right to me. Need to clean up the branch.

**Comment by hol353** [comment]
Rob, change the top edit box to resolves rather than solves.

**Comment by RobZys** [comment]
Yeah sorry

**Pull request closed without merging**
