### PR TITLE
Implemented Report.DoReport event

### PR DESCRIPTION
**Pull request by hol430**
Working on #4202 

e.g. `sum of [Clock].Today.DayOfYear from [Report].DoReport to [Clock].Today as sum`

### CODE REVIEW

**Comment by hol353** [comment]
@sno036: DoReport sounds like a method name. I know it was the name we used in APSIM 7.10. 

Need to come up with an event name. How about 'Reported' or 'Outputed'. The example would be:

sum of [Clock].Today.DayOfYear from [Report].Outputed to [Clock].Today as sum

**Comment by hol353** [comment]
or even better: Why not change report to have a DateOfLastOutput property so the example becomes:

sum of [Clock].Today.DayOfYear from [Report].DateOfLastOutput to [Clock].Today as sum

**Comment by sno036** [comment]
I like that last suggestion. I assume that this will work with array operations as well - e.g.

Ave([Soil].SoilWater.SW) from [Report].DateOfLastOutput to [Clock].Today as AverageWaterContent
and (slightly ridiculously)
(Ave([Soil].SoilWater.Sat) + Ave([Soil].SoilWater.Dul)) from [Report].DateOfLastOutput to [Clock].Today as AverageSomethingSilly

**Comment by hol430** [comment]
Closing this in favour of #4222

**Pull request closed without merging**
