### PR TITLE
Thermal time re name

### LINKED ISSUE #2943: Further tidying of phenology code
Need to rename Thermal time to Progression and remove budding phase because it duplicates most of the functionality of generic phase

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #2943.  I have depricated the budding phase becasuse its functionality duplicated that of generic phase and moved the few specific bits into a budNumberFunction class.  I have also renamed ThermalTime on phases to Progression because this is often not ThermalTime.

@hol353 I am not that happy with the crop.xml files I am submitting as the conversion process has added some cruft.  The alternatives are to resolve issue #2942 then redo this pull request of go through each phase in each crop model and change them manually.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 don't merge this if it runs green (like thats going to happen), I have comitted a .apsimx file that I should not have.  I will wait for this pull request to see what other problems need fixing then submit another pull request

**Comment by HamishBrownPFR** [comment]
@hol353 can I get your advise on what do do with this pull request as I am reaching the end of my tether with it.  It is failing the maize tests with some very minor diffs that could be accepted without to much issue.  However I would quite like to know where these diffs are coming from and use the checkpointing system to diagnose it.
There issue with the extra cruft that the converter put into the crop.xml files still persists.  I think I could remove most of the cruft with find and replace.  The tool we have been discussing in #2942 would help me remedy this problem but not sure if it is close or not.

**Comment by hol353** [comment]
I am trying to work on the checkpoint code to do private members as well as public. I'm having some troubles getting it going. Most of my problems are finding time to work on it. I'm in Sydney this week and Brisbane next week. I'm working on it this afternoon and may get it going. If not it will probably be Friday or next Monday before I get back to it. For now just go onto something else and wait for me to get checkpointing going.

**Comment by HamishBrownPFR** [comment]
OK, thanks @hol353.  I will be good to use this as a test case for the checkpointing and crop converter so I will hang fire until these are both operational.

**Comment by hol353** [comment]
@HamishBrownPFR I've had a go at fixing the checkpoint mechanism. Can you give it a go. It should now write a .json file in the same directory as your .apsimx file. It should also now have private fields. It seems to work for phenology but may not work for other organs / classes.

**Comment by HamishBrownPFR** [comment]
@hol353 I have got some checkpointing working well enough to debug this.  The differences in Maize stats all track back to a change in the way thermal time is accumulated in the germination phase where this pull request fixes a bug so thermal time is accumulated properly.  This has subtle effects on the timing of husk growth which feeds through to trivial differences in the stats.  Happy for these stats to be accepted and the pull request to be merged if the current build test runs OK.

**Pull request merged**
