### PR TITLE
Start of a SWIM3 lower BC test etc.

### PR DESCRIPTION
**Pull request by sno036**
Worthwhile getting this simulation added/merged - there is a mass balance error that emerges at about day 11.

Working on #6824 

Merge this please Jenkins (or does this not work these days?) Does 'working on' end up being merged automatically?

### CODE REVIEW

**Comment by hol353** [comment]
Merging is a manual process that happens once I or @hol430 do a review of it and am happy with it. The 'working on' phase is important to Jenkins to let it know which GitHub issue the PR is related to. It uses this info to version stamp the executables that it builds.

**Comment by hol353** [comment]
If the simulation throws an exception (error) due to a mass balance problem then Jenkins will run 'red' and it won't be able to be merged. We only merge green PRs.

**Comment by hol353** [comment]
@hol430 Can you review and merge if ok? This is a work in progress and there is a long way to go to get SWIM source code meeting coding standards and into the release.

**Review by hol430 — APPROVED** [review]
Looks good, although I'll note that if we're aiming to follow Microsoft's guidelines for code style, we should not have comments on the same line as code like in this line:

```csharp
int isbc = 0; // No storage of water on soil surface
```

Since this is a work in progress I'm happy for this to go through though.

**Pull request merged**
