### PR TITLE
Add met and updated obs file to Eucalyptus validation

### PR DESCRIPTION
**Pull request by sme016**
Working on #5624

### CODE REVIEW

**Comment by hol430** [comment]
That's strange...@hol353 have you changed the jenkins settings or is our bot starting to become self-aware?

**Comment by hol353** [comment]
I haven't changed anything.

**Comment by hol430** [comment]
@sme016 - Hi Phil, looks like the path to the observed file in the Eucalyptus.apsimx file is an absolute path. From the logs:

```
System.Exception: Error in Observed: file 'C:\APSIMxSourceTree\Tests\Validation\Eucalyptus\ObservedEucalyptus 200825a.xlsx' does not exist
```

If you open up the .apsimx file in the gui, and edit the path to the excel file, and just delete the path (so the textbox just contains `ObservedEucalyptus 200825a.xlsx`), then I think that should fix the problem.

**Comment by sme016** [comment]
Ah – yes – that problem again. Thanks

**Pull request closed without merging**
