### PR TITLE
Remove or comment out variables in Importer and SWIMFrame that aren't …

### PR DESCRIPTION
**Pull request by zur003**
…actually being used.
Working on #860

### CODE REVIEW

**Comment by fai04d** [comment]
Eric, can please revert the changes to SWIMFrame? I haven't finished the FORTRAN conversion yet and some of those variables might be needed later on. I'll clean it all out when it's ready to be integrated with APSIM.

**Comment by zur003** [comment]
Hi Justin,

You can revert the code, if you wish. I thought that might be a problem, so with the SWIMFrame stuff I didn’t delete any code,  just commented it out.

Eric Zurcher
Software developer | GrazPlan Project
CSIRO Agriculture and Food

E Eric.Zurcher@csiro.au T +61 2 6246 5143 M 0415 631 421
GPO Box 1700, Canberra ACT 2601
www.csiro.au | www.grazplan.csiro.au

PLEASE NOTE
The information contained in this email may be confidential or privileged. Any unauthorised use or disclosure is prohibited. If you have received this email in error, please delete it immediately and notify the sender by return email. Thank you. To the extent permitted by law, CSIRO does not represent, warrant and/or guarantee that the integrity of this communication has been maintained or that the communication is free of errors, virus, interception or interference.

Please consider the environment before printing this email.

**Comment by hol353** [comment]
Can we not revert the change. Given that the unused variables are commented out, it should be easy to put them back in when they are needed.

**Comment by fai04d** [comment]
What was the rationale for commenting them out in the first place? It's in-development code that isn't even part of APSIM yet (it'll be compiled of course, but not run). Eric had to spend time commenting them and I'm just going to revert them (I won't do another push of SWIM until it's ready for integration which should be soon hopefully). Was it causing problems problems with mono or something?

**Comment by zur003** [comment]
The Mono compiler issues warnings about unused variables, including many cases which the Microsoft compiler doesn't detect. Most of our projects have "treat warnings as errors" turned on, so these warnings were a nuisance when compiling with Mono, as they required manual intervention (if only just to disable the "treat warnings as errors" option). The SWIMFrame project is included in the ApsimX solution, so even though not yet really included in ApsimX, the build machinery still compiles it, and gives the warnings/errors. I've been trying to clean things up, on the principle that "clean" code should generate neither warnings nor errors.

**Pull request merged**
