### PR TITLE
Grapevine

### PR DESCRIPTION
**Pull request by junqi108**
working on #1822 
optimizing the model parameters and add more documentation

### CODE REVIEW

**Comment by junqi108** [comment]
reset this please Jenkins

**Comment by junqi108** [comment]
retest this please Jenkins

**Comment by junqi108** [comment]
@hol430 
hi Drew: it seems Jenkins stuck in the build-up. 
The error says there is some version problem, but i am not sure how to solve it. 

[UI] C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Properties\AssemblyVersion.cs(3,28): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [C:\Jenkins\workspace\PullRequest_v2\ApsimX\Updater\Updater.csproj]

[UI] C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Properties\AssemblyVersion.cs(4,32): warning CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [C:\Jenkins\workspace\PullRequest_v2\ApsimX\Updater\Updater.csproj]

[UI]   APSIM.Shared -> C:\Jenkins\workspace\PullRequest_v2\ApsimX\APSIM.Shared\bin\Release\APSIM.Shared.dll

[UI] Properties\AssemblyVersion.cs(3,28): error CS7034: The specified version string does not conform to the required format - major[.minor[.build[.revision]]] [C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Models.csproj]

[UI] Properties\AssemblyVersion.cs(4,32): warning CS7035: The specified version string does not conform to the recommended format - major.minor.build.revision [C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Models.csproj]

**Comment by hol430** [comment]
Ah - yeah you need to add a "working on #xxxx" to your initial comment. There should be an option to edit the comment somehow..

**Comment by junqi108** [comment]
sorry, after some time not submitting pull requests and caught the flu, I am getting stumbled

**Comment by junqi108** [comment]
retest this please Jenkins

**Pull request merged**
