### PR TITLE
Ginniderra system test

### PR DESCRIPTION
**Pull request by hedycau**
working on #7415

### CODE REVIEW

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
@hedycau This pull request failed. To see the error:
* Click on details above on the Jenkins row that has a red cross. 
* Scroll to the top of the resulting window and click on 'Show Complete Log'
* Search for _Exception_

You should see
```
ERROR in file: ./Tests/Validation/System/Ginniderra/GinniderraApsimX.apsimx
Simulation name: APSIM_SWIMFertiliser0
Models.Core.SimulationException
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.Soils.Swim3.ReadSoluteParams() in /tmp/ApsimX/Models/Soils/SWIM/Swim.cs:line 2305
   at Models.Soils.Swim3.OnReset() in /tmp/ApsimX/Models/Soils/SWIM/Swim.cs:line 1253
   at Models.Soils.Swim3.OnInitialised(Object sender, EventArgs e) in /tmp/ApsimX/Models/Soils/SWIM/Swim.cs:line 1168
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e) in /tmp/ApsimX/Models/Clock.cs:line 289
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 329
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 329
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 212
```

Looks like the problem we saw yesterday in SWIM and then fixed. If you commit and push to your hedycau remote on GitHub this pull request will automatically rerun with the new fixes.

**Comment by hedycau** [comment]
Thanks, Dean @hol353 . I fixed the problem and it ran smoothly on my laptop. I pushed it to my remote, but the test failed. Could you re test it?

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Ok this runs green now. Do you want to make more changes or shall I merge this into the release?

**Comment by hedycau** [comment]
Great! :) The other thing I would like to change is putting the initial soil temperature into the simulation. I could do it after you add the soil temperature initialisation structure. Then we could have the whole validation dataset in it. What do you think of it?

**Comment by hol353** [comment]
Good idea. It might be a while before I get a chance to fix SoilTemperature so I'll merge this into APSIM. Next time you want to make a change, create a new pull request.

**Pull request merged**
