### PR TITLE
Introduce improved leaf expansion stress functions that have been dev…

### LINKED ISSUE #1998: Pull request #929 degraded the Maize models predictions of Final leaf number and MaxLAI
pull request #929 contained a major refactor of the leaf appearance code after a bug was found in this during the wheat model validation.  Some of the paramaters for maize (which was developed before wheat) were fitted incorrectly to account for this bug but these were never refitted after the bug was fixed.  They need to be refitted.

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
…eloped in Wheat.

resolves #1997 
resolves #1998

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hol353  This is another one that needs to be assessed with Loretta testing system.  I think my changes have improved all the stats but they fail as diffs in the old system.

**Comment by hol353** [comment]
OK, Loretta has hopefully fixed the performance testing site. How about you do a retest on one of your pull requests and we'll see how it goes?

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Will need to remove the tests node

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
Hi @hol353 I was waiting for Loretta's testing tool to see how this pull request worked on it but need to move on.  Can you merge this is you are happy with it.

**Pull request merged**
