### PR TITLE
Add UnderReview directory to installed version

### LINKED ISSUE #3877: Put the UnderReview folder into the release to make it easy for reviewers.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #3877

### CODE REVIEW

**Comment by hol353** [comment]
What about the autodocs for under review models?

**Comment by hol430** [comment]
Oh sorry I didn't notice your comment on that issue - I'll add that in to this pull request.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
We'd like to see the autodocs for the under review models on this page:
https://apsimnextgeneration.netlify.com/modeldocumentation/
under a 'Under Review' section at the bottom. Possible?

**Comment by hol430** [comment]
If you merge this pull request they should appear on the website, although they'll be under the same heading as the released models.

Have you made changes to the APSIM.Builds code and published these changes without making a pull request? I can't explain what I'm seeing on that webpage. Specifically, I have no idea where the "Science Documentation" section has come from, and the wording of the title is slightly different to what's in the current source code.

**Comment by hol353** [comment]
I forgot to push my APSIM.Builds code. Done now. Any ideas on how we might get a UnderReview section before I merge this?

**Comment by hol430** [comment]
The APSIM.Builds code needs some way to distinguish the released models' documentation from the under review models' documentation. Maybe we could upload the under review models' documentation to a different directory.

**Comment by hol353** [comment]
Yep that might work. Give it a go. I'll leave this pull request open.

**Comment by hol430** [comment]
APSIMInitiative/APSIM.Builds#10 should also be merged when this is merged. Together, they should allow for under review models' doco to appear on the website.

**Comment by hol353** [comment]
@hol430 This doesn't seem to have worked. I can't see an underreview section on the autodoc page.

**Comment by hol430** [comment]
Autodocs are throwing a fatal for SCRUM validation set (observed table was renamed to Observed but some graphs weren't updated). When this happens, Jenkins doesn't attempt to generate autodocs for anything after SCRUM (alphabetically). The under review models will normally be documented after the validation sets. #3895 should fix SCRUM when it's merged.

**Comment by hol353** [comment]
@hol430 Still lots of errors in the CreateInstallation job on jenkins.

**Comment by hol430** [comment]
Yeah you need to merge #3895 - it will fix the SCRUM error.

**Pull request merged**
