### PR TITLE
Camp tidyup

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #7726

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol353** [comment]
The jenkins build system seems to have a problem. I'm looking into it.

**Comment by HamishBrownPFR** [comment]
Thanks Dean

**Comment by hol353** [comment]
Jenkins is working again now.

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
retest this please Jenkins

**Comment by HamishBrownPFR** [comment]
@hol353 Something odd has happened with this pull request.  It is currently throwing an error which is not a problem.  I have renamed a class and not changed the oat.json file to reflect this.  I can fix that so thats not a problem.  The odd think is I renamed that class many commits ago but this is the first time the build has failed with that error.  Just making you aware of what has happened incase it is a symptom of a problem somewhere

**Comment by HamishBrownPFR** [comment]
@hol353 false alarm.  This was caused my merge confusion on my part.

**Comment by hut104** [comment]
Hamish,
We seem to have a grapevine test, a solution file in a backup folder, and an upgrade log.htm file in the pull request.
It's also failing in CLEM for some unknown reason. @lie112  Any ideas?

**Comment by lie112** [comment]
I have no idea why this issue has just started. I made a successful pull request yesterday and all worked smoothly.
My suggestion is to delete the offending Validation simulation from Tests as I can't get it running on my machine but for different reasons as it won't even open the json file. I don't need this file running in validation now and I'll fix it in future.

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hut104 Random files removed

**Comment by HamishBrownPFR** [comment]
moving to another pull request

**Pull request closed without merging**
