### PR TITLE
Correct years per day to 1/365.242199

### LINKED ISSUE #5065: Years per day
Rather than the current years/day value in I think all models, which is a non-leap year value (1/365), wouldn't it be better to specify it more precisely as: 0.00273785 (=1/365.25) to account for leap years on average. So currently there is an error of 0.068493% per year, or about 3.4% for 50 years. This is not important for short term crop simulations of one or a few years, but for oil palm and forest plantation etc. it is adding an error that we could otherwise avoid.

### PR DESCRIPTION
**Pull request by sme016**
Corrected years per day to 1/365.242199 in Pinus and Eucalyptus .json files
Resolves #5065 
Related to #6654

### CODE REVIEW

**Comment by sme016** [comment]
Ignore MAIub test
Please merge

**Comment by sme016** [comment]
Resolves #8115 
But please tell me how I can also change this value in the TreeManagement tool for #6654

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
If you want to change the management toolbox, open this file in the GUI:
ApsimX\ApsimNG\Resources\Toolboxes\ManagementToolbox.apsimx

Make the changes you want, save the file and then raise a pull request with the modified file.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by sme016** [comment]
Thanks. I'll try the toolbox change in a few days.

**Comment by sme016** [comment]
Please ignore the MAIub test and merge

**Comment by sme016** [comment]
Please Merge

**Comment by hol353** [comment]
The stats show that some observations of ```Stem.MAIub``` have gone missing for Eucalyptus and Pinus. Why is that?

**Comment by sme016** [comment]
That is correct and deliberate. MAIub for both Pinus and Eucalyptus had values from only one or two sites each, which I thought wasn't necessary to keep as part of the testing.

**Comment by sme016** [comment]
Resolves #5065 
Resolves #8115

**Pull request merged**
