### PR TITLE
retranslocation error

### PR DESCRIPTION
**Pull request by junqi108**
working on #5199

### CODE REVIEW

**Comment by junqi108** [comment]
@HamishBrownPFR only grapevine model through errors in the root storage retranslocation

**Comment by HamishBrownPFR** [comment]
Thats good.  Delete Lines 127 - 146 as well.  These functions are redundant so we can tidy up the root class.  That will also fix the error grapevine is flowing.  For completementss it would be good to put the same error checks in the N Allocation code for root.

image

**Comment by junqi108** [comment]
@HamishBrownPFR @hut104 OK, I will delete those lines first. How difficult it would be to include the re-translocation function in Root? it seems to add structural and storage biomass is very easy as we did last time in the PartitionRootMass? will make the TotalDMAllocated negative works if the retranslocation is very big? 
public void PartitionRootMass(double TotalRAw, Biomass TotalDMAllocated)
        {
            DMAllocated = new double[soil.Thickness.Length];
 
            if (Depth > 0)
            {
                double[] RAw = CalculateRootActivityValues();

                for (int layer = 0; layer < soil.Thickness.Length; layer++)
                    if (TotalRAw > 0)
                    {
                        LayerLive[layer].StructuralWt += TotalDMAllocated.StructuralWt * RAw[layer] / TotalRAw;
                        LayerLive[layer].StorageWt += TotalDMAllocated.StorageWt * RAw[layer] / TotalRAw;
                        LayerLive[layer].MetabolicWt += TotalDMAllocated.MetabolicWt * RAw[layer] / TotalRAw;

                        DMAllocated[layer] += (TotalDMAllocated.StructuralWt + 
                                               TotalDMAllocated.StorageWt +
                                               TotalDMAllocated.MetabolicWt)* RAw[layer] / TotalRAw;
                    }
            }
        }

**Comment by junqi108** [comment]
@rcichota @HamishBrownPFR Hi Rogerio, i removed some unwell performed function in the root class. it seems it affects the clover model performance marginally. Just would like to discuss with you whether we can set root retranslocation factor to zero for clover?

**Comment by rcichota** [comment]
Hi @junqi108, happy to discuss this further. Are your simply deleting retranslocation functions or replacing them? Isn't this an important factor for re-growth over spring?
I had played a bit with adding retranslocation from roots in the models I was building, these are quite important for perennial forages (though specific data is not that easy to come by). I had removed from Chicory and Plant when I submitted them, but I think I left them in WhiteClover and maybe RedClover, the effect is small as most retranslocation should come from stolons and taproot. We can either replace the logic or even maybe delete and accept the changes if small...

**Pull request closed without merging**
