### PR TITLE
Ag pasture

### PR DESCRIPTION
**Pull request by hol353**
Working on #3689

### CODE REVIEW

**Comment by hol353** [comment]
@zur003  and @hol430 Looks like Muck is still giving these errors: 

Could not load file or assembly 'Newtonsoft.Json, ...

**Comment by hol430** [comment]
APSIMInitiative/APSIM.PerformanceTests#26 should fix it

**Comment by hol353** [comment]
@zur003, @hol430 : This is going to sound bizarre, but I didn't merge this PR. I merged  #4304 which ran green and GitHub kindly merged this one as well. This PR was not green and so I couldn't have accidentally merged it as there is no merge button when it is red. Maybe I should file an issue with GitHub.

**Comment by hol430** [comment]
Maybe contact github support - and revert the merge commit too since I'm guessing it ran red for a reason?

**Pull request merged**
