### PR TITLE
Wrapping up the RedClover model

### PR DESCRIPTION
**Pull request by rcichota**
Working on #2694

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by rcichota** [comment]
retest this please Jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by rcichota** [comment]
@sarahcleary 
The pull request has been merged, the model is now ready to go to review

**Comment by sarahcleary** [comment]
Thanks @rcichota.  I will send a separate email to Jonathan Ojeda and Mark Lieffering letting them know the model is ready for review.

**Pull request merged**
