### PR TITLE
Apply correct parameter to ruminant energy equation

### LINKED ISSUE #7732: Weaners appear to have too much growth
Weaners (weaned to 12 months) seem to get an elevated growth.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7732

### CODE REVIEW

**Comment by lie112** [comment]
retest this please jenkins

**Comment by lie112** [comment]
I am unable to determine the issue here and something may require a restart.

**Comment by hol353** [comment]
Yep all builds broken. I'm working on it. Not as simple as a restart given that the build nodes restart for every apsim build.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by lie112** [comment]
To assist in fixing issues here's the problem with R 
`PastureByWaterAndNitrogenNitrogen30Waterfalse (./Examples/AgPasture.apsimx) has finished. Elapsed time was 17.0 seconds.
System.Exception: Error from R:
Script path: '/tmp/7d947518-f716-4663-b687-60c93f2591e6-getPackage.R'
StdErr:
Warning in install.packages(pkg, repos = "https://cran.csiro.au/", lib = pkgpath,  :
  'lib = "ApsimInitiative/ApsimX/rpackages"' is not writable
Error in install.packages(pkg, repos = "https://cran.csiro.au/", lib = pkgpath,  : 
  unable to install packages
Calls: getPackage -> install.packages
In addition: Warning message:
In dir.create(pkgpath) :
  cannot create dir 'ApsimInitiative/ApsimX/rpackages', reason 'No such file or directory'
Execution halted

StdOut:

Script contents:
#' Loads a package, installing it if necessary.
#'
#' @param pkg Name of the package to be installed/loaded.
#' @param pkgpath Path where package is to be installed.
#' @return Nothing.
getPackage <- function(pkg, pkgpath) {
    if (!pkg %in% rownames(installed.packages())) {
        if (!dir.exists(pkgpath)) {
            dir.create(pkgpath)
        }
        install.packages(pkg, repos = "https://cran.csiro.au/", lib = pkgpath, dependencies = TRUE)
	} else {
		print(paste('Package', pkg, 'is already installed.'))
	}
}

args = commandArgs(TRUE)
getPackage(args[1], args[2])



   at Models.Utilities.R.Run(String fileName, Boolean throwOnError, String[] arguments) in /tmp/ApsimX/Models/Utilities/R.cs:line 194
   at Models.Utilities.R.InstallPackage(String package) in /tmp/ApsimX/Models/Utilities/R.cs:line 265
   at Models.Utilities.R.InstallPackages(String[] packages) in /tmp/ApsimX/Models/Utilities/R.cs:line 307
   at Models.Optimisation.CroptimizR.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Optimisation/CroptimizR.cs:line 497
   at APSIM.Shared.JobRunning.JobRunner.Run(IRunnable job) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 225
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 189
CroptimizR has finished. Elapsed time was 7.5 seconds.`

**Comment by lie112** [comment]
Any news on the R problem fix?
Never sure when to just retest

**Comment by hol353** [comment]
I'm working on it - hopefully close. I'll retest PRs when I'm ready. Just sit tight for now.

**Comment by lie112** [comment]
Resolves #7718 
The autocreation of the CLEM descriptive summary is no longer created when performing experiment-based simulations.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by lie112** [comment]
@hol353  Seems the upgrade builder has also failed in MacOS build

**Pull request merged**
