### PR TITLE
Fix error bars on graphs

### LINKED ISSUE #3865: Error bars on graphs not working
When graphing observed data that has error columns, an exception will be thrown: "collection was modified, enumeration operation may not execute".

### PR DESCRIPTION
**Pull request by hol353**
Resolves #3865

### CODE REVIEW

**Comment by JJguri** [comment]
@hol353 could you please specify which module and where I need to use to see the error bars in a graph? How do these values need to be added to the obs file?

**Comment by hol430** [comment]
@JJguri If the y variable on your graph is called "Yield" then apsim will look for a column called "YieldError" and show the data in that column as error bars (if such a column exists). So you just need to rename your column containing the error data to the same name as the observed column with the word Error at the end.

You also need to make sure your marker type is set to one of the "Filled" marker types - e.g. FilledCircle. This probably shouldn't be necessary and might be a bug so I'll look into it.

As a (silly) example:

image

image

**Comment by JJguri** [comment]
Thanks @hol430 

I got the bars for my time-series graphs. Now I would like to put it in the x-axis of an XY graph. Please see example below. The difference here is that the data source is a TimeSeriesData table created to match pre and obs. How should I include the AboveGroundWtError in that table?
Untitled

**Comment by hol430** [comment]
Looking at it a bit closer, I think we currently only have support for error data on the y series. I'll fix this as part of #5341

**Comment by JJguri** [comment]
> Looking at it a bit closer, I think we currently only have support for error data on the y series. I'll fix this as part of #5341

Please keep me posted about the development of this functionality. I am exporting outputs and plotting these externally because I cannot add error bars to the p-o graphs in the UI.

**Pull request merged**
