### PR TITLE
Sorghum/documentation

### PR DESCRIPTION
**Pull request by jbrider**
working on #572

### CODE REVIEW

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
@hol353 This looks to be failing soon after it starts running the simulations in the validation folder.
I can't tell which simulation it was running when it failed though.

**Comment by hol353** [comment]
I'm not sure what you're seeing but I see lots of errors like this:
```
ERROR in file: ./Prototypes/C4Maize/C4Maize.apsimx
Simulation name: Angelo98FertN0
Models.Core.SimulationException
 ---> System.Exception: Cannot find a match for link nPhenoStressFunction in model .Angelo98FertN0.paddock.C4Maize.Leaf
   at Models.Core.Links.ResolveInternal(Object obj, ScopingRules scope, Boolean throwOnFail) in /tmp/ApsimX/Models/Core/Links.cs:line 191
   at Models.Core.Links.Resolve(IModel rootNode, Boolean allLinks, Boolean recurse, Boolean throwOnFail) in /tmp/ApsimX/Models/Core/Links.cs:line 46
   at Models.Core.Simulation.Prepare() in /tmp/ApsimX/Models/Core/Simulation.cs:line 272
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Prepare() in /tmp/ApsimX/Models/Core/Simulation.cs:line 276
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 212
```

**Comment by jbrider** [comment]
My bad - apparently I wasn't looking at the complete log.

**Comment by hol353** [comment]
@jbrider  Are you ready to have this merged?

**Comment by jbrider** [comment]
Not quite - pretty close though. Should be right to merge on Monday morning.
It can be merged if you're going to work on documentation though.

**Comment by hol353** [comment]
I'm not working on anything related. I'll wait until next week to merge. Let me know when ready.

**Comment by jbrider** [comment]
@hol353 when (if) this goes green, can you merge it - the input I have been waiting on has been further delayed so I would rather get this merged now and come back to it.

**Pull request merged**
