### PR TITLE
Feature/i leaf

### LINKED ISSUE #610: Need to add a Leaf Interface to get 'SimpleLeaf' to work with 'Structure'

### PR DESCRIPTION
**Pull request by aldoherty**
resolves #610

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
add to whitelist

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request closed without merging**
