### PR TITLE
Fodder beet model#78

### PR DESCRIPTION
**Pull request by ed2014**
Update Fodder Beet prototype after 2 days workshop on model development. Using new folder structure (Prototype folder).

### CODE REVIEW

**Comment by hol353** [comment]
Edmar

Don't put fathen.xml into the Model\Resources directory. It hasn't been approved by the Reference Panel yet. Instead put it into a Replacements folder in your fathen.apsimx file in Prototypes.

**Comment by hol353** [comment]
Edmar

Can you put in just the files for FatHen into a single pull request and FodderBeet into another one. And reference an issue for each one. There are also some source code files that you probably didn't mean to change.

**Comment by ed2014** [comment]
Hi Dean,

Thanks! Sorry for that ... Just realised after I sent the pull request. 

It seems it was accidentally merged into the fodder beet branch during our workshop in the last two days.

Will pay more attention next time to the full list of commits for the branch... Sincere apologies!

Regards,

Ed

**Comment by ed2014** [comment]
Hi Dean,

Trying again. Reverted unintended changes. Please have a look if all ok now.

Thanks,

ed

**Pull request merged**
