### PR TITLE
Add new photosynthesis model

### LINKED ISSUE #2120: New photosynthesis model
Add new DCAPS model by Alex Wu

### PR DESCRIPTION
**Pull request by fai04d**
Resolves #2120
Added new photosynthesis model.

### CODE REVIEW

**Comment by fai04d** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
@fai04d - can you make sure that method names start with an upper case character. Also there is at least one case where a type name and a property name only differ by case e.g.

public ConductanceModel conductanceModel

Not a good thing. There are also completely commented classes. Do we really need these?

**Comment by fai04d** [comment]
This isn't my code, it's by Alex Wu. I don't really know what's in there as they just wanted me to make an interface for APSIM for it. Let me know what you want changed and I'll let Scott and Enli know that it will take some more time to get it in the correct format.

**Comment by hol353** [comment]
I figured it wasn't your code. It needs to conform to Microsoft c# guidelines. Method names should start with a capital letter and the type name should differ from the property/field instance name by more than just case e.g.

public ConductanceModel conductanceModel

isn't good practice as the instance name is the same as the type name (apart from case)

**Comment by hol353** [comment]
The diffs for this pull request show lots of files changed that aren't related to the issue being addressed. A bad merge?

**Comment by fai04d** [comment]
No, it's just Github keeping the state of the branch up to date. I hadn't merged master into this branch for a while so it was out of date. The current merge sorts that out. This PR is currently with Al Doherty who is making changes to conform to our code guidelines.

**Comment by hol353** [comment]
Closing this old pull request. No one working on it.

**Pull request closed without merging**
