### PR TITLE
Check point fixes

### LINKED ISSUE #3022: Expand checkpointing to make it more useful for debugging
The check pointing concept is potentially very powerful for debugging.  Current limitations.

The SaveStateOfObject method writes the full simulation structure if the object argument is an IModel.  This means you can't checkpoint subsets of a simulation

It is not possible locate checkpointed chunks in simulation time.

The WriteToFile method creates a new file, overwriting the previous output each time it is called so you can't checkpoint to the same file more than once in a simulation

The JsonConvert.SerializeObject method serializes the whole object including its parents so even if you do specify a specific part of a model to checkpoint, it will ends up checkpointing the whole simulation, making a massive file.

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #3022 .  See also #3023 for discussion relating to this.  Had to kill that pull request because phantom files were showing up where weren't actually there.  Closing and opening again has dealt to them but I don't know why they showed up in the first place.

### CODE REVIEW

**Comment by hol353** [comment]
@HamishBrownPFR This doesn't really resolve issue 3015. Issue number wrong? Also can you get rid of the CohortArrayLive in the other model resource xml files? It think they are also in wheat.

**Comment by HamishBrownPFR** [comment]
Changed to correct issue (sorry about that), removed CohortArrayLive and CohortArrayDead from Wheat.xml and Potato.xml.  Removed full model xml from Microclimate test.  Added converter method to remove these from other models.

**Comment by hol353** [comment]
One final thing sorry. You have microclimate.apsimx in there. Any reason for that?

**Comment by HamishBrownPFR** [comment]
Yep, I did a search for CohortArrayLive and Dead and found some in that file.  Turns out it had full xml structure for the wheat and maize models so I changed this so it is using the released model

**Comment by hol430** [comment]
@HamishBrownPFR MicroClimate.apsimx still appears to have two instances of the full XML for the wheat model, starting on lines 2673 and 8277. Is this intentional?

**Comment by HamishBrownPFR** [comment]
@hol430  this was not intentional, I should have deleted them

**Pull request merged**
