### PR TITLE
Oats

### PR DESCRIPTION
**Pull request by hut104**
working on #2349 
I've added code to zero biomass outputs in leaf at end crop.  Not sure if this will change the stats

### CODE REVIEW

**Comment by hut104** [comment]
retest this please jenkins

**Comment by hut104** [comment]
retest this please jenkins

**Comment by hut104** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hut104** [comment]
I suggest merging this to get it out of the way.  It is just new OBS data.  Allan has been working on this in any case.

**Pull request merged**
