### PR TITLE
Creation pure fom types

### LINKED ISSUE #1073: Pure FOM residue types
We would like residue types that are pure FOM carb, cell and lign please

### PR DESCRIPTION
**Pull request by josharp22**
Resolves #1073

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
add to whitelist

**Comment by HamishBrownPFR** [comment]
@hol353 I think it needs to you who adds people to the whitelist

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by HamishBrownPFR** [comment]
Merging this because the new FOM types added are useful for research applications

**Pull request merged**
