### PR TITLE
Soil nitrogen

### LINKED ISSUE #1671: SoilNitrogen needs updating to match classic version
Bringing current code from Apsim classic into X to support patches etc.

### PR DESCRIPTION
**Pull request by mcauliffer**
Resolves #1671 
Bringing classic SoilNitrogen code over to X.
 Solutes, SimpleSoilT and outputs now fixed and basic tests OK.

Now wanting to run all tests but please **do not merge** yet.

### CODE REVIEW

**Comment by rcichota** [comment]
@hol353 
Ready to merge if you don't see anything out of place

**Comment by hol353** [comment]
Should this now say resolves rather than working on?

**Comment by rcichota** [comment]
Resolves #1673

**Comment by rcichota** [comment]
Resolves #1671 
Sorry got the wrong number before

**Pull request merged**
