### PR TITLE
Turned soil water warnings into errors

### LINKED ISSUE #1418: Warnings for incorrect soil properties
I had an experiment where SAT > total porosity.  It created millions of warnings and a DB file that was about 1GB.  That caused APSIM to run out of memory.
Really, the error doesn't need to be echoed endlessly, in fact, it could simply be changed to a fatal error.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #1418

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Should this now be a resolved?

**Comment by hol430** [comment]
Fixed. @hut104 time to celebrate

**Pull request merged**
