### PR TITLE
Issue/improve output layers

### PR DESCRIPTION
**Pull request by rcichota**
Working on #2610

I have changed the reference from LayerThickness to the standard Thickness (defined in ISoilWater)
Further I updated the reference to INutrient (instead to ISolute) and add a few more variables (Humic, FOM, etc)

If these changes go well I can remove the reference to LayerThickness from WEIRDO and then eliminate this from ISoilWater as it is a duplicate...

### CODE REVIEW

**Comment by rcichota** [comment]
Retest this please Jenkins

**Comment by rcichota** [comment]
Help please. Something weird has happened with this; firstly, the error from overall pull request is quite cryptic, but more puzzling is the message under my last commit: "This commit does not belong to any branch on this repository." I was working on a single branch, and made commits in sequence to 1) remove LayerThickness; 2) update reference to INutrient, while 3) and 4) were just adding a few more variables, I remembered bulk density the latest... @hol353 @hol430

**Comment by hol353** [comment]
Edit the top comment box and put in a resolves or working on phrase

**Comment by rcichota** [comment]
Thanks @hol353, this is what one get for not committing often enough...

Retest this please Jenkins

**Comment by hol353** [comment]
@rcichota Is there more to do here or do you want it merged?

**Comment by rcichota** [comment]
One more thing to go, sorry couldn't finish it on Friday

**Comment by hol353** [comment]
Good job removing LayerThickness from ISoilWater. Are you happy for this to be merged?

**Comment by rcichota** [comment]
Resolves #2610

**Comment by rcichota** [comment]
Yes, ready to merge

**Pull request merged**
