### PR TITLE
8938 paste valid parent bug

### LINKED ISSUE #8938: Paste model does not obey ValidParent
### What happened?

When you copy and paste a model in the simulation tree the paste does not obey the ValidParent Attribute of the model being pasted unlike Add New.

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by ric394**
resolves #8938

### CODE REVIEW

**Comment by ric394** [comment]
retest this please jenkins

**Comment by par456** [comment]
You've made this branch off another branch, might need to copy your changes for this over to a new branch to clean it up.

**Comment by ric394** [comment]
[like]  Rich, Julian (A&F, Toowoomba) reacted to your message:
________________________________

**Comment by ric394** [comment]
Closing as PR includes unrelated changes. Will submit new PR.

**Pull request closed without merging**
