### PR TITLE
Change CO2 conc error checks

### LINKED ISSUE #7983: CO2 concentration too low for Stomatal Conductance CO2 Function
### What happened?

I am running simulations where the CO2 level is directly read from the met file. The CO2 Level is around 330ppm in the starting year (80´s) of my simulations. I get the error message mentioned in the title. This issue was already discussed here and it seemed that the threshold value was set to 300ppm. I don´t understand why I am still getting this error message. When I run the same simulations with CO2 level above 350ppm everything works fine. Anyone an idea what could be wrong? I am using APSIMX, version 2023.4.7192.0. Thanks!

### What Operating System are you on?

Windows

### LINKED ISSUE #8286: Run with CO2 < 350 ppm
### Describe the new feature

Currently APSIM throws a fatal error is CO2 < 350 ppm.   Atmospheric CO2 reached 350 ppm in 1988 so climate change simulations with base lines prior the this can not currently be run in APSIM.

@hut104 @hol353 

Need to augment CO2 response function so it works at lower concentrations

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #7983 resolves #8286
I have changed the CO2 conc error checks in the RUECO2Function.cs and StomatalConductanceCO2Modifier to throw if CO2 conc < compensation point.
I have also changed the temperature error check in RUECO2Function.cs to throw if temp > 46.5 as the shape of the function inverts at temperatures above this and will give errant values.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 @par456 @ric394 I think there is a problem with the build system.  This PR has been hanging for ages

**Comment by par456** [comment]
Jenkins appears to be down at the moment, will have to look into it.

**Comment by HamishBrownPFR** [comment]
@par456 any update on the build system.  should I ask Jenkins to have another go at this?

**Comment by par456** [comment]
Still down. This'll have to be a job for Dean to look at because I don't have any of the logins for that site. He's at a sprint this week, so its unlikely it'll be fixed today.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hol353 @hut104 can you give this one a quick review and merge if happy.

**Comment by hol353** [comment]
I'll leave this one for @hut104

**Pull request merged**
