### PR TITLE
Changed nutrient to set its surface residue pool using actual ...

### LINKED ISSUE #7225: Maintaining Carbon Balance
There seems to be an issue with the reported values of GPP and NPP: GPP minus RespirationLossC should equal NPP

image

The error comes from lines 1759 and 1766 of PastureSpecies.cs where GPP with units of kgC/ha is calculated from grossPhotosynthesis (also KgC/ha) but is then divided by CarbonFractionInDM (0.4) which converts the kgC to kgDM (which is incorrect). 

public double GPP
        {
            get { return grossPhotosynthesis / CarbonFractionInDM; }

Note that GrossPotentialGrowthWt has the same value as GPP - they use the same formula in the code.

For NPP there is a similar issue (note that respirationGrowth and respirationMaintenance are also in kgC/ha

public double NPP
        {
            get { return (grossPhotosynthesis - respirationGrowth - respirationMaintenance) / CarbonFractionInDM; }

### PR DESCRIPTION
**Pull request by hol353**
(rather than potential) residue decomposition.

Resolves #7225.

### CODE REVIEW

**Comment by hut104** [comment]
We may need to check this. Actual residue decomp probably comes from nutrient

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dean Holzworth ***@***.***>
Sent: Tuesday, August 16, 2022 7:53:13 AM
To: APSIMInitiative/ApsimX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [APSIMInitiative/ApsimX] Changed nutrient to set its surface residue pool using actual ... (PR #7445)


(rather than potential) residue decomposition.

Resolves #7225<https://github.com/APSIMInitiative/ApsimX/issues/7225>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/APSIMInitiative/ApsimX/pull/7445

Commit Summary

  *   16bc11b<https://github.com/APSIMInitiative/ApsimX/pull/7445/commits/16bc11bffadbaa2e88227b6b6bdd2163963c925b> Changed nutrient to set its surface residue pool using actual (rather than potential) residue decomposition.

File Changes

(2 files<https://github.com/APSIMInitiative/ApsimX/pull/7445/files>)

  *   M Models/Soils/Nutrients/Nutrient.cs<https://github.com/APSIMInitiative/ApsimX/pull/7445/files#diff-7b788ba178c8657fdbfefd36be4c9f2716fda0391f38d48770b6b924ea2f8248> (13)
  *   M Models/Surface/SurfaceOrganicMatter.cs<https://github.com/APSIMInitiative/ApsimX/pull/7445/files#diff-dfe9a952d638b78338f0e66a0dc0f2417389f86496e674815cc95d57ab369d16> (7)

Patch Links:

  *   https://github.com/APSIMInitiative/ApsimX/pull/7445.patch
  *   https://github.com/APSIMInitiative/ApsimX/pull/7445.diff

**Comment by hol353** [comment]
Nutrient does calculate actual decomp but previously didn't use it. It simply provided it to SurfaceOrganicMatter. It was setting its surface residue pool using the potential rather than the actual amount of decomp. Net result: it wasn't maintaining a whole of simulation carbon mass balance. 

The interaction between nutrient and surface organic matter models desperately needs a refactor!

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by rcichota** [comment]
Wow, that is major flaw. Hopefully the implications are not too high. And fully agree, a refactor/clarification of roles is needed. Hope to contribute to that over the year...

**Comment by hol353** [comment]
After talking to Neil, my hypothesis was incorrect. What I didn't realise was that the pool called SurfaceResiduePool is in fact not a surface residue pool. It is simply a place to store the potential residue decomposition until SurfaceOrganicMatter asks for it.

The real mass balance problem is in the TotalC output from Nutrient. Closing this PR in lieu of another which fixes TotalC.

**Pull request closed without merging**
