### PR TITLE
Consider XmlIgnore and JsonIgnore when copying properties

### PR DESCRIPTION
**Pull request by hol430**
Working on #1005

### CODE REVIEW

**Comment by hol430** [comment]
@hol353 this is showing big diffs in the agpasture stats. I had a quick peek in PastureSpecies.cs and it appears that a lot of properties with XmlIgnore attributes (e.g. albedo) are serialized in the .json resource files. In fact, as far as I can tell, it seems like most if not all of the properties in the json have an XmlIgnore in the code. Is this deliberate?

**Comment by hol353** [comment]
They have XmlIgnore on them so that they aren't written to the .apsimx files. I now remember trying the change you have in this PR and got very different stats as well. We need to change the approach we're using for deserialising from resource files. This is a mess.

**Comment by hol430** [comment]
I think the problem is that some of these properties with an XmlIgnore are state variables (LAI, CoverGreen, ...), and some are actually model inputs. The problem is I'm not sure which are which in this case. If you look at PastureSpecies.cs, the default value for SpecificLeafArea is 25, but in AGPRyegrass.json, SpecificLeafArea is set to 20. How did you manage to do this? By editing the json? If this property (and others like it) are really a model input, shouldn't they have a display attribute so that they appear in the UI?

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
