### PR TITLE
Updated Gatton Data

### PR DESCRIPTION
**Pull request by hut104**
working on #4773

### CODE REVIEW

**Comment by hut104** [comment]
@hol353We have simply updated an observed data spreadsheet.  If you look at the results, the only changes are for outputs where we have increased the number of observed data.

**Comment by hol430** [comment]
If you look on page 3 on the 'home screen' of the performance tests, you'll see changes to wheat HarvestObsPred. This was due to an issue with the performance tests earlier this morning. If we rerun the tests it should go away (that fixed it for one of the other pull requests anyway).

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hut104** [comment]
Is this right to merge now? We added new OBS data.

**Pull request merged**
