### PR TITLE
Grapevine

### PR DESCRIPTION
**Pull request by junqi108**
working on #1822 
maybe there is an easy way to adding it to the date function, but I am now well versed in that region. So I set up a separated function for it which is also simple. This function is useful when i want to validate the grapevine flowering time which sometimes jumps from December to January.

### CODE REVIEW

**Comment by junqi108** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
@HamishBrownPFR  What is the need for this function? If we have to have it can we make it more generic. Maybe a property that takes a date string like '1-jul'. The code can then do a DateUtilities.GetDate call to turn this into a DateTime. The function could then be called something more generic e.g. DaysSince.

Also don't derive from ICustomDocumentation. Then you can get rid of the Document method.

**Comment by hol353** [comment]
I'd also like a separate issue created for this new function. The pull request can then resolve the issue.

**Comment by HamishBrownPFR** [comment]
Hi @hol353 and @junqi108.  This is needed because some aspects of perennial physiology are analysed relative to a fixed data rather than an identifiable event like sowing that we have in annuals.  
I am not sure the best way to do this.  We could modify the accumulate function to do the job but it would get messy so I suspect a separate function that increments day number between specific dates and resets on specific dates would be the best start.  
@junqi108  use the Accumulate function as a template but instead of incrementing on PostPhenology do it on a clock event so it is not then limited to plant relevance,  something like StartOfDay would be appropriate.  Also instead of specifying StartStageName, EndStageName and ResetStage name change these to dates.  Doing it this way will mean to accumulate days it needs a child constant of 1 but the child function could be other things which will make the function more generic.
Perhaps we call this function AccumulateByDate and we call the current Accumulate Function AccumulateByPhase to make their distinction clear.

**Comment by HamishBrownPFR** [comment]
@junqi108 give me a call or skype if you need some help turning the Start End and Reset stages to dates.

**Pull request closed without merging**
