### PR TITLE
Make Predicted / Observed more flexible

### LINKED ISSUE #7534: More flexibility for Predicted / Observed models
Currently predicted / observed models always use SimulationName as one of the fields to match on when comparing predicted and observed data. There are use cases (e.g. when comparing 2 water balance models - via an experiment - same observed data applies to both simulations) where this field needs to be removed from the fields to match on.

### PR DESCRIPTION
**Pull request by hol353**
Resolves #7534

### CODE REVIEW

**Review by jbrider — COMMENTED** [review]
The documentation for sorghum has added strange characters again.
It looks like it is replacing hyphens with something unknown.

**Comment by hol353** [comment]
Where exactly are the strange characters?

**Comment by jbrider** [comment]
image

There are more instances of the hyphen issue further down.

**Comment by hol353** [comment]
Hmm ok. Add it as a GitHub issue.

**Pull request merged**
