### PR TITLE
Feature/pmf interface

### PR DESCRIPTION
**Pull request by jbrider**
working on #127

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
Test this please

**Comment by hol353** [comment]
Test this

**Comment by hol353** [comment]
Test this please

**Comment by hol353** [comment]
test this please

**Comment by hol353** [comment]
test this please

**Comment by jbrider** [comment]
test this please

**Comment by hol353** [comment]
Test this please

**Comment by hol353** [comment]
Test

**Comment by hol353** [comment]
Test this please

**Comment by hol353** [comment]
test this please

**Comment by hol353** [comment]
retest this please

**Comment by hol353** [comment]
retest this please

**Comment by jbrider** [comment]
resolves #127

**Comment by hol353** [comment]
Jason

Did you mean to close this pull request? It hasn't been merged yet.

Dean

On 10/06/2015 12:49 PM, Jason wrote:

Closed #128<https://github.com/APSIMInitiative/ApsimX/pull/128>.

**Comment by jbrider** [comment]
I'm finished with it - but think I clicked on the close button when I
shouldn't have.

**Pull request merged**
