### PR TITLE
Working on Issue #16 - enabling use of excel files for weather data

### LINKED ISSUE #16: Better weather file reading
1) Can we allow tabs in met files?  People keep making that mistake.
2) Can we just allow xlsx met files?  Save an extra step

### PR DESCRIPTION
**Pull request by cla473**
Resolves #16 - enabling use of excel files for weather data

### CODE REVIEW

**Comment by hol353** [comment]
We are having problems with a hardware failure on one of our servers. Jenkins seems to be affected so you pull request might take a while. Where're working on it.

Dean

On 19/05/2016 12:40:09 PM, Loretta Clancy <notifications@github.com> wrote:

Resolves Issue #16<https://github.com/APSIMInitiative/ApsimX/issues/16> - enabling use of excel files for weather data

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/APSIMInitiative/ApsimX/pull/849

Commit Summary

  *   Working on Issue #16 - enabling use of excel files for weather data

File Changes

  *   M Models/Weather/Weather.cs<https://github.com/APSIMInitiative/ApsimX/pull/849/files#diff-0> (16)
  *   M UserInterface/Presenters/MetDataPresenter.cs<https://github.com/APSIMInitiative/ApsimX/pull/849/files#diff-1> (22)
  *   M UserInterface/Views/TabbedMetDataView.cs<https://github.com/APSIMInitiative/ApsimX/pull/849/files#diff-2> (34)

Patch Links:

  *   https://github.com/APSIMInitiative/ApsimX/pull/849.patch
  *   https://github.com/APSIMInitiative/ApsimX/pull/849.diff

**Comment by cla473** [comment]
Thanks for letting me know.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
