### PR TITLE
Fix the grazing day counter for SimpleGrazing

### PR DESCRIPTION
**Pull request by sno036**
The counter was zeroing to -1 rather than 0 .

@MarkLieffering  - this should fix it.

resolves #5736

### CODE REVIEW

**Comment by sno036** [comment]
resolves #5736

**Comment by sno036** [comment]
retest this please jenkins

**Comment by sno036** [comment]
@hol430 - are you able to see what is wrong with this? I updated before making the (very simple) change and it compiles on my computer.

**Comment by hol430** [comment]
Yeah you need to edit the initial comment, and add resolves #5736.

**Comment by sno036** [comment]
retest this please jenkins

**Pull request merged**
