### PR TITLE
Alter sow method so cultivar overwrite object can be passed in rather…

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
… than needing to find it from the crop model.  This will be needed for the generalised verson of scrum that will calculate parameters externally and pass them into the model

Working on #7869

### CODE REVIEW

**Comment by hol353** [comment]
Why do we need a 'cultivarOverwrites' argument added to the sow method call? What is the use case? 

We already have 'Cultivar' class which overrides things in the plant model.
We also have a 'ModelOverrides' class that can be dropped on a parent plant to allow for a generic plant with overrides for specific plant species. 

Both of these have a public string[] property that specifies what needs to be overridden. These properties could be modified by a manager script or some other model if you are wanting to calculate parameters at runtime.

**Comment by HamishBrownPFR** [comment]
@hol353.  There will be some parameters in the generalized version of SCRUM that are calculated from user specified information each time the crop is sown so the Cultivar and ModelOverwrites approaches are not suitable.  I was thinking passing a cultivar object in at sowing would be a tidy way of doing this but can look at writing something that using the set method instead.

**Comment by hol353** [comment]
Presumably you must already have a manager script that creates the cultivar to pass to SCRUM. Rather than changing PMF, can you use set lines in the manager script instead? I don't really want more complexity and more ways to do things in PMF if there is an alternative.

**Comment by HamishBrownPFR** [comment]
I will see what I can come up with.  Design for the Scrum is still pretty fluid at this stage.  Would you be keen for me to run you through where I am at to get your feed back?

**Comment by hol353** [comment]
Yes, might be good to get a quick update on where you're going with SCRUM.

**Comment by HamishBrownPFR** [comment]
I have changed the approach so cultivar does not need to be passed in.  Closing this pull request as redundant now

**Pull request closed without merging**
