### PR TITLE
Pinus modifications to address review comments and finalise for release

### PR DESCRIPTION
**Pull request by sme016**
Copied TreeThinning and modified as TreeThinningFromAboveOrBelow and included it unused in the BFG simualtion for the validation and used as a modified Control treatment in the example.

Working on #6058

### CODE REVIEW

**Review by hol430 — CHANGES_REQUESTED** [review]
@sme016 - Hi Phil, I see you've committed the Pinus.pdf autodocs file. Normally we don't commit this - you'll need to delete this (e.g. using your file explorer), then it will show up in sourcetree as deleted. You can then stage/add this change, commit and push. Let me know if it gives you any problems.

**Comment by sme016** [comment]
Now removed.
I put it there, as Jason was surprised it wasn’t there for the review. Anyway, it’s not needed now and anyone can generate it when needed.

Thanks,
Philip

**Review by hol430 — APPROVED** [review]

**Comment by hol353** [comment]
@sme016 Why have the stats changed? Were you expecting changes?

**Comment by sme016** [comment]
I extended (Clock) the simulations for the full set of observations available for the few sites where I had previously (for the review) cut them short due to issues of disease, or very low stocking – as requested by Hamish. This led to a deterioration in some stats, but I didn’t think enough of a deterioration to warrant filtering some OvP graphs to the former date range.

I also included comments that warn folk about this issue for the sites concerned, i.e. IMPAC and Puruki.

Hopefully that is ok with you and for review purposes, but let me know if more work is needed.

**Pull request merged**
