### PR TITLE
Fixing Undo not selecting node

### LINKED ISSUE #7070: Strange behaviour when clicking undo
Clicking undo will automatically select the model which is modified by the undo operation, but it won't (necessarily) redraw the right-hand panel.

### PR DESCRIPTION
**Pull request by par456**
Resolves #7070

### CODE REVIEW

**Comment by ric394** [comment]
add to whitelist jenkins

**Comment by ric394** [comment]
add to white list jenkins

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by par456** [comment]
Resolves #7070

**Comment by par456** [comment]
Retest this please jenkins

**Comment by par456** [comment]
Retest this please jenkins

**Comment by hol353** [comment]
Retest this please jenkins

**Comment by hol353** [comment]
Retest this please jenkins

**Comment by hol353** [comment]
Retest this please jenkins

**Pull request merged**
