### PR TITLE
CLEM Refactor resource transaction to provide style and amount

### LINKED ISSUE #6285: Resource transaction model needs better row-based formatting
The current CLEM resource transaction class has gain and losses as column, but pivoting reports needs a style (gain/loss) and an amount

### PR DESCRIPTION
**Pull request by lie112**
Resolves #6285

### CODE REVIEW

**Comment by lie112** [comment]
Is this my problem with the code?

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
No, there was a problem a few days ago which I think has been fixed.

**Comment by lie112** [comment]
Do I need to pull all new changes to this commit for it to work, or will a retest of Jenkins solve the problem?

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
