### PR TITLE
Fix OnEvent Function so it evaluates the IFunction Value every time...

### LINKED ISSUE #4146: Bug in OnEventFunction
The OnEventFunction will only update its value when we change phases. However the child functions' values could potentially change at any time. This problem was identified because we have a sorghum cultivar which modifies the value of a constant function which is referenced by the OnEventFunction. The OnEventFunction continues to return the old value of the constant even after the cultivar changes have been applied.

@HamishBrownPFR is this the intended behaviour of this function?

### PR DESCRIPTION
**Pull request by jbrider**
resolves #4146 
 ...it is referenced, - not just on event change.

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 Error in jenkins, in the multi process job runner code:

```csharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at Models.Core.Run.JobRunnerMultiProcess.PipeServerTaskThread() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Run\JobRunnerMultiProcess.cs:line 130
```

I'm not sure how this code is supposed to work, but it seems odd that it's suddenly causing problems since we haven't changed anything in this space recently.

**Comment by hol353** [comment]
reboot muck and try again?

**Comment by hol430** [comment]
@jbrider - looks like this isn't going to work after all. Should this (and #4146) be closed?

**Comment by jbrider** [comment]
Yes, they can be closed.
It looks like everywhere it's implemented is designed to use cached values.

**Pull request closed without merging**
