### PR TITLE
Allows crop tasks between multi-harvest crops

### LINKED ISSUE #7130: CLEM: selling milk and tracking activities in multi harvest crops
I am encountering two issues with CLEM simulations:

1.	Selling milk with ResourceActivitySell :

I wanted to sell milk by reserving some for households in my CLEM simulations, i.e., sell all except the user-specified amount. I am using the ResourceActivitySell property and Reserve Amount selling style to perform this activity. However, the HumanFoodLedger report shows that surplus milk is sold only once in the first year. In the subsequent months/years, the model sold everything milked instead of selling by reserving the specified amount. Could this be a bug?

2. Tracking activities in multi harvest sequence

The online help crop rotation demonstrates specifying the "first" and "last" harvest in a multi-harvest sequence using a harvest tag column allows multiple harvests and a sequence of crops, and avoids duplication of land preparation and planting after the first harvest. The example clearly shows land preparation and planting performed before the first harvest, and then no activities performed after the first harvest except harvesting. Such an approach is great for cases where only harvesting activity is performed. 

In my case, I am attempting to run Sugarcane-Mustard rotation and I need to track activities such as irrigation, fertilisation etc., after the first harvest (see attached snapshot below after March 2002, in blue dots) until the last harvest (before rotation to the next crop in the sequence). I need this to get the monthly cash flow throughout the year for different activities. However, this does not allow me to track other activities after the first harvest.  Mango is grown in a separate plot/field and Sugarcane-Mustard rotation is grown in another plot/field. Is the rotation meant to track the harvest only? 
CropRotation

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7130

### CODE REVIEW

**Comment by lie112** [comment]
I'm getting an empty datastore test fail in unit testing. Is this just a retest issue?

**Comment by hol430** [comment]
Probably an intermittent problem. Hard to believe it could have been caused by the changes on this branch. I'll look into it.

**Comment by lie112** [comment]
I found there may have still been a problem with a clem simulation in Validation test. I've fixed it. Maybe it just wasn't reporting the correct error.

**Comment by lie112** [comment]
Resolves #7145
This was accidently committed here as well.

**Review by hol430 — APPROVED** [review]

**Comment by lie112** [comment]
It seems the CreateInstallation process last ran on 2 Feb and the jenkins page says it's currently disabled. Can this be restarted to build the latest pull requests into upgrades?

**Comment by hol430** [comment]
The release builds are still running, but they're failing because the code signing cert has expired. Currently looking into it.

**Comment by lie112** [comment]
Any news on the purchase of the certificate to get updates running again?

**Comment by hol430** [comment]
No update, there have been some difficulties obtaining a new certificate.

**Pull request merged**
