### PR TITLE
Updated each project to use v4.5.2 of the .NET framework.

### PR DESCRIPTION
**Pull request by holzworthd-agr**
Working on #2247

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
@holzworthd-agr Drew can you create an issue here in GitHub saying that you are upgrading to verion 4.5.2 and then reference the newly created issue in the top edit box in this pull request? Put in:

Working on #????

Doco on this can be found here: https://github.com/APSIMInitiative/ApsimX/blob/master/CONTRIBUTING.md

**Comment by holzworthd-agr** [comment]
@hol353 Fixed.

**Comment by hol353** [comment]
Jenkins, add to whitelist

**Pull request merged**
