### PR TITLE
Test enabling N2O from nitrification

### PR DESCRIPTION
**Pull request by sno036**
working on #6410 

Modified nutrient.json for 1% loss of nitrified N to N2O to see what the flow on effects would be.

### CODE REVIEW

**Comment by sno036** [comment]
Scanning the checks, all the changes were minor and there were more improvements (44) than worsenings (27).

The advantage of having the N2O losses turned on is that this is a known, but often minor, contributor to N2O emissions and including this makes APSIM both more compliant with current understanding and in agreement with several other models.

Can this be merged please?

**Comment by hut104** [comment]
Can I suggest that we look at N2O outputs and a few other things prior to merging?

There are currently no data for N2O or NAtm outputs and so nothing on this front will appear in the tests. The thing we are testing does not appear in the tests.

Many of the crop models have minimal N test data (e.g. not even fertiliser trials) and so optimal N rate trials are unlikely to respond to this change.

Perhaps some sensibility tests or something?  For example, the suggestion that the N losses should be minor contributor can be tested.  There should be papers that can tell us something about the expected levels.  Perhaps this could be used.  I have previously asked researchers working in this area to submit data/tests in their possession and they have failed to do so.  This was going to be the next step for testing this part of the model prior to changing things.  In the absence of this perhaps tests on emissions factors or the like.

The effect may also be context dependant.  I think the oil palm model has some annual stats in its reporting in the example file.  That could be used to look for changes in emissions for high input tropical agroforestry systems.  The review by Pardon might be useful to check N2O levels in these systems.  This sort of information will be in the APSIM Oil Palm N2O paper.  Peter thorburn's sugar work or the work on wheat in WA are other diverse environments.

It might be interesting to look at low input systems (Africa or Australia) that rely on mineralisation.  A long term simulation (e.g. 100 years) might show a cumulative impact if we have an added N loss pathway.  ie does N rundown accelerate.  The Brigalow catchment study might a possible candidate.

All this might depend on the initial test on whether we have significantly impacted N losses or not.




________________________________

**Comment by sno036** [comment]
In Classic this algorithm was one that was optionally turned on and it was used in several publications (see below a non-exhaustive list in which it was used to my knowledge). Given this history, that Nutrient is replicating SoilNitrogen, and that turning it on has led to minimal changes in the test suite I think it is time to turn it on in NextGen rather than sending a lot of time gathering simulations not currently in the test suite - particularly as not all those crops will be available in NextGen or that they might be reliant on SWIM (which is not quite there yet). If future insertions into the test suite reveal an issue then the setting can be always revisited. 

https://doi.org/10.1016/j.agee.2009.12.014 - Thorburn et al.
https://doi.org/10.1016/j.agee.2009.12.016 - Huth et al.
https://doi.org/10.1111/gcb.13965 - Ehrhardt et al.
https://doi.org/10.1029/2020GB006561 - Fuchs et al.
https://doi.org/10.1029/2019JG005261 - Fuchs et al.
https://doi.org/10.1016/j.envsoft.2017.01.005 - Snow et al.

**Comment by hol353** [comment]
Closing this without merging in favour of #6438.

**Pull request closed without merging**
