### PR TITLE
Jenkins release job needs to extract wheat NPI data

### PR DESCRIPTION
**Pull request by hol430**
Working on #4982

### CODE REVIEW

**Comment by lie112** [comment]
Will this still get the upgrade manager working even though this wasn't a Resolves?

**Comment by hol430** [comment]
There won't be an upgrade created for this pull request. An upgrade will be created the next time a resolves pull request gets merged.

**Comment by lie112** [comment]
Thanks. Is there a way to force the upgrade or create a quick resolved issue rather than wait for others to make one and it to get accepted by @hol353 which may be on Monday? I have some users awaiting the last fixes.

**Comment by hol430** [comment]
Looks like there's another problem with the releases anyway. Looks like it might be a problem with clem(?) - here's an excerpt from the log:

```
Creating documentation from C:\Jenkins\workspace\CreateInstallation\ApsimX\Examples/CLEM/CLEM_Example_Cropping.apsimx
System.Exception: Error obtaining data from database:  ---> APSIM.Shared.Utilities.SQLiteException: no such column: Reason
   at APSIM.Shared.Utilities.SQLite.Prepare(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 645
   at APSIM.Shared.Utilities.SQLite.ExecuteQuery(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 537
   at Models.Storage.DataStoreReader.GetData(String tableName, String checkpointName, String simulationName, IEnumerable`1 fieldNames, String filter, Int32 from, Int32 count, String orderBy, Boolean distinct) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Storage\DataStoreReader.cs:line 394
   at Models.SeriesDefinition.ReadData(IStorageReader reader, List`1 simulationDescriptions) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\SeriesDefinition.cs:line 344
   at Models.Series.GetSeriesDefinitions(IStorageReader reader, List`1 simulationFilter) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\Series.cs:line 186
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at UserInterface.Presenters.GraphPresenter.DrawGraph() in C:\Jenkins\workspace\CreateInstallation\ApsimX\ApsimNG\Presenters\GraphPresenter.cs:line 101
   --- End of inner exception stack trace ---
System.Exception: Error obtaining data from database:  ---> APSIM.Shared.Utilities.SQLiteException: no such column: Reason
   at APSIM.Shared.Utilities.SQLite.Prepare(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 645
   at APSIM.Shared.Utilities.SQLite.ExecuteQuery(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 537
   at Models.Storage.DataStoreReader.GetData(String tableName, String checkpointName, String simulationName, IEnumerable`1 fieldNames, String filter, Int32 from, Int32 count, String orderBy, Boolean distinct) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Storage\DataStoreReader.cs:line 394
   at Models.SeriesDefinition.ReadData(IStorageReader reader, List`1 simulationDescriptions) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\SeriesDefinition.cs:line 344
   at Models.Series.GetSeriesDefinitions(IStorageReader reader, List`1 simulationFilter) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\Series.cs:line 186
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at UserInterface.Presenters.GraphPresenter.DrawGraph() in C:\Jenkins\workspace\CreateInstallation\ApsimX\ApsimNG\Presenters\GraphPresenter.cs:line 101
   --- End of inner exception stack trace ---
Creating documentation from C:\Jenkins\workspace\CreateInstallation\ApsimX\Examples/CLEM/CLEM_Example_Grazing.apsimx
System.Exception: Error obtaining data from database:  ---> APSIM.Shared.Utilities.SQLiteException: no such column: Reason
   at APSIM.Shared.Utilities.SQLite.Prepare(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 645
   at APSIM.Shared.Utilities.SQLite.ExecuteQuery(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 537
   at Models.Storage.DataStoreReader.GetData(String tableName, String checkpointName, String simulationName, IEnumerable`1 fieldNames, String filter, Int32 from, Int32 count, String orderBy, Boolean distinct) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Storage\DataStoreReader.cs:line 394
   at Models.SeriesDefinition.ReadData(IStorageReader reader, List`1 simulationDescriptions) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\SeriesDefinition.cs:line 344
   at Models.Series.GetSeriesDefinitions(IStorageReader reader, List`1 simulationFilter) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\Series.cs:line 186
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at UserInterface.Presenters.GraphPresenter.DrawGraph() in C:\Jenkins\workspace\CreateInstallation\ApsimX\ApsimNG\Presenters\GraphPresenter.cs:line 101
   --- End of inner exception stack trace ---
System.Exception: Error obtaining data from database:  ---> APSIM.Shared.Utilities.SQLiteException: no such column: Reason
   at APSIM.Shared.Utilities.SQLite.Prepare(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 645
   at APSIM.Shared.Utilities.SQLite.ExecuteQuery(String query) in C:\Jenkins\workspace\CreateInstallation\ApsimX\APSIM.Shared\Utilities\SQLite.cs:line 537
   at Models.Storage.DataStoreReader.GetData(String tableName, String checkpointName, String simulationName, IEnumerable`1 fieldNames, String filter, Int32 from, Int32 count, String orderBy, Boolean distinct) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Storage\DataStoreReader.cs:line 394
   at Models.SeriesDefinition.ReadData(IStorageReader reader, List`1 simulationDescriptions) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\SeriesDefinition.cs:line 344
   at Models.Series.GetSeriesDefinitions(IStorageReader reader, List`1 simulationFilter) in C:\Jenkins\workspace\CreateInstallation\ApsimX\Models\Graph\Series.cs:line 186
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at UserInterface.Presenters.GraphPresenter.DrawGraph() in C:\Jenkins\workspace\CreateInstallation\ApsimX\ApsimNG\Presenters\GraphPresenter.cs:line 101
   --- End of inner exception stack trace ---
```

**Comment by lie112** [comment]
Oh, yeah. Not sure why I didn't get an error from Jenkins. 
I'll fix them now. That will get the resolved working!

**Comment by lie112** [comment]
Its a bad column name in a graph. These don't get checked by Jenkins.

**Comment by hol430** [comment]
Yep there's another issue about that I think....basically, the create installer job does some things which aren't actually tested by jenkins -such as creating the docs.

**Pull request merged**
