### PR TITLE
Sorg release

### PR DESCRIPTION
**Pull request by jbrider**
working on #572

### CODE REVIEW

**Comment by jbrider** [comment]
@hol353 This can be merged and released. The documentation is in a usable state - I will keep making some improvements to it when I get a chance but it doesn't need to hold it up any longer.

**Comment by hol353** [comment]
@jbrider
@APSIMInitiative/reference-panel 

Well done on getting the sorghum model ready for release. I don't want to hold it up but Neil and I have a couple of questions about the sorghum model:

- Is MicroClimate's calculated PotentialEP value used in sorghum? From looking through the source code I can't find anywhere it is used.
- Given the narrow validation range (Gatton, Hermitage, Icrisat) can you add a plausibility test i.e. a range of locations of different climate types. Other crop models have this that you could probably easily copy. 
- In your PPT to the RP (https://github.com/APSIMInitiative/ReferencePanel/issues/96) you show a plausibility 'Time of Sowing' test. Where is that?
- Sorghum is used as a dual purpose crop in this part of the world. Can you show a test where animals reduce the leaf area? Other models have tests that you could copy.

I don't think any of this would take long as there are existing examples that you can copy and modify.

**Comment by jbrider** [comment]
The SorghumPlausibilityRuns files has 6 simulations in it including:
- Sowing Date which is the time of sowing example
- Intercropping which shows how to enable Microclimate in a shared cropping situation as presented and discussed during the review.
- CO2 experiment as requested during the review process
- A Forage example which is currently disabled - due to replacements not working with forage examples as discussed during the Canola review. It can be enabled when the model is released.
- RowConfiguration example to show skip row handling.

I will add a location example to that file as well.

**Comment by hol353** [comment]
Thanks @jbrider I didn't see the separate SorghumPlausibilityRuns .apsimx file. A lot of work has gone into it which is great! Well done. Add a location example to it and I'll move the files from UnderReview to the validation directory and merge this PR.

**Comment by jbrider** [comment]
@hol353 This is right to merge.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Sorghum is released. Well done @jbrider and the sorghum team!

**Pull request merged**
