### PR TITLE
Fixed simulation errors being ignored

### LINKED ISSUE #2011: Error conditions and exceptions are not always reported when they should be
If a simulation is pointing to a non-existent weather file (because that file has been moved or deleted), it appears to run (very quickly), but the user receives no indication that anything was wrong.

### PR DESCRIPTION
**Pull request by hol353**
Resolves #2011

### CODE REVIEW

**Comment by hol353** [comment]
retest this please jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Pull request merged**
