### PR TITLE
adding facts data 

### PR DESCRIPTION
**Pull request by sarchontoulis**
working on #6725

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Review by hol430 — COMMENTED** [review]
Are these .apsimx files supposed to contain the full soybean and maize models' structure? This means that the files won't automatically receive any updates to these models, so eventually we won't really be testing the model that people are using?

image

**Comment by hol353** [comment]
No they will have to be removed.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@sarchontoulis We notice that you have copies of maize and soybean in the 'Replacements' folder in the .apsimx files. Have you changed anything in the maize and soybean models or can we just delete the models under Replacements?

**Comment by hol430** [comment]
I checked soybean in a diff tool earlier and there were a few additions (a few cultivars and some extra IFunctions if I recall correctly).

**Review by hol353 — APPROVED** [review]
Merging this for now as it seems to be holding up our build system because of the password protected zip file.

**Comment by sarchontoulis** [comment]
thanks @hol353 
yes, we did a few changes in the replacements; let us know if we need to resend the files without any changes or additions in the replacements

**Pull request merged**
