### PR TITLE
set cohort age at appearance 

### LINKED ISSUE #3207: Cohort age at appearance
The cohort Age at appearance is initialized as a function of main stem appearance rate "(PotLeafTipsAppeared - TipToAppear) * MainStemNodeAppearanceRate.Value;". Consequently, the actual growth duration is not equal to the parameter GrowthDuration. For Leaf 1, the actual growth duration is equal GrowthDuration. For Leaf 2 and others, the actual growth duration is smaller than GrowthDuration. (Not include in the pull request)

I also attached the example apsimx file [leaf-area-cohort-1.zip](https://github.com/APSIMInitiative/ApsimX/files/2251566/leaf-area-cohort-1.zip) I used in which I have provided enough carbon, water, and nitrogen to make sure there are no any stress to constrain leaf expansion. 

Check P4 and 5 generated by master branch [potential-leaf-size-master.pdf](https://github.com/APSIMInitiative/ApsimX/files/2251565/potential-leaf-size-master.pdf). Leaf 1, 4, and 7 is bigger than potential. Leaf 2, 3, 8 and 9 are smaller than potential.

Check P4 and 5 generated with this pull request plus setting cohort age equal to zero at appearance [potential-leaf-size-new.pdf](https://github.com/APSIMInitiative/ApsimX/files/2251564/potential-leaf-size-new.pdf). All leaves have the same potential and actual leaf area.

Call me if you want to discuss more.

### PR DESCRIPTION
**Pull request by byzheng**
resolves #3207

### CODE REVIEW

**Comment by byzheng** [comment]
retest it please jenkins

**Comment by byzheng** [comment]
retest this please jenkins

**Comment by hut104** [comment]
Hi @byzheng 
Are these still required?  It may be worth closing this pull request.

**Comment by byzheng** [comment]
@hut104 I will would like to merge this pull request. @HamishBrownPFR Could you have a look at the changes?

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@byzheng this change will certianly fix #3207 but I am unsure if it will create problems elsewhere.  I can't remember the rational for programming it this way but there would have been some reason for building in this complexity.  For some reason cohort age needed to take account of the part days aging that occurred on the day of initialization.    Will think on this some more and check the performance tests once they are rerun

**Comment by HamishBrownPFR** [comment]
@byzheng  I think we need to merge this pull request to get the leaf size behaving as intended but I wan't to review the results in a bit more detail to see if there are some fixes we can make to model parameters to reduce the impact of the change.

**Comment by HamishBrownPFR** [comment]
@hol353 I am working with @byzheng to get this pull request completed.  There are lots of diffs but all are trivial apart for for barley where n has changed.  We can't work out why this has changed and think it is a problem with the performance testing system.  We have done a comparison of running the change version on one computer and the master on another and compared the results and they are identical so I am not sure why the performance test system thinks n has changed

**Comment by hol353** [comment]
@hol430 This looks like a problem with the performance test web site in the 'Graphical Results' table. It is showing a change in 'n' whereas the tabulated results is not showing this.

**Comment by hol353** [comment]
@HamishBrownPFR I think we can merge this. Are you happy?

**Comment by hol430** [comment]
I wonder if this is related to the fact that this pull request is about 6 months old. I'd be interested to see if the stats are different if you opened a new pull request and re-ran the stats.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hut104** [comment]
This may impact people working on prototypes - I know that Allan's chickpea will change results. This raises the issue again that we don't publish the stats for prototypes.  Perhaps we should publish these, even if they don't hold up the merge - at least we'd know about impact on developers.
________________________________

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
