### PR TITLE
Check the value of N.TotalPlantDeman

### PR DESCRIPTION
**Pull request by byzheng**
Working on #2104 

FN  equals to zero if N.TotalPlantDeman has smaller value, but I am not sure this is the best method.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
Why do you want to set FN to zero of demand is small.  FN is an index of Nitrogen supply (relative to demand) and if demand is small and supply is large is should be a large number, not zero.

**Comment by byzheng** [comment]
I think you are correct. We don't need to care about the extreme big value in this case as FN is just a ratio of demand and supply. The figure just looks ugly.

**Comment by HamishBrownPFR** [comment]
Is it better to put an upper limit on FN,  Off the top of my head things that respond to FN use values up to about 3 so higher values don't have any meaning.  Could limit it to 5??

**Comment by byzheng** [comment]
It will be better to check the reason for small N.PlantTotalDemand (E-14 in my tested case, See below for demand and supply). I would expect it should be equal or close to 0 at `Ripening` stage. 

PS: Double.Epsilon equal to 4.94065645841247e-324 in C#.

image

**Pull request closed without merging**
