### PR TITLE
Updated seasonal destocking and added reporting ability.

### LINKED ISSUE #4577: Ruminant seasonal destocking does not seem to be working
Users have reported difficulty using the seasonal destocking activity in CLEM.

### PR DESCRIPTION
**Pull request by lie112**
resolves #4577 
Upon investigation I have identified a few bugs and improved this component
Added ability to report activity status when destocking is required.
Other minor CLEM improvements included.

### CODE REVIEW

**Comment by lie112** [comment]
I'm not sure how to fix Potato FinalYieldData to get this pull accepted.

**Comment by hol430** [comment]
My pull request #4575 fixes the performance tests problems but @hol353 is on leave until next week so it may not be merged straight away.

**Comment by lie112** [comment]
Thanks. It didn't occur to me there was a backlog of relevant fixes

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
