### PR TITLE
Allow overloaded methods to be included in Report variables

### LINKED ISSUE #7714: Report cannot handle overloaded methods
Report throws "Ambiguous" error when trying to report an overloaded method.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7714 

Added code to identify argument type by the passed values in a method included as variable in reports
This allows us to link the correct overloaded version of the method to the report.

### CODE REVIEW

**Comment by lie112** [comment]
What's the apsim convention for adding strings to the variable entry for reports?
Is it to use single quotes? I was using escaped double quotes but it's messy as actually needs the escape escaped! \\\"
I will change this to single quotes for consistency and ease for users if that's the case.

**Comment by hol353** [comment]
>What's the apsim convention for adding strings to the variable entry for reports?
I don't understand what you're asking.

**Comment by lie112** [comment]
What I meant was if we need to pass a string to a method in report do we ignore text delimiters or use quotes or single quotes.
Model.WorkWithModel("Modelname", 2) for WorkWithModel(string, int32)
We were working to get a method call working and I was struggling to get a string passed or it had the quotes included with the string. I think I worked it out, but now can't remember the solution.

**Comment by hol353** [comment]
Ahh ok. I'm not sure if you need quotes or not. I can't remember.

**Pull request merged**
