### PR TITLE
Changes to sorghum/c4maize to mirror recent changes in classic

### PR DESCRIPTION
**Pull request by hol430**
Working on #572

@jbrider, I noticed that you changed maize's frost kill threshold to 1, but left sorghum's at -3.5. Is this deliberate?

### CODE REVIEW

**Comment by hol430** [comment]
@jbrider the changes to the stats are fairly minor, are you happy for this to be merged?

**Comment by jbrider** [comment]
@hol430  Sorry, this slipped through yesterday. Maize and Sorghum should be the same - were they different in Classic, or in NextGen.  Can you remove the sdRatio change out for now - want to make sure it's not affecting the frost change outputs.

**Comment by hol430** [comment]
Ah, I was talking about classic when I said the frost_kill values were not the same, but I just double-checked and they are indeed the same. I guess I was looking at the changes in APSIMInitiative/APSIMClassic#1847 where maize.xml was changed but sorghum.xml wasn't.

**Comment by jbrider** [comment]
Yeah, there was one update that was out of sync. I thought I'd managed to do it again!

**Comment by jbrider** [comment]
This can be merged.

**Pull request merged**
