### PR TITLE
Implementing a skip-row configuration

### LINKED ISSUE #5068: Implementing a skip-row configuration
If there is not, can we implement something like this?

image

### PR DESCRIPTION
**Pull request by BenAbabaei**
Resolves #5068

### CODE REVIEW

**Comment by hut104** [comment]
These changes seem to be implementing switches (not usually a good way of implementing things). Could we simply get people to enter the two rowspacings on left and right?  That would avoid the use of flags, would be explicit, and would be easier to understand and would allow infinitely more options, especially for agroforestry or more complex simulations.

**Comment by BenAbabaei** [comment]
Hello @hut104 . I will make the change. What would you do with rowConfig? Currently SkipPlant and SkipRow are not accessible via Sowing routine. Should I move everything in that routine and make them 'input' parameters?

**Comment by hol430** [comment]
retest this please jenkins

**Comment by BenAbabaei** [comment]
@hol430 can this be merged?

**Pull request merged**
