### PR TITLE
Updated descriptions, units, bounds for SoilWater.cs

### PR DESCRIPTION
**Pull request by mcauliffer**
Working on #1205 
Updated descriptions, units and bounds for SoilWater.cs

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
When I pull down this pull request onto my computer and then click on 'SoilWater' under a soil in a simulation I get 'Object reference not set ...' errors. When you put [Description] tags on properties, the user interface will try and show that property to the user. I don't think we want the user to see all these properties. Need to discuss with Val.

**Comment by mcauliffer** [comment]
Thanks Dean. I’ll check it out. Sorry.

**Pull request closed without merging**
