### PR TITLE
Implement new filtering and sorting into CLEM

### LINKED ISSUE #6692: Refactor and implement new list filtering and sorting by properties and attributes
After the initial release and user requested improvements made to CLEM it needs a code clean up and some improvements with respect to memory and performance.  This includes better management of individuals (ruminant and labour) throughout in preparation for the new implementation of generic filtering and sorting of lists for activities that allows the user to filter and sort on any property or attributes tags assigned to individuals.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #6692 
Implements new generic filtering and sorting with both reflection and a simpler faster approach for large herd sizes
Completes the code clean up of CLEM 
Fixes bugs and improves model from testing across a range of simulations.

### CODE REVIEW

**Comment by lie112** [comment]
I have been working on Mike Stower's repo with this pull request as I needed to fix up the code
I tried to update his branch to the master changes as I though that might have been an issue for jenkins
This branched the repo and I am now 6 commits ahead of Mike's branch I am working with
How do I get the master up to my latest changes? Is this a rebase to my last change?

**Comment by hol430** [comment]
You should be able to just pull from master (on the APSIMInitiative repo) and then push to this branch Mike's repo.

**Comment by lie112** [comment]
I'm a bit stumped. I am pulling from mikes repo and all was good till I added all the latest changes. Then I fixed the issues with Jenkins but my commits while I push them back the repo don't automatically go to jenkins for a rerun. It seems my last six commits are beyond the position of the repo we are pulling. I went to pull from my branch but it's outside my apsimx repo that has permission. Still easily confused with source control

**Comment by hol430** [comment]
I'm not sure I understand the problem here, but I can't think of a scenario which would necessitate a rebase. Copying files manually is of course the ultimate fallback but I'd consider it a last resort. Feel free to give me a call on teams - might be easier than going back and forth on github.

**Comment by hol430** [comment]
Sure. Feel free to reopen if need be.

**Pull request closed without merging**
