### PR TITLE
Fixed minor problem with cleaning up memory on destruction of a TreeView

### LINKED ISSUE #3618: Tab display is corrupted when simulations are opened
If you are not running in a build environment, with source code at hand, the tab for the first simulation opened hides the "Home" tab.

### PR DESCRIPTION
**Pull request by zur003**
Resolves #3618

### CODE REVIEW

**Comment by hol430** [comment]
Does this fix #3618?

**Comment by zur003** [comment]
@hol430 - Yes, it should fix #3618. I accidentally did a git commit while there was already a pull request open, and so combined to different patches,.

**Comment by hol430** [comment]
Should probably edit the initial comment then, to add "Resolves #3618". Weird how the bug doesn't show up in debug mode - maybe it's the result of some optimisation performed by the compiler in release mode.

**Comment by zur003** [comment]
I changed the initial comment. Do I need to have Jenkins run it again?

**Comment by hol430** [comment]
No need - Jenkins doesn't go looking for a the version number until after this is merged, when the CreateInstallation job gets run.

**Pull request merged**
