### PR TITLE
Maize fixes

### LINKED ISSUE #2295: Odd Parameterisations of maize
The KNO3 and KNH4 parameterisations are not consistent

Root extension has not water stress or temperature response

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #2295

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hut104 can you give your opinion on this one.  I discovered that we had no temperature or moisture stress responses on maize root extension.  Implemented somethig as I don't think the current situation is plausable.  Some stats have shifted but overall model performance is still acceptable??

**Comment by hut104** [comment]
I've investigated the performance tests and I'm happy that the new model is an improvement.  Many attributes are improved.  Any stats that have declined seem to have low values of N, and so are likely to jump around with minor changes.

**Comment by hol353** [comment]
Can you do a pull and then repush to this pull request? There's been a change to the lucerne PO table name  (in another pull request) that I want included in this pull request before I accept the stats.

**Pull request merged**
