### PR TITLE
Bugfixes for Azure job submission/viewer

### PR DESCRIPTION
**Pull request by holzworthd-agr**
Working on #1137 and #806.

Fixed a variety of bugs present in the Azure job viewer. Added new options for downloading results.

### CODE REVIEW

**Comment by hol353** [comment]
Drew, you don't have a "working on #???" or "resolves #???" in the top edit box. You can modify the top box above to add this.

**Comment by holzworthd-agr** [comment]
@hol353 Fixed. Any idea what's causing Jenkins to generate a bad version number?

**Comment by hol353** [comment]
The missing issue number in the top box causes the bad version number (-1).

**Comment by holzworthd-agr** [comment]
So retesting this now should fix the problem?

**Comment by hol353** [comment]
Yes it will, but can we wait for half an hour? I'm running something else at the moment. I'll tell jenkins to retest when I'm ready.

**Comment by holzworthd-agr** [comment]
Yeah, that's fine.

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
