### PR TITLE
Np iwork

### LINKED ISSUE #4725: Include controlled environment data in wheat test set
Need to include this data in test set to facilitate model improvement for NVI project
@EnliWang @byzheng  fyi

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
Resolves #4725

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 @hol430.  This pull request is failing because three simulations are throwing errors.  This is due to a bug that is a bit challenging to fix so I have disabled the three simulations so they don't run.  However, Jenkins if running them anyway.  Is this intended behavior or a bug?

**Comment by hol430** [comment]
Not deliberate - if it's disabled then it shouldn't be run. Which simulation is this? The PalmerstonNorthCE experiment is the one throwing errors, and it doesn't seem to be disabled.

**Comment by HamishBrownPFR** [comment]
I have disabled the three simulations that are throwing errors, not the entire experiment

**Comment by HamishBrownPFR** [comment]
@hol430.  Could I get some help with this one.  Sorry don't wan't to nag.  I am needing to get this pull request merged in to progress some project work.  Issue #4713 is holding me up also.   Let me know if this is not a quick fix and I will come up with a work around

**Comment by hol430** [comment]
Hi Hamish - the errors are being thrown from ApsimX/Tests/Validation/Wheat/ControlledEnvironment/Wheat.apsimx. The palmerston experiment in this file dosen't seem to have any of the simulations disabled, although the palmerston experiment in Wheat.apsimx does have 3 simulations disabled. If these experiments are the same, do we really need them in both files?

**Comment by HamishBrownPFR** [comment]
Ahh, sorry, major rookie mistake.  No we don't need both files, I forgot to delete the ones in the controlled environment folder.  I will delete them

**Comment by HamishBrownPFR** [comment]
@hol353, @hol430 something weird is going on with this pull request.  It has failed on the wheat validation which I was expecting because I have added some new Observation and Simulations in.  However, n has in creased by a factor of 8 for all the wheat variables tested.  This has also caused some subtle changes in the stats.
Any ideas why n has changed?

**Comment by hol353** [comment]
Hmm no idea. I don't think it was me. I haven't changed much lately.

**Comment by hol430** [comment]
Maybe it's related to the conflicts in Wheat.apsimx?

**Comment by HamishBrownPFR** [comment]
@hol430 I have resolved conflicts and got it running again but still have the same issue with n increasing by a factor of 8.  
It is not rally affecting the stats, the changes are small and expected because I have added more observation and more simulations and from this perspective it could be merged (@hol353 ) but I suspect we don't want to merge this until we have resolved what is causing n to increase.

**Comment by hol430** [comment]
This should be fixed by #4740

**Comment by HamishBrownPFR** [comment]
Great, many thanks @hol430

**Comment by HamishBrownPFR** [comment]
From a wheat perspective this is good to merge.  Few minor diffs that are expected because I added some data and made a few minor changes to simulation setups.

However, the stats have changed for Soybean and I don't know why.  Suspect it is something to do with the changes @hol430  made to the multiExcel object as n has changed

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@HamishBrownPFR Can you update this branch so that it includes Mariana's AgPasture changes I merged this morning?

**Comment by HamishBrownPFR** [comment]
@hol353 Done, running now

**Comment by hol353** [comment]
@HamishBrownPFR Are these diffs what you expect?

**Comment by HamishBrownPFR** [comment]
There was some changed parameter values that have snuck in there, I have reverted them now

**Comment by HamishBrownPFR** [comment]
@hol353 this is good to merge now.  Diffs are because I have added more data and simulations.   A few small ones because I have changed some harvest rules which is causing a few additional ones to show up and a few to drop off.  Will tidy this up later as part of ongoing work with the wheat model.  Ok to merege for now because the model has not changed, just the amount of data being used in stats

**Pull request merged**
