### PR TITLE
Merge netcore3 branch

### PR DESCRIPTION
**Pull request by hol430**
Working on #5344

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Are we game to merge this?

**Comment by hol430** [comment]
@APSIMInitiative/developers - once this is merged, you will need to install the .NET Core 3.1 SDK in order to compile apsim. I've updated the compilation instructions on the netlify site, but if you're using windows it boils down to downloading and running the [visual studio installer](https://visualstudio.microsoft.com/vs/) to modify your existing visual studio installation, and selecting the .NET Core cross-platform development workload (highlighted in the screenshot below). If you're using Linux/mac I'd suggest using your distribution's package (if available) or the [dotnet-install script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) otherwise.

Development Contribute Compile Windows InstallNetCore

**Comment by hol430** [comment]
@hol353 - up to you. Once people get the sdk installed then it should "just work". We could get Neil to try it on his own later in the week when we're in the office. We could also give people a few days' lead time to get the sdk installed. Or you could just merge it now.

**Comment by hol430** [comment]
Brave! I think we can probably delete the netcore3 branch on the main repo now - it's just an older version of this branch.

**Pull request merged**
