### PR TITLE
Some changes in root in relation to water uptake and root angle

### LINKED ISSUE #5052: Some changes/cleanup in root water uptake to implement root angle
- Root does not need a two-part 'CalculateWaterSupply' as both parts do the same thing.
- Available soil moisture must account for 'rootProportionInLayer'.
- MaxDepth is not needed as root never passes the layer with XF=0.
- 'layeproportion' of the last layer is already accounted for in 'rootProportionInLayer'.
- Root activity must not use RootProportionInLayer as it is already used to calculate Water Uptake. 
- Replacing ProportionThroughLayer with RootProportionInLayer. 
- Some cleanup and renaming (to follow APSIM style).

### PR DESCRIPTION
**Pull request by BenAbabaei**
Working on #5052 

- Root does not need a two-part 'CalculateWaterSupply' as both parts do the same thing.
- Available soil moisture must account for 'rootProportionInLayer'.
- The formula to calculate a semi-circular pattern for root system was corrected.
- A semi-elliptic pattern was added, which may be moved to a separate class/function in future.
- MaxDepth is not needed as root never passes the layer with XF=0.
- Minor changes related to Sorghum model.
- 'layeproportion' of the last layer is already accounted for in 'rootProportionInLayer'.
- Root activity must not use RootProportionInLayer as it is already used to calculate Water Uptake. 
- Replacing ProportionThroughLayer with RootProportionInLayer. 
- Some cleanup and renaming (to follow APSIM style).

### CODE REVIEW

**Comment by BenAbabaei** [comment]
retest this please jenkins

**Comment by BenAbabaei** [comment]
retest this please Jenkins

**Comment by BenAbabaei** [comment]
@hol353 would you please have a look at this pull so I could move to our next step, if there is nothing wrong with the proposed changes/fixes?

**Comment by BenAbabaei** [comment]
retest this please Jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Pull request closed without merging**
