### PR TITLE
Fix a few AgPasture bugs

### PR DESCRIPTION
**Pull request by rcichota**
Working on #7224
working on #7225
working on #7289

Fixing a few bugs reported by @MarkLieffering plus a couple I identified (and created) in my last pull request
 - ensure respiration outputs are zero after killing a plant
 - correct units for GPP, NPP, NAPP, and NBPP
 - fix bug related to tissue turnover rates

### CODE REVIEW

**Comment by MarkLieffering** [comment]
Thanks @rcichota !

**Comment by hol353** [comment]
@rcichota Yesterday Neil made a fix to SWIM suction routine to try and improve SWIM's stability. I've merged that change and done a pull on your branch to include Neil's fix. I've then gone and put SWIM3_testing.apsimx back into your simulation and it now runs without SWIM crashing which is good.

This branch now seems to be failing in a manager example: 

Examples\ManagerExamples\RegressionExample.apsimx

This example has a sensibility test that does a regression between irrigation amount and harvested wt of agpasture. It throws if the slope of the regression line is < 0. I'm not sure why we have this test. It might just be an example of how to write a post simulation test in which case you can probably change it to something else to get Jenkins to pass.

**Comment by rcichota** [comment]
Thanks @hol353 I got the error message for that slope test early in the week and was wondering what it was for...
I need to get this AgPasture stuff merged in, it is getting messy. I had done a few fixes and added outputs that your commit overwrote. No big deal (and the question about the use of carbon content in detachment rate made me check it. It is correct (from the original code - EcoMod) and I will reinstate it / rewrite as it is part of converting digestibility...).
Where I am strugling is that all my changes tend to make AgPasture (in the test simulation) produce too much. A lot of it is because the way the soils were set up, so I need to verify them... and there are many...

**Comment by sno036** [comment]
@rcichota - I would be OK with temporarily taking the Radcliffe sites out of the test set and concentrating on the higher quality data at Winchmore and Ruakura. Would that assist progress?

**Comment by MarkLieffering** [comment]
@sno036 , @rcichota. Would the long term Flock House data set be of use? There are a few gaps when we were maintaining the system and did not graze.

**Comment by sno036** [comment]
retest this please Jenkins

**Comment by rcichota** [comment]
@hol353 
This can now be merged. I still wat to add some datasets to the validation, but ran out of time this week. Will try get them early next week and be done with this. At least until Val and Mark find if there is an error in the C balance...
BTW, I have removed four simulations, as they will be added as 'detailed' simulations and test on their on right (I was using two of them - plus another set from a newer trial - as baseline in my changes, need a bit of clean up and I will add them back next week)
Resolves #7224
Resolves #7225
Resolves #7289
Resolves #7292

**Comment by hol353** [comment]
Hi @rcichota This PR deletes SWIM3_testing.apsim. We don't want to do that! Can you undo the deleted file?

**Comment by rcichota** [comment]
@hol353 
This issue with the SWIM simulation was an odd one, I did check and hope that was the only one...
I have updated the multispecies simulation as well as added a few more of the datasets I have been promising
Resolves #7325

**Comment by rcichota** [comment]
Hi @hol353 
Are you happy with the state of this or do you see were I can make further amendments?
If you think things are ok, could you merge it, please. I would like to update our version of APSIM in PowerPlant and run some simulations with the fixes I've made...
Thanks

**Pull request merged**
