### PR TITLE
Damage function of frost and heat for canola and wheat

### PR DESCRIPTION
**Pull request by PengchengHU**
Working on #7406  Added the damage functions for canola and wheat, and the corresponding datasets for validating the damage functions included as well.

### CODE REVIEW

**Comment by BrianCollinss** [comment]
Add "Working on #7406" or "Resolves #7406" to the first comment.

**Comment by PengchengHU** [comment]
> Add "Working on #7406" or "Resolves #7406" to the first comment.

Hi @BrianCollinss thanks for the suggestion.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@PengchengHU Is this ready to be merged or are you going to make further changes?

**Comment by PengchengHU** [comment]
> @PengchengHU Is this ready to be merged or are you going to make further changes?

Hi Dean, yes, it is ready to be mergerd.

**Comment by BrianCollinss** [comment]
When the function is added, the parameters are all zero even though wheat is selected by default. I have to change crop to canola and then reselect wheat to get the correct parameters.

image

**Comment by PengchengHU** [comment]
Hi Brain, we had noticed this issue and will fix it later.

**Comment by TobiasK12** [comment]
Are there any publications validating this function or using it for climate impact assessments?

**Comment by PengchengHU** [comment]
Yes, we are preparing a paper on it. Note that since we continuously bring more comprehensive datasets to estimate the parameter values of the damage function, the values will be subject to change.

**Pull request merged**
