### PR TITLE
Use Azure references that are compatible with .Net core 3.

### PR DESCRIPTION
**Pull request by zur003**
Working on #4272 
@hol430 - would it be possible for you to test this before it is merged? I'm not really set up to use Azure.

### CODE REVIEW

**Comment by hol430** [comment]
I will have a play but it will have to wait until next week

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by hol430** [comment]
@sno036 @hol353 would one of you guys be able to test this as I don't have an azure account/credentials.

Eric - looks like there's a problem with the performance tests. I'll look into it

**Comment by sno036** [comment]
I tried earlier today but wasn't able to get it to work. Will consult with Dean tomorrow.

**Comment by hol430** [comment]
Looks like the problem in the performance tests collector was caused by incrementing the version of Newtonsoft.Json package used by apsim. I've issued a pull request to fix this by making the same change to the performance tests collector, but if it gets merged it might cause all other pull requests to fail until this one is merged.

**Comment by zur003** [comment]
@hol430  - Thanks for looking into this. Is the problem the change in version of Newtonsoft.Json, or that I added it to the UnitTests projects? I shall revert to 11.0.2 and see what happens...

**Comment by hol430** [comment]
I think the problem is the change in Newtonsoft.Json. What's the background on this - is version 11 not supported under .net core?

I don't really see a problem with changing the version - it's just that we needed to also remember to change the version in the performance tests collector (I think!).

**Comment by lie112** [comment]
Doesn't .Net Core have built in JSON support?

**Comment by sno036** [comment]
I just tied this with Azure and got an error. It might be that the easiest if I supplied a Azure creds to someone who knows what they are doing so they can test. Just let me know who.


System.IO.IOException
  HResult=0x80070020
  Message=The process cannot access the file 'C:\Users\snowv\OneDrive - AgResearch\Desktop\Temp\TestAzure.db' because it is being used by another process.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, CompressionLevel compressionLevel, Boolean includeBaseDirectory)
   at UserInterface.Presenters.NewAzureJobPresenter.SubmitJob_DoWork(Object o, DoWorkEventArgs e) in C:\aaUnderVC\apsimNextGen\ApsimNG\Presenters\NewAzureJobPresenter.cs:line 338
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by hol430** [comment]
Looks like it's trying to zip and upload the .db file which is locked. We don't even need to upload the .db file - this bug was probably there from the beginning but we never noticed. Am happy to look into it if you want, but I'll need some sort of access to an azure vm.

**Comment by sno036** [comment]
@hol430  - yes can give you access. I don't think this is your highest priority at the moment (graphs, documentation web page, ...) so let me know when you want to deal with it and I will send a licence file privately.

**Pull request merged**
