### PR TITLE
Apsim wheat

### PR DESCRIPTION
**Pull request by ZhiganZhao**
Working on #4773

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 This is Zhigan who is working with Enli, Neil and I on the Wheat project.  Please verify

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by HamishBrownPFR** [comment]
I have reverted out the changes to Wheat.json the @ZhiganZhao committed as we will need to do some more work on the phenology model.  This pull request now removes some duplicate data for #4710, adds some missing data for some NZ trials and adds some code changes for the CAMP phenology model

**Comment by HamishBrownPFR** [comment]
This pull request is a bit contrived now, I will close and put a clean one up

**Pull request closed without merging**
