### PR TITLE
Generalise temp interp

### LINKED ISSUE #5121: Tomorrows met data
@hol353 @hol430 @hut104 @junqi108 we are working on the grapevine model and bud burst is quite sensitive to short periods of chilling and are needing a more detailed daily air temperature interpolation.  The problem is the approach we want to use needs to know tomorrows minimum temperature.  APSIM currently has no notion of tomorrows weather.

I can program another a MinTtomorrow variable into IWeather and have it go get this from the met file.  However, this feels quite messy and I am wondering if anyone can think of a better way.

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #5121.

I have changed the met object to read a day ahead to get tomorrows met data and retain the past two reads to use for today and yesterdays met

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 @hol430.  I think there is something odd happening with the performance testing.  This pull request has changes on n for the wheat test but no changes to wheat simulations or observations.  I think these changes are being retained from the previous pull request?

**Comment by hol353** [comment]
retest this please jenkins.

I think I merged the other PR just as you submitted this one. Might have been a timing issue. Anyway see if re-running it works.

**Comment by HamishBrownPFR** [comment]
@hol353 it has failed for a different reason this time, didn't seem to run the tests

**Comment by HamishBrownPFR** [comment]
@hol353 it has worked, just takes some time for the graphs to appear on the performance website

**Comment by HamishBrownPFR** [comment]
Is it surprising that it failed the performance tests in less that 14 min?

**Comment by hol353** [comment]
Jenkins says it took 18 minutes which is about right:
image

**Comment by HamishBrownPFR** [comment]
Thats weird, when I looked at it your retest comment was made 14 min ago and it already had a red X.  I kept looking at it and the number of graphs kept increasing.  Does it show it has failed as soon as one goes red but then keep working its way through the tests and adding the graphs to the performance site

**Comment by HamishBrownPFR** [comment]
I will reopen this pull request.  I cannot reproduce the diffs it is failing on so want to check it is not an issue with the performance tests

**Pull request closed without merging**
