### PR TITLE
Root demand function source code only

### PR DESCRIPTION
**Pull request by junqi108**
Working on #1832

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
Hi @hol353 this is a follow on from #1834 where you requested @junqi108 to take the changes out of the model xml files so you could put this refactor into the change tool.

**Comment by hol353** [comment]
Sorry, this now seems to have conflicts. Can you fix?

**Comment by hol353** [comment]
Hi @HamishBrownPFR, I can't seem to see any branches under PlantAndFoodResearch. Have my permissions being revoked?

**Comment by hol353** [comment]
Sorry @HamishBrownPFR,  my mistake. I had the URL wrong. I can see this branch now. All good.

**Comment by hol353** [comment]
I have changed the file converter to add a DMDemandFunction to root if it doesn't exist. I've pushed changed file to this branch. Jenkins will still run red though because the XML files in the resources will need changing manually. Can you go and do that please?

Retest this please Jenkins

**Comment by hol353** [comment]
Retest this please Jenkins

**Comment by junqi108** [comment]
Retest this please Jenkins

**Comment by HamishBrownPFR** [comment]
Thanks for you help with this @hol353.  Would it be worth our while learning how to add these changes into the change tool or is it better for you to do this?

**Comment by junqi108** [comment]
Hi Dean @hol353, I have modified the XML in the resource fold. I did not change the APSIMx in the test and validation folder. It seems some of them appear in the resource fold but some not.

**Comment by junqi108** [comment]
Shall I fix the errors in the WEIRDO manually? It is probably caused by the management file that calls the root partition.fraction? Shall I also add the demand function in the root part?

**Comment by HamishBrownPFR** [comment]
I will have a look at it

**Comment by HamishBrownPFR** [comment]
Hi Junqi.

Sorry it took me a while to get onto this

You are correct.  Weird needs to have .DMDemandFunction added into the scripts that are setting the partitioning fraction.  There are two simulations where this is happening Validation\LandP  and Sensibility\Transpiration

Your pull request also failed on the grapevine tests.  For some reason there were two DMDemandFunction nodes on the root.  The change tool, thanks to deans modifications will take a PartitionFraction node that is a child of root and replace it with a DMDemandFunction node even if there is already a DMDemandFunction node present already.  However this confuses the model.  Make sure you delete the redundant PartitionFraction node on root in you grapevine test file.

Give me a call if you have any further problems.  I will be in my office all day today and all of next week.

Hamish

**Comment by junqi108** [comment]
Thanks very much, Hamish. Hope it will pass this time.

**Comment by junqi108** [comment]
the test has passed, but the build was failed.  The process cannot access the file APSIM.setup because it is being used by another process.

**Comment by junqi108** [comment]
Retest this please Jenkins

**Comment by HamishBrownPFR** [comment]
@hol353 I think there is a problem with Jenkins.  The build is throwing errors when trying to create the installation

**Comment by hol353** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
Hi @zur003 There have been a few times now when the installation creating on Jenkins fails - like now. It seems that there are files locked that can be written. Seems to happen when it is creating the Debian installation. Can you remote desktop into Scoop and have a look? I've left Process Hacker running - at the bottom you'll see fciv.exe and findstr.exe running which I suspect is the problem.

**Comment by zur003** [comment]
Yes, those were the culprits. I've killed the zombie processes, and restarted stuff on Jenkins.

Part of this is my fault. I had a build yesterday that got "stuck" when building the installers (I'm still not sure why). I tried to kill the job through Jenkins, but it apparently left a few processes running.

**Comment by hol353** [comment]
@zur003 : Can you modify the batch file to stop this from happening again?

**Comment by zur003** [comment]
@hol353 : I don't really know what's going wrong, so I don't know how to fix it. There is a possibility that I triggered a problem yesterday by doing a commit to a branch while its pull request was still being processed. Not sure whether that caused a problem or not.

**Comment by zur003** [comment]
Retest this please Jenkins

**Pull request merged**
