### PR TITLE
Setup APSIMX Siumlation

### PR DESCRIPTION
**Pull request by Xiumei2017**
Working on #1721 
Hi Dean,
I am working with Hamish on the lucerne model, I add some more simulations on it.

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
Add to whitelist Jenkins

**Comment by HamishBrownPFR** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
retest this please Jenkins

**Pull request closed without merging**
