### PR TITLE
Avoid new syntax for out parameters, to allow compilation with older …

### LINKED ISSUE #2276: VS2015 build broken
New language features in AzureJobDisplayView.cs have broken the Visual Studio 2015 build.

### PR DESCRIPTION
**Pull request by zur003**
…compilers (e.g., using VS 2015). Resolves #2276

### CODE REVIEW

**Comment by zur003** [comment]
Retest this please Jenkins

We really need to fix these PerformanceTests problems...

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Restest this please Jenkins

**Comment by hol353** [comment]
I cancelled job on Jenkins due to conflicted files

**Comment by zur003** [comment]
Closing until I sort out git merge problems.

**Pull request closed without merging**
