### PR TITLE
Orchard model

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #3801

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 for some reason this pull request is throwing a error in trying to build the nutrient documentation.  However, I don't think I have touched anything that relates to that.  Any suggestions on what is going on here appreciated.

Hamish

**Comment by hol353** [comment]
This is an intermittent problem that we need to fix.

retest this please Jenkins.

**Comment by hol430** [comment]
> This is an intermittent problem that we need to fix.

This is probably a result of the way the mapsui -> skia image conversion has been implemented. I suspect the download is timing out (see `MapRenderer.cs:107`); I don't really have time to look into this now, but a quick and easy fix might be to increase the timeout duration a bit, and to explicitly throw an exception with a helpful error message if `result` is still null after the loop there. But maybe there's a more elegant way to handle this in the mapsui API, I can't say I'm really familiar with it.

**Comment by HamishBrownPFR** [comment]
@hol353 could you merge this one please.

**Pull request merged**
