### PR TITLE
Switch to a more recent version of Mono.TextEditor.

### LINKED ISSUE #2439: Braces matching in script editor
Use the braces matching feature in the manager script editor like APSIM Classic has.

### PR DESCRIPTION
**Pull request by zur003**
Resolves #2439 

Note that this uses a newer version of Mono.TextEditor,dll, which will have some small differences in appearance (e.g., highlighting of the current line).

### CODE REVIEW

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by zur003** [comment]
retest this please jenkins

**Comment by zur003** [comment]
retest this please jenkins

**Pull request merged**
