### PR TITLE
small changes to get SimpleLeaf working for sorghum implementation

### PR DESCRIPTION
**Pull request by jbrider**
Working on #572

### CODE REVIEW

**Comment by hol353** [comment]
@jbrider You've added 2 optional functions. We're moving away from optional functions, instead making all functions mandatory. To modify all .apsimx files that use SimpleLeaf, create a file converter method in:

    ApsimX\Models\Core\ApsimFile\Converter.cs

If you have a look at the UpgradeToVersion10 method in this file you'll see an example of a change method for adding several constant functions to an organ.

I also notice that you an empty setting for TipsAtEmergence. This means that it can't be set. If this is intended then get rid of the empty setter.

**Comment by jbrider** [comment]
Why the move away from optional? 
It seems like a better solution than writing a converter every time?

I must have missed bringing the setter back in from a snapshot - will fix that.

**Comment by jbrider** [comment]
So the existing optionals that are in there, just haven't been removed yet?

**Comment by jbrider** [comment]
TipsAtEmergence is in the ILeaf interface as an int - is it preferred to change TipsAtEmergence to an IFunction and change the interface to a double, or have the getter for TipsAtEmergence return the result of an IFunction as an int?  
I'm only interested in defaulting this value to a 1 so that Structure will start counting leaves - is it acceptable to save the TipsAtEmergence in the xml file as 1? It is completely hidden from the interface at that stage. I haven't checked yet if the documentation picks it up.

**Comment by hol353** [comment]
We are working at getting rid of optional functions. I removed most (all?) from GenericOrgan a few months ago.

I would leave the interface returning an int then write a getter in SimpleLeaf that returns the int result of a 'TipsAtEmergenceFunction'. Then for any SimpleLeaf organ in all crops have the converter insert a constant function called 'TipsAtEmergenceFunction' that returns a zero so that existing behaviour is retained. Then for your sorghum crop model have it return 1.

I'm unsure what you mean when you say "... is it acceptable to save the TipsAtEmergence in the xml file as 1? It is completely hidden from the interface at that stage".

**Pull request closed without merging**
