### PR TITLE
Rewrite codes for nitrogen redistribution

### LINKED ISSUE #2138: In PLANT calculate reallocation before retranslocation?
@HamishBrownPFR In the nitrogen supply function, is it more logical to calculate reallocation before retranslocation? As `nitrogenSupply.Retranslocation` removes `nitrogenSupply.Reallocation` although there are no impact for current wheat model ( `senescenceRate` equals to zero).
 
https://github.com/APSIMInitiative/ApsimX/blob/871830c04d39f368ac450d33aa55237d54e2653f/Models/Plant/Organs/GenericOrgan.cs#L298-L304

### PR DESCRIPTION
**Pull request by byzheng**
resolves #2138

### CODE REVIEW

**Comment by byzheng** [comment]
@HamishBrownPFR Following on our discussion in #2138, I have rewrote codes for GenericOrgan and LeafCohort about nitrogen reallocation and retranslocation. Could you have a look in case I have made stupid changes?

**Comment by HamishBrownPFR** [comment]
Looks OK to me

**Comment by hol353** [comment]
This pull request can't be merged until Jenkins passes. Lots of failed simulations!

**Comment by byzheng** [comment]
For my understanding, all non-structural nitrogen (metabolic and storage) can be reallocated and retransallocated into other organs. So I changed the reallocation through including the StorageN and MetabolicN.

```csharp
 nitrogenSupply.Reallocation = Math.Max(0, (startLive.StorageN + startLive.MetabolicN) * 
                                        senescenceRate.Value() * nReallocationFactor.Value());
nitrogenSupply.Retranslocation = Math.Max(0, (startLive.StorageN + startLive.MetabolicN) *
                                      (1 - senescenceRate.Value())  * nRetranslocationFactor.Value());
```

The failed reason is the `if` statement doesn't include `startLive.MetabolicN`.
```csharp
// Retranslocation
            if (MathUtilities.IsGreaterThan(nitrogen.Retranslocation, startLive.StorageN + startLive.MetabolicN - nitrogenSupply.Retranslocation))
                throw new Exception("N retranslocation exceeds non structural nitrogen in organ: " + Name);
// Reallocation
if (MathUtilities.IsGreaterThan(nitrogen.Reallocation, startLive.StorageN))
   throw new Exception("N reallocation exceeds non structural nitrogen in organ: " + Name);
```
I can easily fix the bug above. But I am not sure how to deal with the problem below.

For retranslocation, I guess we can first remove from `StorageN`, then `Metabolic`
```csharp
 Live.StorageN -= nitrogen.Retranslocation;
```

For reallocation, I don't understand why Live need to remove StorageN here. I guess all senescence part should be removed in other codes including dry mass and nitrogen. Or we should remove the StorageN from the `Dead`, instead of `Live`.

```csharp
Live.StorageN -= nitrogen.Reallocation;
```

@HamishBrownPFR Any comments here?

**Comment by hol353** [comment]
@HamishBrownPFR The diffs here are only probably minor but it takes quite a while to go through the diffs. Should we relax the tolerances on the stats (I think it is 1%) or should we find a better way to do this?

**Comment by HamishBrownPFR** [comment]
@hol353 probably both.  The tolerance is perhaps to tight.  Also a better way for reviewing diffs is needed.  Would it be better to list diffs sorted from largest to smallest so we can see what the worst diff is and how quickly the diffs trail off to insignificance.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by byzheng** [comment]
The major difference come from nitrogen concentration for wheat and barley. I can expect these changes as the pull request changes the nitrogen supply in reallocation and retranslocation. I have quickly gone through all figures with obvious difference and didn't notice the huge changes. @HamishBrownPFR Any comments about it? 

It will be better to retest it when pull request #2154 is merged as #2154 changed the nitrogen supply.

**Comment by hol353** [comment]
OK. I've accepted #2154 and have updated the stats on this one. I can't see any major diffs. @HamishBrownPFR ?

**Comment by hol353** [comment]
retest this please jenkins

**Comment by byzheng** [comment]
It seems the results are similar as the previous test. @HamishBrownPFR  and @hol353 Any comments about it?

**Comment by HamishBrownPFR** [comment]
Ill have a look at it

**Comment by HamishBrownPFR** [comment]
@byzheng I can see a problem with this change.  You are now accounting for Metabolic N in reallocation and retranslocation supply.  However, Under SetNitrogenAllocation() Retranslocation and Reallocation are only being subtracted from the StorageN.  We need to partition Reallocation and Retranslocation of N between Storage and Metabolic when it is removed.

**Comment by byzheng** [comment]
@HamishBrownPFR I don't figure out a good way to subtract metabolic from Retranslocation and Reallocation, so I removed the metabolic from GenericOrgan. Will keep in mind and fix it later.

**Comment by HamishBrownPFR** [comment]
@byzheng it would be a good idea to log a specific issue so it is not forgotten

**Comment by byzheng** [comment]
Can be merged?

**Comment by HamishBrownPFR** [comment]
@byzheng The size of some of diffs being generated here worry me.  Can you put the changes to leaf and the changes to generic organ into separate pull requests so we can get a better idea of where the diffs are coming from?

**Comment by HamishBrownPFR** [comment]
@hol353 and @byzheng I have done some testing of this pull request and have some relevent comments on #2203 (a pull request I used for testing the geneirc organ code changes specifically but have closed now).  I was uncomfortable with the size of some of the diffs that were being created by this pull request.  Alot were changes to stats that were already poor and can be ignored.  Of the ones that were effecting stats that were showing a good fit the ones I have checked could be related to a small number of observations making the stats very sensitive to small changes or to the poorly fitting points withing a larger group getting worse.  The latter suggesting the bug that is being fixed here was partly covering other problems in model parameterisations which can be resolved in due coarse.

@hol353 I recommend merging this pull request.

**Comment by byzheng** [comment]
@HamishBrownPFR Very appreciate it for your careful checking. I agree with your comments in #2203. It should not have any impacts on Wheat for changes in generic organs. I guess it is related that minimum, critical and maximum nitrogen concentration are not totally linked with structural, metabolic and storage DM, which I think you design PMF with this way. 

PS: @hol353 I also noticed this similar problem in other pull request that retrieving some variables impacts on the results in which changes should not have any impacts (#2158). I don't track down into details, but there are something we need to worry about and check carefully.

**Comment by HamishBrownPFR** [comment]
@byzheng no worries, we work together an keep making APSIM better.

**Pull request merged**
