### PR TITLE
.net core/gtk3 ApsimNG

### PR DESCRIPTION
**Pull request by hol430**
Working on #5344

Converted ApsimNG to the sdk-style csproj format and have both netcore and framework builds using the same files. Also added the unit tests project back into the solution, ~although I haven't converted it to the sdk-style format yet.~

### CODE REVIEW

**Comment by hol430** [comment]
Thanks Eric- I guess this means you got it working ok on your machine?

**Comment by zur003** [comment]
@hol430 - Yes, I got it working, although there are still a few rough edges. For example, sqlite3.dll is not being automatically copied into NetCoreBin. Also, I'm having trouble starting a debug session from the IDE. But mostly it's working as expected. The next thing I'd like to attempt is getting basic text/code editing working with gtkSourceView. I have this mostly working, but need to tidy it up a lot before it's ready to be merged. That currently uses a GtkSharp 3 wrapper for SourceView that I compiled myself - I need to check to see whether anyone has put a similar version on nuget.

**Comment by hol430** [comment]
Good point about sqlite3.dll, although in the long run it might be worth switching to the nuget package. For now I'll just modify the csproj file to fix this.

For the sourceview, I've submitted a pull request against the GtkSharp repo to add some bindings. In the long run this will mean we should end up with a nuget package for this. For now, I've manually generated the .nupkg files and uploaded them to myget ,and added a reference to this to ApsimNG.csproj. The only caveat is that - for now - you will have to install libgtksourceview4 via msys and then place it somewhere where the clr will find it (e.g. in the NetCoreBin directory). I've been in touch with the maintainer of GtkSharp about packaging this with the other native binaries which are automatically downloaded when you build a project using GtkSharp, so this shouldn't be an issue for developers in the longer term. We will need to think about how we ship these to our end users however, as there's no official way of doing this yet - although there may be something in the works there as well.

There are also some issues with debugging in visual studio which are caused by a bug in the particular version of the native GLib library provided by the GtkSharp package. There's an issue in the GtkSharp repo about this and it should hopefully be fixed sometime in the next few weeks when we update the native libraries provided by GtkSharp.

image

**Comment by zur003** [comment]
@hol430 - So the target will be GtkSourceView 4 rather than GtkSourceView 3? That will be good, although I noticed that the Windows Gtk 3 distribution that I'm using (which I think may have been auto-downloaded by the GtkSharp stuff) packages SourceView 3 rather than 4. I need to go back and see what the differences were.

**Comment by hol430** [comment]
Yep, I have targeted sourceview 4(.0.0 from memory), and yeah it's not included in the files which are auto downloaded by GtkSharp (ie the files downloaded to %LOCALAPPDATA%\Gtk\3.24), but we're working on adding it to those files.

**Comment by hol430** [comment]
@hol353 this could probably be merged, I don't know if I'll be getting back onto this this week (note that the PR is against the netcore3 branch, not master).

Current status is that all projects now build under netcore and netframework. We have a working code editor with syntax highlighting, code completion, etc. Intellisense for other components (e.g. report) seems to be working. Probably lots of things which don't work but the main things which still need to be implemented:

- Some sort of HTML/markup renderer. Currently I've implemented IHTMLView by sticking the raw HTML into a textview widget
- Syntax highlighting in report
- Ctrl+shift+space to trigger method signature helper dialog in code editor
- Find/replace in code editor (this will actually be more powerful than the current version, since gtksourceview api supports regex)
- Few issues with grids such as colours in the profile view, column header vertical alignment

I wonder if at some point in the future we would want to merge this into master. This would mean that anyone compiling apsim would need to install the .net core sdk (>=3.0 I think), which can be done via the visual studio installer, or via microsoft's [dotnet-install](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) scripts. For the average user, this wouldn't have much of an impact (once the sdk is installed), since the .net framework (gtk2) build is still the default when you hit run. Switching to .net core builds can be done via a dropdown in visual studio. Any thoughts?

**Pull request merged**
