### PR TITLE
Apsim wheat

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #4773

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353  @hol430  this pull request appears to have stalled, is Jenkins working?

**Comment by hol353** [comment]
Back up now. Your job is running.

**Comment by HamishBrownPFR** [comment]
Thanks @hol353

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hol353  @hol430  can anyone tell me why my pull request is failing on the Morris simulations?

**Comment by hol430** [comment]
Yes there are some problems with the R packages. Previously it was failing intermittently, now it's failing every time. Will let you know when it's fixed.

**Comment by HamishBrownPFR** [comment]
Thanks @hol430

**Comment by hol430** [comment]
I think it should be fixed now...#5664 is not getting these errors anymore

**Comment by hol430** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hol353  this is good to merge.  Have added another experiment to test set is why performance stats changed

**Pull request merged**
