### PR TITLE
Fixed line highlighting bug in Mono text editor. Also fixed problem w…

### PR DESCRIPTION
**Pull request by zur003**
…ith getting enumeration text for popup menus. Working on #2518

### CODE REVIEW

**Comment by hol430** [comment]
Is this failing because it's trying to use the same version number as #2520?

**Comment by zur003** [comment]
It failed because Jenkins's buddy Scoop was unplugged.

**Comment by zur003** [comment]
retest this please jenkins

**Comment by zur003** [comment]
retest this please jenkins

**Pull request merged**
