### PR TITLE
Minor bugfixes to keep Val happy

### LINKED ISSUE #2901: UI 'improvements' not :-)
@hol430 

A recent change to the UI seems to have broken the colour coding of separator lines in Manager properties and pushed boolean checkboxes too far right (too easy for the user to miss).

image

### PR DESCRIPTION
**Pull request by hol430**
Resolves #2901

### CODE REVIEW

**Comment by hol430** [comment]
Don't merge this yet - looks like there may be more stuff to fix.

**Comment by hol353** [comment]
OK but you do realise @sno036 is never happy.

**Comment by hol430** [comment]
Don't merge this if you enjoy being able to edit cells in a grid.

**Comment by hol430** [comment]
I think it's safe to merge this now.

**Pull request merged**
