### PR TITLE
Grapevine

### PR DESCRIPTION
**Pull request by junqi108**
working on #1292

update the grapevine model:
1. update the canopy depth configuration in the leaf. there is some confusion between the depth function in leaf and the height function in structure
1. update the met files for RPC
2. conducted simulations for the new canopy systems

### CODE REVIEW

**Comment by junqi108** [comment]
@hol353 stats are fine for me ^-^

**Comment by HamishBrownPFR** [comment]
@hol353 @junqi108 has fixed a bug on this PR which has changed the stats.  Over all it has a positive impact with no major reductions in stats on any variables so suggest merging this one

**Comment by hol353** [comment]
Will merge but first can you remove tasks.json please.

**Comment by junqi108** [comment]
> Will merge but first can you remove tasks.json please.

tasks.json has been deleted. although there could a trace in the git history

**Pull request merged**
