### PR TITLE
Added 'CO2xTemperature' simulation and memo

### LINKED ISSUE #4503: Add set of simulations for parameter sensibility in AgPasture
New set of simulations for the example of AgPasture are needed

### PR DESCRIPTION
**Pull request by mpandreucci**
Resolves #4503

@hol353 and @sno036 These are the changes I've done to the example of AgPasture. I added a CO2xTemperature simulation and did a memo for the whole example. Please let me know if there is anything that should be changed or isn't right.

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 Muck is back up now

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@mpandreucci: You need to put working on issue number in the top comment box for this pull request to work.

**Comment by mpandreucci** [comment]
retest this please jenkins

**Pull request merged**
