### PR TITLE
MicroClimate doing residue interception and evaporation

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #1196

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353, @hol430 .   This pull request is throwing in the morris example and I can not work out why.  Any pointer appreciated.

**Comment by hol430** [comment]
@HamishBrownPFR I can't reproduce this locally but I'm hoping that #4151 will fix this.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@HamishBrownPFR looks like the Morris bug is fixed (or in hiding). The current failure in SoilTemp might be a legitimate breakage caused by these changes.

**Comment by HamishBrownPFR** [comment]
Thanks @430, I will look into it

**Comment by hol353** [comment]
@HamishBrownPFR: @sno036  and I were going to do a bit of refactoring of MicroClimate but I noticed this pull request. Can you get it green? Once that is done what other plans do you have for MicroClimate? Should we hold off on refactoring?

**Comment by HamishBrownPFR** [comment]
@hol353 @hol430 there seems to be a problem with muck

**Comment by hol430** [comment]
Yeah I think there was a power outage here over the weekend. Looks like your job is running now.

**Comment by HamishBrownPFR** [comment]
Hi @hol353.  I am pretty sure I have got this all tidy now but keep getting held up by the build.  Would be good to merge this in before you start refactoring Microclimate.

**Comment by hol430** [comment]
I think one of our build agents restarted to install windows updates...should be running again now.

**Comment by HamishBrownPFR** [comment]
@hol353 This CAN be merged.  Diff in performance tests is the result of an accidental bug fix.  Explanation below.  
Diffs are only coming in the lucerne simulations of the LandP experiment in the SoilWater.apsimx validation set.  Diffs were in soil water for the first couple of months of the simulations and I have traced this back to differences in crop transpiration (see figure below with checkpoint on master and the thin line representing the results from this pull request.  This pull request is giving the correct behavior because there CoverGreen is zero during this time and transpiration should be zero also
image
CoverGreen should not be zero during this phase but I will fix this on a seperate pull request.

**Pull request merged**
