### PR TITLE
Lucerne 1721

### PR DESCRIPTION
**Pull request by Xiumei2017**
Working on #1721

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 this is failing on red clover because there are no baseline stats committed for Nconc but it is producing number now.  At least that is what I think is happening.

**Comment by rcichota** [comment]
There was an issue with Nconc, but that was (or at should have been) fixed in the merged commit. The issue was that there were two variables re- Nconc and a few missing values, I deleted one and fixed the other, and so there should be values in there now...

image

**Comment by hol353** [comment]
@HamishBrownPFR I assume you're Ok with the changes to Plant in this PR. I notice a PopulationFactor has been added to the Plant class. What is that?

**Comment by HamishBrownPFR** [comment]
Hi @hol353.  Yep I made those changes but pushed them up through Xuimei's repo so we could test things on her system first.  Population factor has a default of 1 so doesn't do anything in most cases.  For lucerne it reduces LAI and biomass demands when the plant density is low and individual plants can't grown any bigger to fill in gaps in the field.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
