### PR TITLE
Delete old Test script and add Edith's new .apsimX plus observed data…

### PR DESCRIPTION
**Pull request by ed2014**
working on #78 

- Add FodderBeet.apsimx to enable auto doc
- Delete old FodderBeetTest.apsimx
- Add Edith's new observed data

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
Don't put quotes around the working on bit at the top.

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
