### PR TITLE
New command line feature

### PR DESCRIPTION
**Pull request by ric394**
working on #8038 

# New command line feature: --apply

## New switch

models.exe will be able to be executed with a new switch:
 ```--apply```

## What does it do?

This new switch, in conjunction with a 'config' file (a text file with simple commands) allows you to perform a series of actions. 
The actions include:

- add model, 
- remove model, 
- save simulation, 
- and load simulation, 
- and create simulation.

### CODE REVIEW

**Comment by ric394** [comment]
retest this please jenkins

**Comment by ric394** [comment]
retest this please jenkins

**Comment by hol353** [comment]
I have pulled your branch and done some testing. 

1. Can you update the documentation to include the copy command?
2. I can't get the copy comment to work. I want to copy a simulation to be a child of an experiment. This is my instruction file (commands.txt):

```
load wheat.apsimx             
add [Simulations] Experiment  
copy [Simulation] Experiment
delete [Simulation]                 
save wheatnew.apsimx       
```

This is how I run it:
```
C:\Work\Repos\ApsimInitiative\ApsimX\bin\Debug\net6.0\Models.exe --apply commands.txt
```

This is what I get in the GUI (wheatnew.apsimx):
image

Notice the simulation name.

I then changed the copy line to ```copy [Simulation] [Experiment]``` as I wasn't sure about whether brackets were needed and it had no effect i.e. it didn't copy the simulation to a child of experiment.

**Comment by hol353** [comment]
This works well - good job! One final thing - remove launchsettings.json from the PR. It is specific to your computer. Perhaps put it into .gitignore.

**Pull request merged**
