### PR TITLE
Generalise interp

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
Working on #5325

### CODE REVIEW

**Comment by hol430** [comment]
@HamishBrownPFR looks like you've accidentally changed the line endings in a few files. Have you changed computers or any of your git config settings recently?

**Comment by HamishBrownPFR** [comment]
Yes, I changed some git setting to surpress an error I got about line endings every time I committed.

**Comment by hol430** [comment]
This is probably because `core.autocrlf` is set to false, but I have no idea how to change that from git fork. @hol353 I assume that we want lf (not crlf) in all files? If so, I can create a separate pull request and add a .gitattributes file so that this is not dependent on each user's git config settings.

**Comment by HamishBrownPFR** [comment]
I set it in this file

image

**Comment by hol353** [comment]
@hol430 I don't care what the setting is. I do care that the line endings on windows computers are crlf.

**Comment by hol430** [comment]
@HamishBrownPFR I've standardised the line endings of all files to LF. You will need to pull down latest changes and merge conflicts. Then, to fix the files you've added CRLF to, you'll need to open a terminal in the ApsimX directory (there's probably a "console" button in your git client - do you use sourcetree?), and run the following command:

```
git add --renormalize .
```

**Comment by HamishBrownPFR** [comment]
@hol430.  Im a bit confused by this.  I made the change to my gitconfig file a few weeks ago and have had a number of pull requests merged into APSIM master since so not sure why it has come up as an issue now.  Will I need to change all the files I have committed since making the change?  Do I need to change the setting in my gitconfig file to stop it changing them again?

**Comment by hol430** [comment]
I think your gitconfig is correct now, as core.autocrlf is set to true. Previously, this setting determined git's line endings behaviour, but I've changed the .gitattributes file, so this behaviour should be tied to the repository now, rather than to each user's git settings.

I'm not sure exactly how these files ended up with the wrong line endings. The only files whose line endings you'll need to fix is the files you've changed as part of this pull request - and maybe files on your other branches which aren't merged, but I wouldn't worry about them for now. You can fix up these files by running the command I posted above, and then committing any changes.

**Comment by HamishBrownPFR** [comment]
@hol430 I have followed your instructions above but it does not create changes to any files.  I will push to this branch again and see how it looks?

**Comment by HamishBrownPFR** [comment]
Looks OK?  Was merging in your changes along with the change to the gitattributes file enough to fix it?

**Comment by HamishBrownPFR** [comment]
No, sorry, it did make changes put staged them all automatically.  I wasn't looking for them there

**Pull request merged**
