### PR TITLE
8873 Reformat Script Option

### LINKED ISSUE #8873: Manager script "Reformat" does not work
### What happened?

image

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by par456**
Resolves #8873

Disabled this menu option a few weeks ago because it wasn't finished. Working on getting it to do what we want.

Basic formatting it complete, need to work on edge cases now by reformatting a bunch of different scripts.

### CODE REVIEW

**Comment by ric394** [comment]
In the management toolbox, when I reformat 'Fertilise when variable reaches threshold' the formatting is not quite right:
image

**Comment by ric394** [comment]
ClimateController from management toolbox has a similar formatting issue. Seems to be if else blocks without curly braces.

image

**Comment by ric394** [comment]
When reformatting SWIMNH3Volatilisation I got an index out of range error in CodeFormatter.cs line 182. This is also available from Mangement toolbox.

**Review by ric394 — CHANGES_REQUESTED** [review]
Just a few things to address.

**Review by ric394 — APPROVED** [review]

**Review by ric394 — APPROVED** [review]

**Comment by BrianCollinss** [comment]
A few cases that may be able to be improved:

- If default value is provided for an array:
image

- Removes the blank lines between public and private properties:
image

- Removes the blank lines that are there to make the code more readable:
image

- Undesirable format when multiple "." are used in a command:
image

**Pull request merged**
