### PR TITLE
Sorghum review

### LINKED ISSUE #7016: Sorghum issues for release
I didn't have my notes with me and forgot to raise two minor issues at the recent meeting for #572 

The sorghum examples use SoilNitrogen in the soil model.  These, and the validation files, should all use Nutrient.

The output variable names in the observed data should be the standard apsim names otherwise readers of Autodoc will see only the alias names.  It is best that people know what the output really is (e.g. sorghum.leaf.live.wt)

### PR DESCRIPTION
**Pull request by jbrider**
resolves #7016

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
The issue talks about replacing the soilnitrogen model with nutrient. I don't see that change in this PR. Have you got the right issue number?

**Comment by jbrider** [comment]
I have tested the nutrient implementation and it will work fine.
Currently working on updating dynamic tillering in classic and nextgen
first - remaining items should be easier.

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
@hol353 @hol430 This can be merged if it runs ok.  Changes were expected as there were some fixes.

**Review by hol353 — APPROVED** [review]

**Pull request merged**
