### PR TITLE
Grain Water content changes

### PR DESCRIPTION
**Pull request by ilhuber**
Working on #2753

Don't merge this just yet!

### CODE REVIEW

**Comment by hol353** [comment]
OK. Let me know when you do want it merged.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hut104** [comment]
This is now out of date and the file has been converted to JSON.  This can be resubmitted in future if required.

**Pull request closed without merging**
