### PR TITLE
Update the simulation name

### LINKED ISSUE #3174: Duplicate simulation names found in wheat validation
I got an error to run wheat validation dataset (ApsimX\Tests\Validation\Wheat\Wheat.apsimx).  "Duplicate simulation names found Wakanui2015Base". 

This error is only happening in GUI, not command line.

### PR DESCRIPTION
**Pull request by byzheng**
resolves #3174

### CODE REVIEW

**Comment by byzheng** [comment]
retest this jenkins please

**Comment by byzheng** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
