### PR TITLE
Include ApsimNG with debugging launch profile in Visual Studio

### LINKED ISSUE #7692: Windows Subsystem for Linux (WSL) needed to run APSIM in VS 2022
Has anything changed in preferences or APSIMNG lately forcing the system to only want to work with WSL?
My Visual Studio (2022) now only lets me run through WSL and I don't have Ubuntu or Debian installed on my system, so I can't run (release or debug) APSIM from VS
There is very little to no help online around this when you don't want to use WSL and I can find a way to revert back to running the application as a Windows application. 
I have no cross-platform extensions installed in my options/cross platform manager

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7692

### CODE REVIEW

**Comment by zur003** [comment]
Do we really need this? I suspect most of us get along quite fine without having a Properties\launchSettings.json file at all. I think this would be of use only to developers switching between Windows and WSL debugging, and I doubt there are many in that situation.

**Comment by lie112** [comment]
I figured someone needed the WSL and added this to the launchsettings.json. Therefore, anyone else not using WSL needs another launch setting in order to run APSIM in the visual studio development environment. I am not sure where it came from and can't find it in any commit searches. Maybe it was some weird behaviour in my system but didn't show up in my sourcetree commits. Do you have a ApsimNG/properties/launchSettings.json? It took me a day to work out why my system switched to only allowing WSL runs and threw errors regarding no Linux installed.

**Comment by zur003** [comment]
@lie112 - No, I don't have a launchSettings.json file. I'm not entirely sure, but I think it's created by Visual Studio if you launch an application for debugging under WSL or ASP.Net. I haven't looked at WSL at all, so I don't really know the details.

**Comment by lie112** [comment]
Interesting. I'll delete the file and see how we go. I have used Asp.Net but certainly not within APSIM solution and don't know how WSL launch got into ApsimNG.

**Comment by lie112** [comment]
It's not needed and works when removed completely. It must have been committed elsewhere as I can't delete the file without committing the changes. I guess I could just repull the latest changes. I assume no one else needs it.

**Comment by lie112** [comment]
I'm lost in git now. A fresh pull and all the changes are still there. Can I delete the file and make that commit to sort all this out?

**Comment by lie112** [comment]
Shall we just ignore and close this pull request? Not sure if I'll be able to delete the branch.

**Pull request closed without merging**
