### PR TITLE
Accumulate certain variables from and stop between phases

### LINKED ISSUE #2304: Modify accumulate function to cover part of the phase
Currently, start and end-stage specified with a text string, but sometimes we only want to accumulate certain variables within part of the stage.

### PR DESCRIPTION
**Pull request by junqi108**
resolves #2304  working on #1822

### CODE REVIEW

**Comment by hol353** [comment]
This now conflicts because I just merged your last pull request

**Comment by junqi108** [comment]
No, these two are different. One works with date and one works with numeric
phase. Junqi

**Comment by hol353** [comment]
What I meant was that your branch has conflicts. You modified Model.cs and Models.csproj in this pull request and your last one. You'll need to do pull before repushing to this pull request.

**Comment by junqi108** [comment]
OK, sorry I thought they are separated pulls. I will make a pull first and then make a new pull request.

**Pull request closed without merging**
