### PR TITLE
Fixes for grazing, growth and breeding of Ruminants based on expert checking

### PR DESCRIPTION
**Pull request by lie112**
working on #3907 
This merge includes a range of CLEM fixes and improvements identified while implementing the expert identified problems and improvements to the Ruminant grazing and breeding components.
The new features include: updated ResourceTransactions, ResourceUnitsConverter functionalilty, improved HTML summary display details, corrected Help URI links, updated crop reader using SQLite and functionality to use the new Methods with arguments in reporting.

### CODE REVIEW

**Comment by lie112** [comment]
How can I tell what versions of Upgrade are available when I only have the development version (VS) installed? My users have upgraded to #3947 which is a larger number than this #3946 but the CLEM changes are not included in the upgrade. It seems that not all merges provide an upgrade option in the upgrade window. How can I tell them what version to select to ensure the latest CLEM changes are included? I assumed if the #number was larger than the CLEM merge it would be included. thanks for merge after my pushy email.

**Comment by hol430** [comment]
If a pull request says 'working on' it will not generate an upgrade. You need to close an issue via 'resolves #xxxx' to generate an upgrade. Usually doesn't matter too much because any upgrade which is released *after* your pull request gets merged will contain all of the changes in your pull request.

**Comment by lie112** [comment]
Got it. Thanks. I just need to find the next "resolves" after my merge. Thanks. I am still learning lots.

**Comment by lie112** [comment]
Is the best approach to merge another simple change and "resolve" my issue as I don't know when the next "resolves" merge will be submitted? I should be starting to have more specific issues from this point on now that the majority of CLEM initial development is now complete.

**Comment by hol430** [comment]
I imagine that #3950 will be merged this afternoon, and a new version will be released, containing these clem changes.

**Pull request merged**
