### PR TITLE
Eliminate the WIndows.Forms GUI, and use only Gtk#

### LINKED ISSUE #2059: Two different GUIs is one too many
For some time now, we've had both a Window.Forms GUI and a Gtk# GUI. This is a maintenance headache. There no longer seems to be a good reason to continue maintaining the Windows.Forms GUI, so if there are no objections, it will be killed.

### PR DESCRIPTION
**Pull request by zur003**
Resolves #2059

### CODE REVIEW

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
More changes to Jenkins configuration. 
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
Hi @zur003 
I notice that you have modified a bunch of .apsimx files. My pull request also modifies many of the same files. Any reason why you included them in the pull request? Can you remove them?

**Pull request merged**
