### PR TITLE
New POStats collector

### PR DESCRIPTION
**Pull request by hol353**
Working on #5900

### CODE REVIEW

**Comment by hol430** [comment]
What's the idea behind committing a zip file?

**Comment by hol353** [comment]
A temporary measure for now to let me try it. I want to run new collector and old collector in parallel for a while. If I push my commits to the APSIM.Performance repo then Muck will try and compile that and use which isn't what I want yet. To get around that I'll commit a zip file of binaries to allow me to test.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
