### PR TITLE
SequenceTimer added for crop harvest

### LINKED ISSUE #5859: Need ability to provide sequence in activity timer
The CLEM harvest timer needs the ability for the user to provide a repeated sequence of months to use.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #5859

### CODE REVIEW

**Comment by lie112** [comment]
retest please Jenkins

**Comment by lie112** [comment]
Not sure why this pull request has halted

**Comment by hol430** [comment]
It's running the eucalyptus PR at the moment. Should get to this one in a few minutes.

**Comment by lie112** [comment]
Must have been after my restest request, as it had been running for 2 days.

**Pull request merged**
