### PR TITLE
Initial commit of AgPasture

### PR DESCRIPTION
**Pull request by mpandreucci**
Working on #3689

### CODE REVIEW

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
Woo Hoo your first pull request. Well done.

**Comment by mpandreucci** [comment]
@hol353 haha still feel like a kid putting a knife into a power plug though

**Comment by hol353** [comment]
@hol430 Does this error on Jenkins look familiar?

**Comment by hol430** [comment]
Ah, it's our old friend, #3678

**Comment by sno036** [comment]
@hol353 - please don't merge this for now

**Comment by mpandreucci** [comment]
Retest this please Jenkins

**Pull request merged**
