### PR TITLE
New Apsim NG testing implemention

### PR DESCRIPTION
**Pull request by fai04d**
Replace old R test suite with an in built test suite that runs at the end of simulations. First implementation. Working on #215

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
I will have a look

**Comment by HamishBrownPFR** [comment]
What exactly do you mean by verify

**Comment by hol353** [comment]
add to whitelist

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
add to whitelist

**Comment by fai04d** [comment]
Working on #215. Temporarily disabled unit tests as they are not complete.

**Comment by fai04d** [comment]
Working on #215. Removed old test node from wheat validation.

**Comment by fai04d** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
