### PR TITLE
Implements improved crop component measures

### LINKED ISSUE #7602: Problem with external resource manager
The recent upgrade caused the resource manager to throw an error when filtering resources to consider

### PR DESCRIPTION
**Pull request by lie112**
resolves #7602

### CODE REVIEW

**Comment by lie112** [comment]
I am unable to get this pull request to work as there is an issue with HarfBuzzSharp libraries.
some other process has /tmp/ApsimX/bin/Release/netcoreapp3.1/runtimes/tvos/native/libHarfBuzzSharp.framework/libHarfBuzzSharp open

**Comment by zur003** [comment]
@lie112  - libHarfBuzzSharp is not the problem; that's just a warning. If you look at the full log, you'll see errors are occurring with Examples/CLEM/CLEM_Example_Cropping.apsimx. These are:

1.  ---> System.NotImplementedException: Unknown or invalid units [per ha] specified by companion component [LabourRequirement]  in [CropActivityManageProduct]: [a=Manage Maize.Grow maize crop]
2.  ---> System.NotImplementedException: Unknown or invalid units [per ha harvested] specified by companion component [ActivityFee]  in [CropActivityManageProduct]: [a=Manage rotation.Manage Wheat]

Stack dumps are available in the log.

**Comment by lie112** [comment]
Thanks Eric.... I'll address them now. I looked through the huge list of jobs and didn't see those two.

**Comment by lie112** [comment]
I cannot work out which tests have failed as it seems to be an issue with the format of two apsimx files in temp validation directories.

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by lie112** [comment]
Thanks, never know when a retest request is the answer.

**Comment by zur003** [comment]
@lie112 - I only knew because I'd seen that one before. It's in the Unit Tests, at a point where it's testing some magic with sockets; beyond that, I don't really understand why it occasionally fails.

**Pull request merged**
