### PR TITLE
Speed up empty datastore and put information message in status window

### LINKED ISSUE #6551: Empty Datastore is slow for the Wheat Validation Set
If the wheat validation is run to create a populated datastore, then do an empty datastore, it can take 2:04 minutes to complete the emptying.

Somewhat related to this, no message is written to the status area at the bottom of the screen to tell you when the emptying is complete.

### PR DESCRIPTION
**Pull request by hol353**
Resolves #6551

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 - this has stalled on Jenkins, so I've aborted the build.

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
