### PR TITLE
Fodder beet model#78

### PR DESCRIPTION
**Pull request by RobZys**
Working on #78

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol353** [comment]
add to whitelist

**Comment by HamishBrownPFR** [comment]
retest this please Jenkins

**Comment by fai04d** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
Thanks Justin.

I don’t think Dean is in today so it will have to wait until Monday.

Hamish

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
The issue number at the top is wrong. It isn't 619.

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
We need non cryptic error messages or morons like me are never going to get this

**Comment by hol353** [comment]
Looks like it can't find the issue number after your 'working on' statement above. I'll have to fix this mess up on Monday.

**Pull request merged**
