### PR TITLE
Provide generic pasture data reader for CLEM

### LINKED ISSUE #5283: Create generic pasture data reader
The legacy link to GRASP input data should be avoided.

### PR DESCRIPTION
**Pull request by lie112**
This generic data reader better reflects the range of simulation models that can be used for pasture production input into CLEM

resolves #5283

### CODE REVIEW

**Comment by lie112** [comment]
retest this please jenkins

**Comment by lie112** [comment]
Having issues getting this pull request to work.

**Comment by hol430** [comment]
Looks like there was an apsim classic job in the build queue and it stalled for some reason. I've aborted it, so this one is running now.

**Comment by hol430** [comment]
Ok, this one has failed now too, because you don't have a working on or resolves in the initial comment. You'll need to edit it and then rerun the  tests.

**Comment by lie112** [comment]
Oops. It's been too long between pull requests!

**Comment by lie112** [comment]
retest this please jenkins

**Comment by lie112** [comment]
resolves #5283

**Pull request merged**
