### PR TITLE
Oat model validation

### PR DESCRIPTION
**Pull request by ekhaembah**
Working on #8503 
Re-submitting a pull request after adding new data and cultivars

### CODE REVIEW

**Comment by ekhaembah** [comment]
re-test Jenkins please

**Comment by ekhaembah** [comment]
@hol353 - see responses below <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CFLEZK/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CFLEZK/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


DailyPO | Parameter | Response
-- | -- | --
1 | Oats. AboveGround.N | Added more data, hence the difference in number of entries
2 | Oats. AboveGround.NConc | New plot from new available data; Very good performance rating from the   statistics.
3 | Oats. AboveGround.Wt | Additon of data marginally reduced prediction accuracy, but the stats   indicate very good performance
4 | Oats.Ear.Wt | More data, some reduced accuracy, but high performance rating overall
5 | Oats.Grain.Number | Reduced fit, but not significant change.
6 | Oats.Grain.Wt | Same as before - no changes
7 | Oats.Leaf.CoverTotal | Added more data, improved fit
8 | Oats.Dead.Wt | Added more data, slightly improved fit
9 | Oats.Leaf.DeadCohortNo | Improved rating
10 | Oats.Leaf.ExpandedCohortNo | More data; some reduced accuracy, but high performance rating overall
11 | Oats.Leaf.GreenCohortNo | More data; rating slightly reduced
12 | Oats.Leaf.Height | Added more data, slightly improved fit
13 | Oats.Leaf.LAI | Added more data, improved fit
14 | Oats.Leaf.Live.N | Added more data, improved fit
15 | Oats.Leaf.Live.Nconc | Added more data; Slight changes but high accuracy as per the stats
16 | Oats.Leaf.Live.Wt | Added more data; rating slightly reduced, but good rating overall
17 | Oats.Leaf.SenescingCohortNo | Added more data; rating reduced; poor fit even before
18 | Oats.Leaf.SpecificArea | Slight improvement but poor rating overall
19 | Oats.Leaf.Wt | Added more data, improved fit
20 | Oats.Phenology.Stage | These values were taken on one date only, so have been removed
21 | Oats.Phenology.Zadok.Stage | Added data; Stats indicate good model performance
22 | Oats.Stem.Live.Nconc | Added data; Stats indicate good model performance
23 | Oats.Stem.N | Added data; Stats indicate good model performance
24 | Oats.Stem.Wt | Added more data, improved fit
25 | Oats.Structure.LeafTipsAppeared | Added more data, high prerformance rating indicated
26 | Oats.Structure.TotalStemPopn | Added more data, improved fit
27 | ProfileWater | Added more data, small reduction but very good overall
28 | Soil.Water.Volumetric(1) | Addition of more data reduced accuracy, but not by much
29 | Soil.Water.Volumetric(2) | Addition of more data reduced accuracy, but not by much
30 | Soil.Water.Volumetric(3) | Added more data; good fit indicated
31 | Soil.Water.Volumetric(4) | Addition of more data reduced accuracy, but not by much
32 | Soil.Water.Volumetric(5) | Added more data; good fit indicated
33 | Soil.Water.Volumetric(6) | Added more data
34 | Soil.Water.Volumetric(7) | Addition of more data reduced accuracy, but not by much
35 | Soil.Water.Volumetric(8) | Improved fit
  |   |  
DailyPOSAE | SoilN_0_120 | Data from a new added experiment; Good fit indicated
  | SoilN_0_15 | Data from a new added experiment; Good fit indicated considering   variability in soil N measurements
  | SoilN_0_30 | Data from a new added experiment; Good fit overall
  | SoilN_0_60 | Data from a new added experiment; Good fit overall
  | SoilN_0_90 | Data from a new added experiment; Not bad overall
  | SoilN_15_30 | Data from a new added experiment; Not bad overall
  | SoilN_30_60 | Data from a new added experiment;    High variability in data
  | SoilN_60_90 | Data from a new added experiment; Not bad overall
  | SoilN_90_120 | Data from a new added experiment; limited data set (n=8) that was highly   variable
  | VWC_0_30 | Changed to Soil.Water.Volumetric(1) & included in item   (26)
  | VWC_30_60 | Changed to Soil.Water.Volumetric(2) & included in item   (27)
  | VWC_60_90 | Changed to Soil.Water.Volumetric(3) & included in item   (28)
  |   |  
DailyPOSup✘ new | Leaf.CohortSizes (1-9) | These were in the previous release - we haven't done anything on them
  | ProfileWater | Standardised across simulations & moved to DailyPO
EnviroPO |   |  
  | cumDrainage70cm | Information is from lysimeter experiments which have limitations; open to   improvement as more data become available
  | cumLeaching70cm | Data from a new added experiment; Good fit indicated
  |   |  
HarvestPO |   |  
  | Oats.Grain.Wt | Removed as already included in DailyPO
  | Oats.Phenology.FlagLeafDAS | Small movements but very good rating, overall
  | Oats.Phenology.FloweringDAS | Small movements but very good rating, overall



</body>

</html>

**Comment by hol353** [comment]
Since you're looking at the oat model, it would be nice to clean up some of the zero predicted / observed values from the validation graphs (unless they are valid of course)

image
image

**Comment by ekhaembah** [comment]
It looks like Apsim isn't getting the timing right, making it difficult to identify genuine zeros. Example below. I'll log an issue shortly & address your comment after the issue is resolved.
image

**Comment by rcichota** [comment]
Hi @hol353 
What Edith means is that APSIM seem to be rendering the observed data wrongly. We cannot see why that is...
For the graph above, plotted using excel, the observed data should look like this:
image

I agree those zeros need cleaning up, but they are not the big issue here. Was there any changes to the graphing system in APSIM recently?

**Comment by hol353** [comment]
There have been changes. We'll investigate.

**Pull request closed without merging**
