### PR TITLE
Adds 3rd APSIM Next Gen Tutorial - The Nitrogen Cycle

### PR DESCRIPTION
**Pull request by ric394**
Working on #7821

### CODE REVIEW

**Comment by ric394** [comment]
please retest this jenkins

**Comment by ric394** [comment]
retest this please jenkins

**Comment by i-heis** [comment]
Hey, not sure if this is the right place, but I am having an issue with the Nitrogen Cycle Tutorial for ApsimX. After double checking everything if it is in line with the tutorial, I still cannot create the graphs on TotalNO3 and TotalNH4 because "Graph: No data matches the properties and filters set for this graph". Even though I used the Report variables from the Tutorial, NO3 isn't reported as TotalNO3 and NH4 does not appear in the drop down menu for the Graph. I used the Wheat.apsimx file from the Examples folder.
grafik
Thanks, Irina

**Comment by ric394** [comment]
@i-heis I'll have a look at this for you.

**Comment by ric394** [comment]
@i-heis I've reviewed the tutorial and found the issue you've run into.

1. In `Report`, The report event needs to be set to `[Clock].EndOfDay` rather than `[Wheat].Harvesting` to get the daily outputs for all the report variables.
2. Reset the `DataStore` using right-click > empty the data store and rerun the simulation after setting the x and y axes and all should work as intended.

Thank you for pointing out this issue and helping improve the tutorials.

**Comment by i-heis** [comment]
great, thanks for your fast reply, I got it to run correctly! I have noticed some other small things that may be helpful to mention in the tutorials 3-5 (maybe):
[ApsimXTutorial3to5comments.txt](https://github.com/APSIMInitiative/ApsimX/files/15415906/ApsimXTutorial3to5comments.txt)
Thank you very much for these tutorials, it was a fun way to start getting to know APSIMx.

**Pull request merged**
