### PR TITLE
adding an empty job object to force jobs finished event to fire

### LINKED ISSUE #4007: Refresh data store does not work
Right clicking on a data store and selecting 'refresh' does not work - a message is displayed in the status panel saying 'Post processing models have successfully completed' but this appears to be a lie because the post simulation tools do not get run.

### PR DESCRIPTION
**Pull request by jbrider**
resolves #4007

### CODE REVIEW

**Comment by jbrider** [comment]
It's failing on a test: EnsureOnlyPostSimulationToolsAreRun which is testing for the wrong thing.
It's testing if no simulations are run, but not testing if postprocessing happens.

**Comment by jbrider** [comment]
Having issues running tests. Getting an error opening the sqlite db - BadImageFormatException - which according to a previous issue (#1159) is something to do with 32bit + 64bit.
Other tests failing as well - is there anything you have to configure to get tests to run successfully?

**Comment by hol430** [comment]
Yeah the setting you need is hidden away under the Tests ribbon in visual studio:

Tests -> Test Settings -> Default Processor Architecture -> X64

image

**Comment by jbrider** [comment]
Mine didn't quite look like that - but found the same setting in the
testexplorer dialog.

**Comment by jbrider** [comment]
While looking at the contents of a table in the datastore - how do you update the table display when you right click->Refresh on the datastore?  
explorerPresenter.Refresh(); didn't appear to do anything.

**Comment by hol430** [comment]
Hmm...maybe something like this?

```csharp
(explorerPresenter.CurrentPresenter as DataStorePresenter).PopulateGrid();
```

**Comment by jbrider** [comment]
That worked. 👍 
Should I create a separate issue for that, ,or just push it through with this one?

**Comment by hol430** [comment]
I'd say just push it through with this one, it's a small enough change.

**Comment by jbrider** [comment]
How do you work out why a test failed? It's running green on my machine.

**Pull request merged**
