### PR TITLE
Pinus prototype created

### PR DESCRIPTION
**Pull request by sme016**
Working on #5147

Created a Pinus Prototype, which is initially a copy of a very cut-down version of the Eucalyptus validation

### CODE REVIEW

**Comment by hol430** [comment]
Hi Phil - you will need to edit your initial comment and add "Working on #5147" (without the quotes).

**Comment by sme016** [comment]
Thanks for the reminder, but it will be a little later – I have to head out for now

P

**Comment by hol430** [comment]
retest this please jenkins

**Comment by sme016** [comment]
Working on #5147 

Corrected link to met file in Pinus.apsimx

**Comment by sme016** [comment]
Working on #5147

Corrected link to met file in Pinus.apsimx

**Comment by sme016** [comment]
Retest this please Jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
