### PR TITLE
Chickpea

### PR DESCRIPTION
**Pull request by hut104**
working on #158

### CODE REVIEW

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hut104** [comment]
This commit fixes errors found within the model.  The fixes significantly improve important stats such as yield and biomass at maturity

PredictedObserved |   | n |   | RMSE |   | NSE |   | RSR
-- | -- | -- | -- | -- | -- | -- | -- | --
  |   | Chickpea.AboveGround.Wt |   | 120 | (120) |   |   | 94.2352 | (118.353) | ✔ |   | 0.749 | (0.604) | ✔** |   | 0.499 | (0.627) | ✔***
  |   | Chickpea.Grain.Size |   | 2 | (2) |   |   | 0.30135 | (0.31705) | ✔ |   | -14528.491 | (-16082.023) | ✔ |   | 85.233 | (89.674) | ✔
  |   | GrainWt |   | 138 | (138) |   |   | 43.5098 | (59.3175) | ✔ |   | 0.660 | (0.367) | ✔** |   | 0.581 | (0.793) | ✔**

There are minor changes to other stats which decrease model accuracy with marginal effect.

The defects need to be fixed, so I recommend merging this.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@hol430 Why has this failed? I reran it an hour ago.

**Comment by hol430** [comment]
I believe this may be due to my performance tests repo having a branch called refactor and the apsim initiative repo also having a branch of that name. When we go to checkout the refactor branch, git is unable to resolve the name 'Refactor'. My refactor branch has already been merged so I've deleted it. Hopefully that fixes the issue (can you retest this please jenkins) - although it doesn't explain why it suddenly became an issue now, when the branch name conflict has existed for about 3 weeks.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
