### PR TITLE
Wheat

### LINKED ISSUE #1966: Make wheat more sensitive to drought
A number of simulations are not showing sufficient sensitivity to drought treatments

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #1966

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353  I am wanting to check the impact of these changes using the new test system but it fails on the old tests so won't progress to the new tests.  Is there any way of getting this to run on the new test system?

**Comment by hol353** [comment]
Not at the moment. It isn't possible. Loretta needs to do some more work (Monday) before we can rely on her performance testing website.

**Comment by HamishBrownPFR** [comment]
No worries, I am not in a rush to get this merged in (if it is mergable at all) but keen to use it as a way the assess the testing system.

**Comment by hol353** [comment]
I think we're close to being able to use Loretta's performance test site. Rerun this pull request?

**Comment by HamishBrownPFR** [comment]
OK, I will update the branch and push again today

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
The changes in this pull request address problems in an specific set of experiments in the test set.  Overall the statistics are improved or have small reductions.  However, reviewing stats at the regional scale, there are some major differences caused so we can't take these changes into general release.  I will close this pull request and rethink how to resolve these issues.

**Pull request closed without merging**
