### PR TITLE
Modifications to oat model phenology and adding validations

### PR DESCRIPTION
**Pull request by ekhaembah**
Working on #8503 

Measured data has been used to modify the oat phenology model. Additional simulations have been added to the validation set.

### CODE REVIEW

**Comment by ekhaembah** [comment]
@hol353, @hut104, @HamishBrownPFR 

I have encountered this error related to Australian simulations that I cannot find a solution to. It appears it relates to the filter in the Roma 2006 validation graphs. Could you assist please?

image

**Comment by HamishBrownPFR** [comment]
@ekhaembah.  I will pop in to your office today and see if we can work this one out

**Comment by rcichota** [comment]
retest this please jenkins

**Comment by ekhaembah** [comment]
Closing this pull request to generate a new one.

**Pull request closed without merging**
