### PR TITLE
Moved APSIM.Shared into ApsimX

### PR DESCRIPTION
**Pull request by hol430**
Working on #3532

### CODE REVIEW

**Comment by hol430** [comment]
@zur003 @her123 @sno036 @rcichota @jbrider @BenAbabaei @byzheng @ver078 @lie112 @MikeStower 

FYI - we've moved APSIM.Shared into ApsimX. This means you no longer need to maintain a separate APSIM.Shared repository. You can safely delete APSIM.Shared from your PC if you don't work on one of our other repos.

**Comment by zur003** [comment]
If we make changes to files on the APSIM.Shared subfolders, and have them committed, will those modifications automatically be merged into the APSIM.Shared repository? Should we do this manually? Or are the two versions of APSIM.Shared effectively going to be forked, and not necessarily be kept in common?

**Comment by hol430** [comment]
The last one - the two repositories probably won't be synchronised and will diverge over time. I think the plan is to gradually phase out APSIM.Shared but keep it around for legacy purposes. The other codebases which reference it - performance tests, websites, etc - really only use a few utility methods and that's it (I think!). 

I don't know that there will be many changes which need to propagate to all of our other codebases.

**Comment by hol353** [comment]
To stop the divergence over time, I'd probably lean towards closing the APSIM.Shared repo. This will force the issue for the other tools.

**Comment by hol430** [comment]
If we want to check out an older version of ApsimX, we would still need to clone APSIM.Shared - deleting it would make this impossible. Although I agree that having two different APSIM.Shareds out there is not ideal.

**Pull request merged**
