### PR TITLE
Added the ability to copy the path to a node.

### LINKED ISSUE #2087: Copy the full path to any nodes in a model
For the report and documentation purpose, I always write names of a node in the model, e.g. `'Wheat.Leaf.CohortParameters.LeafSizeShapeParameter` through copying and pasting all parent names of LeafSizeShapeParameter. 

It will be very useful to add a new item in the context menu (right click) to each node to generate the full path of this node and copy to system pasteboard.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #2087 

Accessible via the right-click context menu or ctrl + shift + c.

I also included a small update to the github readme file, as I didn't feel that this change was worth its own pull request.

### CODE REVIEW

**Comment by hol430** [comment]
@hol353 Any idea why the version string is empty?

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by zur003** [comment]
retest this please jenkins

**Pull request merged**
