### PR TITLE
Generalise temp interp

### LINKED ISSUE #5121: Tomorrows met data
@hol353 @hol430 @hut104 @junqi108 we are working on the grapevine model and bud burst is quite sensitive to short periods of chilling and are needing a more detailed daily air temperature interpolation.  The problem is the approach we want to use needs to know tomorrows minimum temperature.  APSIM currently has no notion of tomorrows weather.

I can program another a MinTtomorrow variable into IWeather and have it go get this from the met file.  However, this feels quite messy and I am wondering if anyone can think of a better way.

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #5121

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 @hol430 there is something going wrong with the build system.  I opened this pull request 1 min ago and it is already telling me it has failed the performance tests

**Comment by HamishBrownPFR** [comment]
@hol353 I don't know why this has failed the performance tests, there are no differences that I can see

**Comment by hol430** [comment]
@hol353 when was the last time you accepted changes in stats?

**Comment by hol353** [comment]
Well no change in stats but there are changes if you drill down on the 3rd sheet from the front page:
image
The performance site should probably look only at stats. It must be looking at the 'passed tests' as well.

**Comment by hol353** [comment]
I last accepted stats about 5 hours ago.

**Comment by HamishBrownPFR** [comment]
So do you merge this and accept stats or do I need to do something else?  I am not sure how to resolve those changes.

**Comment by hol353** [comment]
@hol430 What is the performance site doing?

**Comment by hol430** [comment]
Looks like a bug/inconsistency between the performance tests service (aka backend) and portal (aka frontend). The only tests which have failed are SEslope, SEintercept, and r2 for some of the wheat.leaf.cohortMaxSize values, but the portal's tabulated results page (and graphical results too) only show the rmse, nse, rsr, and n columns. So it is failing, but the portal isn't showing the failures.

I thought that only the rmse, nse, rsr and n are supposed to be taken into consideration when the pass/fail status is calculated, so this may be a bug more than an inconsistency.

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
