### PR TITLE
Add new simulations of wheat during wheat development workshop

### PR DESCRIPTION
**Pull request by byzheng**
working on #632

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
add to whitelist

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol353** [comment]
add to whitelist

**Comment by HamishBrownPFR** [comment]
retest this please Jenkins

**Comment by HamishBrownPFR** [comment]
Some of the simulations failed because they couldn't find gatton-15-g3.met.  See
http://apsrunet.apsim.info/JenkinsCI/job/3.%20Run%20Prototypes/64/console

I suspect it is the dashes in the file name causing strife.  Is is possible to change the file name to remove the dashes.  Push the changes to your repo and another test will be started automatically

**Pull request merged**
