### PR TITLE
Changes to excel multi input component

### LINKED ISSUE #4713: ExcelMultiInput not merging files
I have two excel files with observed data (worksheets named 'Observed') that I am trying to read in using the ExcelMultiInput object.  It will read in the data from the first file into and Observed table.  It sort of reads the 2nd file but does not merge in the simulation name so the data is not visiable in the UI and can't be matched with predicted values.

Interestingly, if I read one of the files in with the ExcelInput object, then change the file name on the ExcelInput object to the other file it will read it in and merge it properly with the data already in the Observed table.  That works but is painful.  

I can provide the two files I am working with to test this, just fire me an email

### PR DESCRIPTION
**Pull request by hol430**
Resolves #4713

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353.  This bug fix causes the soybean tests to fail because the multi-input excel object had been duplicating data and now it isn't so the stats are now correct.

when you merge this can you please to a retest on #4726 which needs this bug fix to run its tests correctly.  Many thanks

**Comment by hol430** [comment]
Actually, can you hold off on merging this. I want to double check that this is doing what I think it's doing. All of those diffs in the stats are a bit alarming.

**Comment by HamishBrownPFR** [comment]
@hol430.  Sorry to winge again.  I need this bug to be resolved before I can complete #4726.  Is there anything I can do to help progress this one?

**Comment by hol430** [comment]
Ok, I just had a quick look and everything appears to be working so @hol353 I guess this is ok to merge.

**Comment by HamishBrownPFR** [comment]
Thanks @hol430 .  I think we can close this issue now

**Pull request merged**
