### PR TITLE
Typos in contributing.

### LINKED ISSUE #1965: Typos in the contributing docs.
In `CONTRIBUTING.md` there are a few typos; loged, triger, introdued, relavent. Please correct the spelling of these words.

### PR DESCRIPTION
**Pull request by philderbeast**
Creating this pull request without a pre-existing issue to test if it will trigger a build. This fix resolves #1965.

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
Hi Phil, how are you!!
Hope things are going well in Canada
For a build to be triggered you have to have you name on the Whitelist, @hol353  is the only one who can do this and you do have to have an open issue.

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by philderbeast** [comment]
The build failure is `'The version specified '2017.08.31.-1' is invalid'`.

**Comment by zur003** [comment]
You will have that problem if there is no associated issue number.

**Comment by hol353** [comment]
The file that you're trying to edit has instructions on the wording you need to have in the top comment box.

**Comment by philderbeast** [comment]
This fix resolves #1965.

**Comment by philderbeast** [comment]
I've edited the initial comment to reference an issue.

**Comment by philderbeast** [comment]
retest this please jenkins.

**Pull request merged**
