### PR TITLE
Feature/white clover model#2069

### PR DESCRIPTION
**Pull request by rcichota**
Working on #2069
Lots of work on sorting out DM partitioning and documentation

### CODE REVIEW

**Comment by rcichota** [comment]
@hol353 I cannot see what has fail in this request, when i look at the details it says 100% passed. I had refreshed the data, deleted some rubish left over from Plantain and added a few more data, would be this the cause?

**Comment by hol353** [comment]
Yes, there was a problem with the performance testing site introduced yesterday. I'm told it is fixed now so hopefully the current pull requests running on Jenkins work OK. If they do, you can try retesting this pull request.

**Comment by rcichota** [comment]
Retest this please Jenkins

**Comment by rcichota** [comment]
Retest this please Jenkins

**Pull request merged**
