### PR TITLE
Fodderbeet review fixes

### PR DESCRIPTION
**Pull request by RobZys**
Working on #78

### CODE REVIEW

**Comment by RobZys** [comment]
I have made a change to fodderbeet but for some reason my git is not registering it, my fault for not noticing the lack of file change

**Comment by RobZys** [comment]
@hol353  dean can you accept the stat difference for fodderbeet please

**Comment by hol353** [comment]
The working on issue number in the top box references another pull request. Can you change it to reference the correct issue instead?

**Comment by RobZys** [comment]
Working on #78

**Pull request merged**
