### PR TITLE
Bubble charts

### PR DESCRIPTION
**Pull request by peter-devoil**
Working on https://github.com/APSIMInitiative/ApsimX/issues/3890 

Recovering from a failed merge of Rotations branch.

### CODE REVIEW

**Comment by peter-devoil** [comment]
I'd like to go over this with dean/drew sometime please. It's workable, but needs attention, and I'd like a heads up before it goes to review. From the code:

// implement node colours & descriptions, separate node name from id
// dynamic / auto layout of new nodes & arcs
// implement command history
// nodes & arcs referenced by ID, not names
// intellisense to display simulation events that we can publish / subscribe to (currently only have C# .net events)
// strip blank lines , newlines from rules / actions. Syntax checking?
// "fixme" where noted in code

**Comment by peter-devoil** [comment]
Hey @hol430, @her123 and  @zur003 - is there a nonclamenture for driving / driven properties that should be used instead of publish/subscribe? I made some changes in the last commit that dont seem to fit .

**Comment by hol430** [comment]
Not sure if we have a convention which applies here. I don't recall seeing driving/driven terminology in the next gen source code but subscriber/publisher seems to be used fairly widely.

**Comment by hol430** [comment]
@peter-devoil you'll need to edit the initial comment box and add "working on #xxxx" or "resolves #xxxx" to get this to run properly on Jenkins. Which items on the todo list do you need me to action in order to get this through?

**Comment by peter-devoil** [comment]
Nothing just yet, drew. But https://github.com/APSIMInitiative/ApsimX/issues/4463 is a bit of a problem for making sure it works...

**Comment by hol353** [comment]
Yep so get your branch up to date and create a new pull request and we'll try and get it through.

**Pull request closed without merging**
