### PR TITLE
Remove one of the PlantEnding methods in Root

### PR DESCRIPTION
**Pull request by rcichota**
Working on #3425

### CODE REVIEW

**Comment by rcichota** [comment]
This Resolves #3425 
I have tidied up and standardized few methods that handle the two variables I was interested in tracking (Removed and Detached biomass). They were reporting some wrong values or not being zeroed correctly upon CropEnd. The changes fix the reporting (though I had to add extra variables to plant)
I traced the wrong values to a lack of updating to the Live and Dead variables (these are the sum of all live and dead biomass, over leaf cohorts or soil layers). This problem only happens for Root and Leaf and when harvesting and ending the crop in the same day. The plant was returning some biomass at RemoveBiomass and then again at PlantEnding without updating itself, thus returning more biomass and N than it actually had...
Only three simulations show considerable diffs. I believe they can be accepted, though it would be good if someone can check them out.
The one from the Rainshelter here in Lincoln I am a bit familiar with, it showed only minor deviations, and a few are improvements;
The changes to the SCRUM simulation are also small, though for a couple of points they are large...
The Tarlee simulation showed somewhat greater diffs but only for the top layer (which is where it was expected as the residue return now changed)

**Comment by rcichota** [comment]
@hol353 , this can be merged now I believe.
The Root organ had two PlantEnding methods, which I merged into one. I've just noticed the command to return biomass in the one I deleted was the correct one, the other returned all biomass to Surface OM. Last commit fixes it... This also removes the diffs in the validation simulations

**Comment by hol353** [comment]
Looks Ok to me but should 'working on' be 'resolves'?

**Comment by lie112** [comment]
There are still a few fixes I am working on, then it will be resolved and I can move on. Should I keep creating Issues as I go through and keep checking and fixing CLEM or can they all go through the one “getting it working” issue?

**Pull request merged**
