### PR TITLE
Reduce the stem population in each leaf cohort 

### PR DESCRIPTION
**Pull request by byzheng**
Working on  #2160 

As I suggested on  #2160, the stem population in each leaf cohort is reduced during plant mortality and branching mortality. 

* Plant mortality: reduce cohort population in all cohorts as the fraction of plant mortality.
* Branch mortality: reduce cohort population only for cohorts which leaf/stem number is not less than the leaf/stem number at the top leaf cohorts (i.e. kill the smaller tillers firstly).

### CODE REVIEW

**Comment by hol353** [comment]
@HamishBrownPFR This looks OK to me. Can you have a quick look?
@byzheng Does this resolve the issue?

**Comment by byzheng** [comment]
@hol353  I just partially fixed this bug and still need to think about how to reduce cohort population in branch mortality.

**Comment by hol353** [comment]
Do you want me to merge or wait for the rest of your fix?

**Comment by byzheng** [comment]
Please wait for my further fixing.

**Comment by byzheng** [comment]
The feature is already implemented, but disabled in ApexTiller. My problem is related with another bug. I will submit a new pull request to address it.

**Pull request closed without merging**
