### PR TITLE
Testing the apex model for wheat

### PR DESCRIPTION
**Pull request by byzheng**
working on #1908

### CODE REVIEW

**Comment by byzheng** [comment]
Retest it

**Comment by byzheng** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
You need to spell 'working' correctly in the top comment box. Edit the top box and then issue another retest message.

**Comment by byzheng** [comment]
retest this please Jenkins

**Comment by byzheng** [comment]
retest this please Jenkins

**Comment by byzheng** [comment]
Still have the same problem. I may be close this issue and submit a new pull request.

**Comment by hol353** [comment]
You need to say 'working on' in the top box. 
Instructions: https://github.com/APSIMInitiative/ApsimX/blob/master/CONTRIBUTING.md

**Comment by byzheng** [comment]
retest this please Jenkins

**Pull request closed without merging**
