### PR TITLE
Implement new filtering and sorting of individuals

### LINKED ISSUE #6692: Refactor and implement new list filtering and sorting by properties and attributes
After the initial release and user requested improvements made to CLEM it needs a code clean up and some improvements with respect to memory and performance.  This includes better management of individuals (ruminant and labour) throughout in preparation for the new implementation of generic filtering and sorting of lists for activities that allows the user to filter and sort on any property or attributes tags assigned to individuals.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #6692
Implements new generic filtering and sorting with both reflection and a simpler faster approach for large herd sizes
Completes the code clean up of CLEM
Fixes bugs and improves model from testing across a range of simulations.

### CODE REVIEW

**Comment by lie112** [comment]
Well that didn't work. I think I may have pushed my branch to Mike's repo as a new branch accidentally.
So I do need to get my latest commits moved to his other CLEM-refactor branch that is in sync with Jenkins.

**Comment by lie112** [comment]
Here's my problem
The master pull to try and fix jenkins' complaints seems to have broken off where it was
I'd love for origin/CLEM-refactor to be up the top with my ListFilter
I was unable to pull origin/ListFilter for the error reasons above.

image

**Comment by hol430** [comment]
I think the following steps should get you to where you want:

1. Make sure you don't have any uncommitted changes
2. Checkout the origin/CLEM-refactor branch (I think in fork you can right click -> checkout)
3. Pull from origin/ListFilter (this will pull into the newly-created local CLEM-refactor branch)
4. Push to origin/CLEM-refactor

**Comment by lie112** [comment]
Yep, that was it. Thanks.

**Pull request closed without merging**
