### PR TITLE
Multi pore water model

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #1057 

This pull request makes a bit of mess in soil.cs to break dependencies on parameters that are not needed for WEIRDO.  This all needs tidying up.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this pleas jenkins

**Comment by HamishBrownPFR** [comment]
@hol353 Hi Dean.  Can you review this one when you get a chance

**Comment by hol353** [comment]
We need to have a serious talk about your naming conventions:

public MultiPoreWater WEIRDO;

Really????

**Comment by HamishBrownPFR** [comment]
Water Evaporation Infiltration Redistribution Drainage runOff.  That is what the model is called.

**Pull request merged**
