### PR TITLE
Fix cultivar documentation when the cultivar makes no model changes.

### LINKED ISSUE #3124: OilPalm autodocs broken.
OilPalm autodocs do not work due to an argument null exception which occurs while generating cultivar documentation.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #3124

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
