### PR TITLE
RedClover - reply to review

### PR DESCRIPTION
**Pull request by rcichota**
Working on #2694 
Few changes to the model documentation in reply to review

### CODE REVIEW

**Comment by rcichota** [comment]
Retest this please Jenkis

**Comment by hol430** [comment]
retest this please jenkins

**Comment by rcichota** [comment]
@hol353 this is finally ready for merging
We'll proceed to release once RP give us the green light

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel have given you the green light.  @rcichota please proceed with merging.

**Pull request merged**
