### PR TITLE
Small changes to assist with compilation under .Net 6 - handling of W…

### PR DESCRIPTION
**Pull request by zur003**
…indows-specific code and never-true condition.

Working on #7139

### CODE REVIEW

**Comment by lie112** [comment]
Hi @zur003 
Can you explain why we need to use the try catch rather than a simple if else statement to trap the clock.StartDate and EndDate being null outside a running simulation? Is it because clock can be null, or because there's other issues with .ToShortDateString. Would clock?.StartDate have solved the issue. I've always avoided try catch for this operation and why doesn't this relate to other locations in the code?

**Comment by hol430** [comment]
Clock.StartDate will never be null, because it's not a nullable type. Therefore `clock.StartDate == null` will never evaluate to true.

**Comment by zur003** [comment]
Also note that the Clock StateDate and EndDate properties raise an Exception if any nullable values they attempt to reference are in fact null. Your "if-else" logic would never have worked, as the cases you were trying to catch would have raised exceptions that weren't being handled.

**Comment by lie112** [comment]
This code is run at design time not during the simulation, thus the search in the tree for the first clock model.
Therefore if someone has just added a new Clock model to the simulation it will have null Start and End date until supplied in the property presenter. Therefore I was trapping this situation.

**Comment by zur003** [comment]
@lie112 - But StartDate and EndDate can never be null; they are of type DateTime, not DateTime?. What you can do to check for unintialised values is, rather than test them against null, test them against the default value for DateTime.  So something like if (clk.StartDate = default(DateTime)) might be what you want. (The default value for DateTime is apparently DateTime.MinValue, which is 1 January 0001, and unlikely to appear in most simulations.)

**Comment by zur003** [comment]
Thinking about this a bit more, and looking at how the StartDate and EndDate properties are implemented in Clock.cs, perhaps you just want to use the nullable Start and End properties rather than the non-nullable StartDate and EndDate properties when testing for unintialised values.

**Comment by zur003** [comment]
Closing this, as I've included stuff that isn't going to work under 3.1.

**Pull request closed without merging**
