### PR TITLE
Improve dairy milk production

### PR DESCRIPTION
**Pull request by her123**
working on #4480

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@her123 this is still red but I think it's a legit failure now, in one of the prototypes (`LUDFStockWithSlurp_v0.apsimx`).

**Comment by her123** [comment]
It appears that this simulation uses some external parameter files (... StockAndSupplement\RuminantLUDF_035.prm). these are not the right format to match the changes in the source for the dairy revisions. I will need to modify these files and commit them to the pull request.

**Pull request merged**
