### PR TITLE
Actually ADD (!) NH4 to SurfaceOrganicMater

### LINKED ISSUE #9264: NH4 when specified as an amount is not being added to SurfaceOrganicMatter
### What happened?

For some reason the logic around NH4 was done differently to NO3 and that resulted in the NH4 not being added. 

There are other issues (to be fixed later)
- no amount option for P
- the wrong amount of C is being added or the reporting is wrong

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by sno036**
Can this be merged please. It fixes the immediate issue but there are bigger problems with SurfaceOrganicMatter that need addressing. 

resolves #9264

### CODE REVIEW

**Comment by sno036** [comment]
@par456 - the error message seems to be about file storage rather than this change itself. What is the solution here please?

**Comment by hol353** [comment]
retest this please jenkins.

The POStats database was full (happens every 3 months). I've emptied it and so am restarting the PR build.

**Comment by hol353** [comment]
retest this please jenkins.

**Comment by BrianCollinss** [comment]
@sno036 how come this didn't change any stats? For my better understanding of this module. Thanks.

**Pull request merged**
