### PR TITLE
New Cotton Model

### PR DESCRIPTION
**Pull request by TiemenRhebergen**
working on #4631

### CODE REVIEW

**Comment by ric394** [comment]
@TiemenRhebergen in your Soil.Physical layer you have 1300mm as your depth, but in your PreIrrigation management script you have set the Soil depth to 1800mm. Changing it 1300 allows the simulation to run.

image

**Comment by hol353** [comment]
@TiemenRhebergen If you click the 'Details' link above and then scroll to the top of the window and click 'Show complete log' you'll see lots of errors like:
```
ERROR in file: ./Prototypes/Cotton/Cotton Tiemen/Cotton 20230222.apsimx
Simulation name: NAR0607Ir80
Models.Core.SimulationException
 ---> System.Exception: In Boll, cannot find a plant organ called Shell
   at Models.PMF.CompositeBiomass.OnSimulationCommencing(Object sender, EventArgs e) in /tmp/ApsimX/Models/PMF/Biomass/CompositeBiomass.cs:line 49
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 320
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 320
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 214
NAR0607Ir80 (./Prototypes/Cotton/Cotton Tiemen/Cotton 20230222.apsimx) has finished. Elapsed time was 1.2 seconds.
----------------------------------------------```

Looks like you have a CompositeBiomass that references 'Shell' and 'Shell' doesn't exist.

**Comment by TiemenRhebergen** [comment]
Hi Dean,

I see that you’re running a old version of the cotton model where the reproduction parts did not have any sub components. In Cotton 20230222, bur, lint, seed did not exist yet.

I pushed the latest cotton model to GitHub last Friday; Cotton test Bollfilling and maturing 20231114.apsimx

**Comment by hol353** [comment]
Then you must still have the old file Cotton 20230222.apsimx in your directory. Jenkins runs all .apsimx files it can find. Delete the old ones and then push again.

**Pull request merged**
