### PR TITLE
reorganizing code to current standards

### PR DESCRIPTION
**Pull request by jbrider**
working on #572

@hol353 Finally getting back to sorghum - I have reorganised the order according to the coding standards spec, which has created a lot of changes.  It should go green, if so, can you merge it. 
There are more changes to come but until this one is merged it will be hard to see what those changes are (trying to make it a bit easier).
I have mainly moved code around, changed the readonly getters to use lambdas and changed some public to private.
I still have to fix some capitalisations.
There are a few private variables in the wrong place - they will be extracted out in the next stage.
I will close the old pull request once I have made sure I have captured all the changes from it.

### CODE REVIEW

**Comment by jbrider** [comment]
@hol430 @hol353 Jenkins seems to be having issues with an AssemblyVersion.cs. Is this something I have to work out on my end?

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by hol430** [comment]
Yep - you'll need to edit your initial comment and add "working on #x" (with an issue number). One of the jobs on my list is to get ApsimBot to post a comment to this effect when it spots a PR missing this bit.

**Comment by jbrider** [comment]
Oops. It has been a while...

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
@hol353 this is right to merge - and will make the next PR much easier to follow.

**Comment by hol430** [comment]
@jbrider - what's the status on #6166 - should it be closed?

**Comment by jbrider** [comment]
@hol430 It can be closed.

**Pull request merged**
