### PR TITLE
Simulation updated for first site in classic obs file

### PR DESCRIPTION
**Pull request by sme016**
working on #5105

### CODE REVIEW

**Comment by sme016** [comment]
Retest this please Jenkins

**Comment by sme016** [comment]
working on #5105

**Comment by sme016** [comment]
Retest this please Jenkins

**Comment by hol430** [comment]
Hi Phil - looks like this one is already green - ie it has run without errors, so no need to retest it. I expect @hol353 will merge it sometime soon, so no further action should be required from you.

**Comment by sme016** [comment]
OK, but I thought that test might not have included the new met file I added. I'll wait now to see what gets merged. Apologies.

**Pull request merged**
