### PR TITLE
Move Slurp into release

### LINKED ISSUE #586: Move Slurp into release

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #586

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
Don't merge this.  I still need to move the tests from prototype folder to tests folder

**Comment by HamishBrownPFR** [comment]
Also removed the Non-PMF slurp as part of this.  Two pushes stacked up to test.  Let them both run before merging

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Because I merged SCUM first, this pull request failed as you changed some of the same files. I'm not sure why Jenkins compile failed. Looks like it couldn't find the resolves tag above. Perhaps a transient error.

**Pull request merged**
