### PR TITLE
Run refactor

### PR DESCRIPTION
**Pull request by hol353**
Working on #3951

### CODE REVIEW

**Comment by hol430** [comment]
@hol353 all of the other pull requests seem to be failing (to compile) on Jenkins because of errors relating to the job manager. I suspect APSIM.Shared is still stuck on your branch. Do you mind if I push a modified version of the Jenkins script to this branch?

**Comment by hol353** [comment]
Go for it.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
