### PR TITLE
Rotations

### PR DESCRIPTION
**Pull request by peter-devoil**
working on https://github.com/APSIMInitiative/ApsimX/issues/3890

### CODE REVIEW

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@hol430 Even though this pull request is conflicted jenkins should not have run green because the collector failed - see jenkins console output. Can you make sure that if the collector fails, the jenkins run also fails.

Also need to see why the collector failed.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by peter-devoil** [comment]
Please delete this branch

**Pull request closed without merging**
