### PR TITLE
Report all simulation messages from experiments in CLEM

### LINKED ISSUE #7716: Need to display details from experiments in CLEM messages
The inclusion of experiments means all validation errors and warnings are not displayed to the user in CLEM-Messages
While these are available in the Summary model, users are now used to looking at CLEM messages for formatted details on any issues during the simulation. This will be a first start at reporting issues in multi simulation experiments without the need for an experiment dropdown as provided in Summary presenter.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7716

### CODE REVIEW

**Comment by hol353** [comment]
Why have you changed locator? It looks like you have made arguments to method calls more flexible but I don't see what this has to do with your linked issue 'Need to display details from experiments in CLEM messages'.

**Comment by lie112** [comment]
Something has stuffed up in this commit. I didn't realise that commit was with this pull request as I thought it was in the previous 
#7714 issue and #7715 pull request that it relates to. I don't know how to remove/move a commit to another pull. I think I accidently worked on the same branch where an open pull request was and this is automatically added.

**Comment by hol353** [comment]
Now that I've merged your other PR, do a pull on this branch and then repush it. Locator.cs should then disappear from this PR.

**Comment by lie112** [comment]
Sorry, I don't understand the process to do another pull on this branch. Looking at the branch in pull requests/new just leads me back to this pull request and the locator commit is still there although now above the new changes since last viewed.

**Comment by lie112** [comment]
Of course. Thanks. here it comes.

**Pull request merged**
