### PR TITLE
Add DiffuseFraction to IWeather

### LINKED ISSUE #5929: 'IWeather' does not contain a definition for 'DiffuseFraction'

### PR DESCRIPTION
**Pull request by BrianCollinss**
Resolves #5929

### CODE REVIEW

**Comment by BrianCollinss** [comment]
retest this please jenkins

**Comment by BrianCollinss** [comment]
retest this please jenkins

**Comment by BrianCollinss** [comment]
@hol430 should I retest this one?

**Comment by hol430** [comment]
From the logs:

```
Compiling...
  APSIM.Shared -> C:\Jenkins\workspace\PullRequest_v2\ApsimX\APSIM.Shared\bin\Release\APSIM.Shared.dll
  Models -> C:\Jenkins\workspace\PullRequest_v2\ApsimX\Bin\Models.exe
Presenters\CLEM\MessagePresenter.cs(131,32): warning CS0219: The variable 'type' is assigned but its value is never used [C:\Jenkins\workspace\PullRequest_v2\ApsimX\ApsimNG\ApsimNG.csproj]
  ApsimNG -> C:\Jenkins\workspace\PullRequest_v2\ApsimX\Bin\ApsimNG.exe
Weather\MockWeather.cs(8,32): error CS0535: 'MockWeather' does not implement interface member 'IWeather.DiffuseFraction' [C:\Jenkins\workspace\PullRequest_v2\ApsimX\Tests\UnitTests\UnitTests.csproj]
  Updater -> C:\Jenkins\workspace\PullRequest_v2\ApsimX\Bin\Updater.exe
  APSIMRunner -> C:\Jenkins\workspace\PullRequest_v2\ApsimX\Bin\APSIMRunner.exe
  CreateDocumentation -> C:\Jenkins\workspace\PullRequest_v2\ApsimX\Bin\CreateDocumentation.exe
```

It's failing due to a compilation error in the unit tests - you'll need to fix this. If you try to compile it locally you should see the same error.

**Comment by BrianCollinss** [comment]
I don't know what is happening with those Wheat sims!

**Comment by hol430** [comment]
retest this please jenkins

**Comment by BrianCollinss** [comment]
If you approve these changes, can it be merged?

**Comment by hol430** [comment]
I'd prefer to see what @hol353 or @hut104 thinks of this one, so it will have to wait until next year.

**Comment by hut104** [comment]
I notice that this pull request would result in nearly all simulations having shortwave radiation as totally diffuse.
PErhaps the weather component should use the existing code in NG to calculate the clearsky tranmission and from that apply the Bristow method for partitioning Radn into Diffuse and Direct components.  This would allow people to start using the values in light interception and photosynthesis models from normal APSIM met files.

**Comment by BrianCollinss** [comment]
We have this code in **CanopyPhotosynthesis.cs**, but it works at hourly time scale. Do you think we can adapt and adopt it?

                  ```
  AtmTrans = PAR / (0.5 * SolarConst * SinHeight);

                    if (DifFr < 0)
                    {
                        if (AtmTrans <= 0.22)
                            DifFr = 1.0;
                        else
                        {
                            if ((AtmTrans > 0.22) && (AtmTrans <= 0.35))
                                DifFr = 1.0 - 6.4 * (AtmTrans - 0.22) * (AtmTrans - 0.22);
                            else
                                DifFr = 1.47 - 1.66 * AtmTrans;
                        }
                        DifFr = Math.Max(DifFr, 0.15 + 0.85 * (1.0 - Math.Exp(-0.1 / SinHeight)));
                    }

                    if (DifFr < 0 | DifFr > 1)
                        throw new Exception("Diffuse fraction should be between 0 and 1.");
```

**Comment by BrianCollinss** [comment]
Currently only Enli's Photosynthesis module uses diffusion fraction, which is calculated internally if it is less than zero. Can we accept these changes as a placeholder for something more permanent which someone may implement later?

**Comment by BrianCollinss** [comment]
retest this please jenkins

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - does this need a separate discussion/workshop etc..?

**Comment by BrianCollinss** [comment]
retest this please jenkins

**Comment by hut104** [comment]
I note that the code for introducing slope and aspect effects also has its own code for diffuse fraction (and clear sky radiation value, and extraterrestrial radation!!!!)
All a bit of a mess.
We should perhaps clean this up.

**Comment by hut104** [comment]
I've pulled down your repo and added some code to estimate a diffuse fraction for the day based on the existing code used in weather.cs and various utilities already in NG. I can't push the changes back into your repo.  You'll need to pull them down from mine.

https://github.com/hut104/ApsimX/tree/DiffuseFr

**Comment by BrianCollinss** [comment]
Hi @hut104 . This branch is exactly like my own. Have you pushed your changes to your online branch?

image

**Comment by hut104** [comment]
Sorry about that. Try again

________________________________

**Comment by hut104** [comment]
Tests for that code now added to my repo

**Comment by BrianCollinss** [comment]
What do you think @hut104 ?

image

**Comment by hut104** [comment]
I've added test data for an arid location and a tropical location now as well.
I think we have an issue in the units of vapour pressure when discounting the trasmissivity of the atmosphere for water vapour.

**Comment by BrianCollinss** [comment]
retest this please jenkins

**Comment by BrianCollinss** [comment]
@hol430 I am not sure what happened here? Is there a problem in build process?

**Comment by hut104** [comment]
Check the file paths to the met files. Apsim hi sometimes adds full paths. The path should only be the filename.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by BrianCollinss** [comment]
image

**Comment by hut104** [comment]
@hol353 Is this right to merge?

**Pull request merged**
