### PR TITLE
Testing some changes to report aggregation

### LINKED ISSUE #3305: In 'Reporting Variables' panel, events cannot be chosen from a pop-up list
It would be handy if we could choose **events** like **[Wheat].Sowing** from a pop-up list (like other objects or traits) when we need to calculate an aggregated value using arithmetic functions. Users are not usually familiar with all the **events** available. Currently **events** can only be chosen that way in the **Reporting frequency** panel in **Report** objects, not in the **Reporting variables** panel.

image

### PR DESCRIPTION
**Pull request by hol430**
Working on #3316 
Resolves #3305

### CODE REVIEW

**Comment by hol430** [comment]
Depends on APSIMInitiative/APSIM.Shared#77

**Comment by sno036** [comment]
@hol430 - as you are working on this .... is it possible for the array aggregation to put something in that sums (for example) the whole array?  e.g. sum(nh4n[]) or sum(nh4n[:])? At present the from/to indices need to be inserted and this causes issues with using the same report across multiple soil descriptions etc.

Also suggest adding in the documentation for clarity that if indices are used, they are 1 (not 0) based.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
I thought you could just put `sum(nh4n)` into report...does this not work?

**Comment by sno036** [comment]
Duh!

**Comment by sno036** [comment]
Hi Drew - thanks for this - the " to [Clock].Today" is now working correctly.  Is there any possibility of having something like 
    sum of [Weather].Rain from *TheReportsLastReport* to [Clock].Today as sumRainBetweenReports
where *TheReportsLastReport*  is some sort of keyword that knows when this particular Report (there can be several Report models in a single simulation) last did an output?

**Comment by hol430** [comment]
Off the top of my head I don't think this will be as simple as adding a LastReportDate property to the report - I'll look into it.

**Pull request merged**
