### PR TITLE
Fix manager overrides bug + add test.

### LINKED ISSUE #8911: --apply does not change manager parameters
### What happened?

I am unsure whether this is a bug.

In the following config commands, the first line works fine and replaces the met file name. But the second line does not change the manager script parameter, with or without quotation marks.

```
[Weather].FileName = Met/AU-Emerald.met
[Sowing].Script.SowDate = 15-Jan   ---> OR ("15-Jan")
```

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by ric394**
resolves #8911

## Notes
- The manager script was not updating its parameters after they were modified.
- This meant that when the file was being saved, the changes were not saved.
- A conditional statement was added to update the parameters of any manager scripts being overridden.
- A test was added to ensure this always occurs.

### CODE REVIEW

**Comment by BrianCollinss** [comment]
I just ran the example I had shared with you and the SowDate is still 15-Aug instead of 15-Jan or 15-Sep.

image

**Comment by BrianCollinss** [comment]
It's working on my example sims. Ta

**Comment by hol353** [comment]
This branch is now conflicted.

**Comment by BrianCollinss** [comment]
On HPC, sims failed as APSIM --apply adds "" around the SowDate:

image

**Pull request merged**
