### PR TITLE
Sorghum devt

### PR DESCRIPTION
**Pull request by jbrider**
working on #572

### CODE REVIEW

**Comment by jbrider** [comment]
The converter functions don't seem to run on the models already in the resources folder.
Is there a different process for them?

The link functions are not case sensitive for the first letter, but they are for the remainder of the name - is this on purpose?

**Comment by HamishBrownPFR** [comment]
Converter only works on .apsimx files.  To convert a .xml there is a button on the toolbar in the UI, "Convert XML file"

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by jbrider** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@jbrider I am working on implementing the same structure for N demands as what I have for DM demands at the moment.  Not sure how long this will take me to complete but it would allow tidier implementation of the SLN demand when done.

**Pull request merged**
