### PR TITLE
Merge in latest sorghum changes

### PR DESCRIPTION
**Pull request by hol430**
Working on #572

### CODE REVIEW

**Comment by sarahcleary** [comment]
@jbrider - should this be tagged as ready for review?

**Comment by jbrider** [comment]
It probably can - we're still waiting on some science changes and have a
few things to look at cleaning up that require the stats process - which
requires having it in the under review folder.
I was going to discuss it at the panel meeting next week.

**Comment by sarahcleary** [comment]
Thanks @jbrider. Will add it to the agenda.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 the performance tests are failing because there are no accepted stats for sorghum.

**Comment by hol353** [comment]
I merged this too soon. There appears to be some non sorghum changes in here.

**Comment by hol430** [comment]
Which file?

**Pull request merged**
