### PR TITLE
Fixed cultivar names returned by Plant

### LINKED ISSUE #6387: Euc cultivar selection fails dt inclusion of memo
Using the TreeManagement Tool in the EucalyptusRotation example (at least - maybe in other examples too), selecting a cultivar causes the simulation to fail as the assoicated memo is included - see screenshot
image

### PR DESCRIPTION
**Pull request by hol430**
Resolves #6387

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Won't this remove all the alias names from the returned list of cultivar names?

**Comment by hol430** [comment]
Yes. How are the alias names supposed to work? Or rather, what are they supposed to do?

**Comment by hol353** [comment]
Alias are just different names for the same cultivar. The wheat model makes extensive use of these where a cultivar is known by many different names. It will allow the user to sow the cultivar that they know and behind the scenes it is mapped to another name. We need to keep this feature.

**Comment by hol430** [comment]
Ok, I've tweaked the way that this works. The Alias property is no longer referenced by any of our code outside the Cultivar class - I'd like to remove this property altogether, but do we need to allow for manager scripts which reference it?

**Comment by hol353** [comment]
You can remove the alias property. It should be an internal thing only. I don't think any manager scripts will use it (famous last words!)

**Comment by hol353** [comment]
Do you want to get rid of :

```c#
public string[] Alias
```

from the Cultivar class before I merge this?

**Comment by hol430** [comment]
Yep, I'll do that.

**Pull request merged**
