### PR TITLE
Changed NUptake routine to match PMF

### PR DESCRIPTION
**Pull request by hol353**
Working on #5356

### CODE REVIEW

**Comment by hut104** [comment]
I'd imagine that we're close to pulling this out into a dedicated function in PMF for maintainability reasons.  Would this work in AgPasture?

**Comment by hol353** [comment]
Yep that would be ideal.

**Comment by mpandreucci** [comment]
@hol353 do I add these changes to my AgPasture for now so that I can move on with trying to sort out the simulations with high N?

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@mpandreucci : Yes add these changes. I'll merge this in the next hour or so. Just want to rerun it first.

**Comment by mpandreucci** [comment]
Cool. Thanks

**Comment by hol353** [comment]
Do we really want to merge this yet given the very poor model fit?
image

**Pull request closed without merging**
