### PR TITLE
Added some new output for World Modelers use; allow additional grazin…

### PR DESCRIPTION
**Pull request by zur003**
…g to be initiated from a manager script; prevent culture setting problem when reading parameters.
Working on #4534

### CODE REVIEW

**Comment by zur003** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@zur003 We (as in @hol430) are looking into why our builds are all failing.

**Comment by zur003** [comment]
It appears to be related to the recent addition of a test which attempts to delete a .db file. For whatever reason, the .db file is held open.

**Comment by zur003** [comment]
Got my git branches confused. Will close this pull request and submit a new one after tidying up.

**Pull request closed without merging**
