### PR TITLE
added obs data for kingaroy8485 and Ord

### PR DESCRIPTION
**Pull request by hut104**
working on #4075

### CODE REVIEW

**Comment by hut104** [comment]
retest this please jenkins

**Comment by hut104** [comment]
retest this please jenkins

**Comment by EnliWang** [comment]
@hut104 How far has the work progressed now? We are working on a list of Chinese datasets, would like to add to this?

**Comment by hut104** [comment]
Certainly.

The model is still essentially a soybean plant with basic alterations.  Most focus has been on finding datasets.  Do the datasets have all the required data (crop, management, soil, climate)?

________________________________

**Pull request merged**
