### PR TITLE
Reworked the startup screen in the GUI

### LINKED ISSUE #757: Suggestion: Upgrade button should be on "home" window
The Upgrade button appears only after opening a simulation or toolbox - why? I suggest placing it on the "home" window in the standard section next to e.g. "Open an example".

### PR DESCRIPTION
**Pull request by hol353**
Resolves #757

### CODE REVIEW

**Comment by zur003** [comment]
Implementing this in GtkSharp will be left as an exercise for the student.

**Comment by hol353** [comment]
Yes, I wondered about GtkSharp when I was doing this. In the end I decided that Eric would sort it because he loves GtkSharp.

**Comment by hol353** [comment]
Actually I need to do some more refactoring of this view to fix a few other problems.

**Comment by zur003** [comment]
I think the time has come for me to share the love.

**Pull request merged**
