### PR TITLE
Fixed errors in soil water parameters (e.g. AD>LL)

### PR DESCRIPTION
**Pull request by hut104**
working on #1418

### CODE REVIEW

**Comment by hut104** [comment]
retest this please

**Comment by hol353** [comment]
Why is there a change to the file:  Jenkins/performanceTests.bat???

**Comment by hol430** [comment]
There was a problem with one of our webservices where it returned a non-200 HTTP response code. I'm not sure what caused it and I doubt I can reproduce it. Unfortunately this also revealed a typo in one of the Jenkins scripts because we didn't get any detailed info about the failure. I fixed the script on this pull request in the hope that the problem in the webservice would show up again when the tests were rerun, but that didn't end up happening.

**Comment by hol353** [comment]
So do you want this merged?

**Comment by hol430** [comment]
The jenkins change is good to merge. I assume Neil's changes are safe as well - they ran green on Jenkins anyway.

**Pull request merged**
