### PR TITLE
PhenologyEventTests

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
Working on #2850
Give IsAlive identical behaviour to IsGerminated to test if they can be combined

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hol353.  Dont merge this as it will conflict with your work on leaf refactoring.  I am just running this the check I have got everything right before I need to merge it with your stuff.

**Comment by HamishBrownPFR** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
This is now green. Merge it?

**Comment by HamishBrownPFR** [comment]
Yes please

**Pull request merged**
