### PR TITLE
Fix RotationManager transition messages

### LINKED ISSUE #7280: RotationManager verbose output shows incorrect transition messages
When you put a RotationManager in 'Verbose Mode', the simulation log shows messages like "Transition from Wheat to Wheat is not possible. Weight = 0", but it is actually talking about a transition from the previous state to wheat.

PR coming soon.

### PR DESCRIPTION
**Pull request by AJChapman**
Resolves #7280.

### CODE REVIEW

**Comment by zur003** [comment]
This has been sitting here a long time. 
Retest this please Jenkins

**Comment by zur003** [comment]
@AJChapman - The bug appears to still be there, and ought to be fixed. If you edit your original comment and change "Fixes" to "Resolves", then add a new comment requesting Jenkins to retest, it should run and be ready to merge.

**Comment by ric394** [comment]
retest this please jenkins

**Comment by par456** [comment]
retest this please jenkins

**Pull request merged**
