### PR TITLE
Add datasets to ForagePlantain

### LINKED ISSUE #7736: Add validation data to ForagePlantain
We have a few more dataset to add to the plantain validation set. 
Based on these, a few model improvements are also being implemented

### PR DESCRIPTION
**Pull request by rcichota**
Resolves #7736 
Adding two new dataset to the validation,
Plus improvements in the model done in light of the new data

### CODE REVIEW

**Comment by rcichota** [comment]
Resolves #7736

**Comment by rcichota** [comment]
Retest this please Jenkins

**Comment by rcichota** [comment]
@hol353 
I am not quite following the 'error' message. It said a reference to an issue was missing, I added it and trigger a retest (twice), but the message seem to still be the same... Can you help me please. Thanks

**Comment by rcichota** [comment]
retest this please jenkins

**Comment by zur003** [comment]
@rcichota - The "Resolves #7736" needs to be edited into the original comment, not just placed in a new one. To edit an existing comment, click on the triple dots in the upper right corner of the comment box, and choose Edit from the resulting menu. Then you can ask Jenkins to retest (but don't expect it to pass, as there are still problems in the build system).

**Comment by rcichota** [comment]
Thanks @zur003 
Did not realise the info regarding issue needed to be in the original comment (have been doing wrong all this time - or sometimes at least). Hope the build system will be fixed soon, any prognosis? (just curious, not in much hurry)

**Comment by rcichota** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
I have killed this build, sorry @rcichota. I'm working on the build system at the moment. It isn't running correctly. I'll retest your PR when it is fixed.

**Comment by rcichota** [comment]
Cool, thanks

**Comment by hol353** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by rcichota** [comment]
Retest this please jenkins

**Comment by rcichota** [comment]
@hol353 
I believe this can be merged. The differences in stats are fairly small now and mostly a reflection of an increase in the amount of data (a bit more dispersion). I am happy enough with that and we will likely make further changes as there are further work me and Xiumei will be doing over the next few months. But for now this is it...
I am not sure about the error showing up on Jenkins, the message says something about the Peanut simulation, I haven't touched anything other than the Plantain simulation...

**Comment by par456** [comment]
retest this please jenkins

**Comment by rcichota** [comment]
Thanks @par456 , the build finished ok. 
@hol353 , the stats are just a bit worse than before, due to the inclusion of more data. If you happy it can be merged. There is more we want to do over the next few months, but we'll deal with that later.

**Pull request merged**
