### PR TITLE
Read diffuse fraction from weather file

### LINKED ISSUE #3190: Read diffuse fraction from weather file

### PR DESCRIPTION
**Pull request by byzheng**
resolves #3190

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
You'll need to fix your merge conflicts to get this to run green.

**Comment by byzheng** [comment]
retest this please jenkins

**Comment by behnamxa** [comment]
Banyou, by any chance, did you see mu comment here (https://github.com/APSIMInitiative/ApsimX/pull/3183)? I'm not sure if you get github notifications.

**Pull request merged**
