### PR TITLE
Fixed a bug in GraphPage code

### LINKED ISSUE #6625: Graphing Events does not work...again
Go to the most recently pushed version of "MungbeanwithNewPhenology." It or some version of the problem is in all the graphs.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #6625

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 this is failing on the performance tests:

```
The DELETE statement conflicted with the SAME TABLE REFERENCE constraint "FK_PullRequest_PullRequest_AcceptedPullRequestId". The conflict occurred in database "APSIM.POStats", table "dbo.PullRequest", column 'AcceptedPullRequestId'.
```

Do you know anything about this?

**Comment by hol353** [comment]
?? No idea. I don't understand the error message at all. Other PRs have run green haven't they since we created a new po stats database last week.

**Comment by hol430** [comment]
Ok, I'll try opening a new PR.

**Pull request closed without merging**
