### PR TITLE
When importing old .apsim files, add fert/irrigation nodes if needed.

### LINKED ISSUE #2762: import of old APSIM files bringing faulty nodes
SurfaceOM needs to be renamed SurfaceOrganicMatter when the import occurs

Also the crop specific characteristics within soil/water needs to be renamed CropSoil, not just 'crop' as it is at the moment.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #2762

### CODE REVIEW

**Comment by jbrider** [comment]
Can you add a check if the irrigation is set to automatic - it needs to add
the automatic irrigation script with the relevant parameters.

**Comment by hol430** [comment]
Good thinking - that would have been handy a few weeks ago

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
Ahh...I don't think this one was good to merge

**Pull request merged**
