### PR TITLE
Move everything to 64-bit. This also requires use of .Net 4.6.

### LINKED ISSUE #2199: Move to 64bit APSIM Next Generation
We need this urgently so that large simulations with many zones (e.g. #2195) can run. Val will also probably run into this problem when she explores larger urine patch modelling.

The problem is going to be the third party packages we use in particular the GTK and SQLite .dll files.

@zur003 Do you have time to look into this?

### PR DESCRIPTION
**Pull request by zur003**
Resolves #2199

### CODE REVIEW

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
@hol353 - Dean, this all "works" but don't merge just yet. I realised that I don't have the VC runtime stuff all set up correctly with the installer. Other than that, it all seems good.

**Comment by zur003** [comment]
@hol353 - OK. This should all be perfect now.

**Comment by zur003** [comment]
@hol353 - It looks like this can still be made to work with version 4.5 of the .Net framework. Should I revert back to that?

**Comment by hol353** [comment]
I don't mind targeting .NET 4.6. Leave it as it is. Is this ready to be merged? Should we change 'working on' to 'resolves' at the top?

**Comment by zur003** [comment]
Yes, it's ready to merge. I will change the "working on" text.

**Pull request merged**
