### PR TITLE
Sorghum/cleanup

### PR DESCRIPTION
**Pull request by jbrider**
working on #572 

So much for not many changes.
No changes expected to the model results at this stage.

### CODE REVIEW

**Comment by jbrider** [comment]
@hol353 this is right to merge.
Apologies for the number of changes - I know it's not easy to follow when moving code to different places.
Would you prefer more changes to this one, or create new ones?

**Review by hol430 — CHANGES_REQUESTED** [review]
Looks good to me, except there are a few private methods which start with lower case letters - all methods should start with upper case letters.

https://apsimnextgeneration.netlify.app/development/software/codingstyle/

**Comment by jbrider** [comment]
very minor changes expected.

**Review by hol430 — APPROVED** [review]
Looks good, changed bits all comply with style guidelines.

**Pull request merged**
