### PR TITLE
Lucerne_1721 updated

### PR DESCRIPTION
**Pull request by Xiumei2017**
Working on #1721

Bring in working progress since last pull request.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 @hol430 I can't reach jenkens to check the reason for the build failure, browser is returning an error:

image

I assume clicking the details link should still take you to Jenkens??

**Comment by hol430** [comment]
The link seems to work for me...I think Val had some issues getting to Jenkins some time ago due to the firewall blocking it (@sno036?). Can you follow the link on your phone, using mobile data? If so, maybe you need to talk to your IT people. 

Here's the error message if that helps:
```
Commencing simulations...
ERRORS FOUND!!
Error in file: C:\Jenkins\workspace\PullRequest_v2\ApsimX\Prototypes\Lucerne\LucerneValidation.apsimx /RunTests
ERRORS FOUND!!
System.Exception: Duplicate simulation names found: Iversen_91DefoliationLL in simulation Iversen_91
   at Models.Core.Runners.RunOrganiser.GetNextJobToRun() in C:\Jenkins\workspace\PullRequest_v2\ApsimX\Models\Core\Runners\RunOrganiser.cs:line 91
   at APSIM.Shared.Utilities.JobRunnerAsync.JobRunnerThread(IJobManager jobs, Int32 numberOfTasksToUse) in C:\Jenkins\workspace\PullRequest_v2\APSIM.Shared\Utilities\JobRunnerAsync.cs:line 77
----------------------------------------------
Finished running simulations. Duration 14.33 sec.
----------------------------------------------


Finished running simulations. Duration 861.28 sec.

script returned exit code 1
```

Looks like the Lucerne prototype failed. You should be able to reproduce this on your pc by pulling down upstream changes and running the LucerneValidation.apsimx.

**Comment by sno036** [comment]
@HamishBrownPFR - yes the issue I had was a net nanny thing. It is resolved for AgR but PFR might have blocked it more recently.

**Comment by hol430** [comment]
@Xiumei2017 @HamishBrownPFR do you guys have access to Jenkins now?

**Pull request merged**
