### PR TITLE
Update of CLEM specific reporting

### LINKED ISSUE #7457: Errors thrown on creating views from CLEM reports when no database present
There a number of vague errors thrown when there is no database as CLEM attempts to build database views.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7457

### CODE REVIEW

**Comment by lie112** [comment]
I'm not sure what the harfbuzzsharp nuget packages jenkins is complaining about. As far as I can tell my branch is fully up to date with APSIM. Is there something I need to do to get this build to succeed and get this upgrade to users?

**Comment by zur003** [comment]
I don't think harfbuzzsharp is the problem - that bit just looks like a warning (possibly a file conflict as Jenkins was building multiple projects simultaneously, with the problem resolving after a couple of retries). The blocking error looks to be in the unit tests, with TestReadDate, TestReadDouble, TestReadDoubleArray and TestReadInt failing.

**Comment by zur003** [comment]
I'm not sure why those unit tests failed, so I shall try:

test this again, please, Jenkins.

**Comment by zur003** [comment]
Or, rather, 
retest this please Jenkins

**Comment by hol353** [comment]
retest this please Jenkins

**Pull request merged**
