### PR TITLE
add barley simulations for NPI 2020 field experiment

### PR DESCRIPTION
**Pull request by ZhiganZhao**
working on #6435

### CODE REVIEW

**Comment by byzheng** [comment]
@hol430 We get an error for this pull request which seems there are some trouble in the Jenkins. Could you have a look?

```
Building installer...
bash: /tmp/ApsimX/Setup/netcoreapp3.1/debian/buildDebianInstaller: No such file or directory
script returned exit code 127
```

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@byzheng - I was testing some changes to jenkins earlier. I've reverted the changes so this is running normally again. Looks like some legit errors though:

```
ERROR in file: ./Tests/Validation/Barley/Barley.apsimx
Simulation name: YanYean2020TOS2CvRosalind
Models.Core.SimulationException
 ---> System.Exception: Invalid number of values on line: 1,2020-03-09,2020-03-09,2020-03-09,2020-03-09,2020-03-10,2020-03-10,2020-03-09,2020-03-11,2020-03-09,2020-03-10,2020-03-09,2020-03-11,2020-03-10,2020-03-08,2020-03-09,2020-03-09,2020-03-10,2020-03-09,2020-03-08,2020-03-10,2020-03-09,2020-03-09,2020-03-09,2020-03-09,2020-03-10,2020-03-11,2020-03-09,2020-03-09,2020-03-10,2020-03-12,2020-03-10,2020-03-09,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
in file: /tmp/ApsimX/Tests/Validation/Barley/YanYeanEmergenceDates2020.csv
   at APSIM.Shared.Utilities.ApsimTextFile.GetNextLine(StreamReaderRandomAccess inData, StringCollection& words) in /tmp/ApsimX/APSIM.Shared/Utilities/ApsimTextFile.cs:line 605
   at APSIM.Shared.Utilities.ApsimTextFile.Open() in /tmp/ApsimX/APSIM.Shared/Utilities/ApsimTextFile.cs:line 194
   at Models.Script.OnStartOfSimulation(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e) in /tmp/ApsimX/Models/Clock.cs:line 283
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 273
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 282
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 200
YanYean2020TOS2CvRosalind (./Tests/Validation/Barley/Barley.apsimx) has finished. Elapsed time was 0.8 seconds.

```

**Comment by byzheng** [comment]
@ZhiganZhao  Could you have a look?

**Comment by ZhiganZhao** [comment]
@hol430 @byzheng Thanks Drew and Bangyou. I will fix this.

**Comment by hol353** [comment]
You need to edit the top comment box and add a 'working on ' or 'resolves' followed by a github issue number with a '#' symbol at the front of it. Look at other pull requests to see what I mean.

**Comment by hut104** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hut104** [comment]
@hol353 I think this can be merged.  The changes are due to extra data added, and some changes to results within the new data.  I refitted some cultivars to make the field data better. This had some impact on controlled environment datasets, but I'm more worried about users simulating real fields.

**Pull request merged**
