### PR TITLE
Mcsp #166

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
MCSP model set up and tested with a basic set of tests and documentation.  No validation is included because this is not a mechanistic model and can not really be validated sensibly (happy to be challenged on this)

Some code changes were made so expecting some problems in the tests that will need fixing before this pull request can be put up to the RP. Working on #166

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
Not sure why this failed?  If someone can explain it I will fix it.

**Comment by hol353** [comment]
Hamish you need to put 'working on #...' In the pull request text. That will link it to an issue. Jenkins requires it now.

**Comment by HamishBrownPFR** [comment]
Can you make it so jenkens can get the issue number out of the branch name?

**Comment by HamishBrownPFR** [comment]
#166

**Comment by HamishBrownPFR** [comment]
How do I trigger a new test on jenkens.  If I push more stuff up the the branch that has the pull request it triggers a test but resolving this issue does not require any further pushing

**Comment by hol353** [comment]
reset this please Jenkins.

**Comment by hol353** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
Retest this please Jenkins

**Comment by HamishBrownPFR** [comment]
OK, turns out my programming was a bit better than I remembered and it didn't fail where I thought it would.  

What is the process now to get this up to reference panel?

**Comment by hol353** [comment]
Neil simply sent the generated PDF to Chris Murphy via email, citing the issue number e.g. 166. Also a good idea to recommend a reviewer. I'll merge this pull request now as your MCSP model is in prototypes (where it should be)

**Comment by zur003** [comment]
Looking for a bit of clarification on the Jenkins build requirements. Is the phrase "working on #x" required, or is it just the presence of "#x" that is required? Presumably "resolves #x" remains it's own bit of special magic? The "Development Process" page on apsim.info mentions the need for "Resolves", but makes no reference to "working on".

**Comment by hol353** [comment]
Should have "working on #..." or "resolves #...". Jenkins actually requires this now or it won't compile. I'll update the development process page.

On 31/07/2015 10:45 AM, zur003 wrote:

Looking for a bit of clarification on the Jenkins build requirements. Is the phrase "working on #x" required, or is it just the presence of "#x" that is required? Presumably "resolves #x" remains it's own bit of special magic? The "Development Process" page on apsim.info mentions the need for "Resolves", but makes no reference to "working on".

**Pull request merged**
