### PR TITLE
Convert CarbonConcentration as a Link

### LINKED ISSUE #2228: CarbonConcentration is not a link property

### PR DESCRIPTION
**Pull request by byzheng**
resolves #2228

### CODE REVIEW

**Comment by byzheng** [comment]
retest this please Jenkins

**Comment by byzheng** [comment]
@hol353 I added a few missing attributes in the apsimx files (CarbonConcentration for PerennialLeaf), but finally noticed I can update it in the ConvertToLatestVersion.

**Comment by hol353** [comment]
Bangyou, don't include the .apsimx files in the Tests and Prototypes directory. No need to commit them.

**Comment by hol353** [comment]
Bangyou, I can't see any need for wheat.apsimx being in this pull request.

**Comment by byzheng** [comment]
OK I will remove it.

**Pull request merged**
