### PR TITLE
N demand refactor

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #2202

### CODE REVIEW

**Comment by hol430** [comment]
This failed because Muck ran out of disk space. I will do some cleaning up, and then retest when ready.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@HamishBrownPFR you will need to resolve these merge conflicts before this can run on Jenkins.

**Comment by jbrider** [comment]
Sorry @HamishBrownPFR - I thought Dean was waiting on yours before merging mine or I would have asked him to hold off on it. Bad assumption in hindsight.

**Comment by HamishBrownPFR** [comment]
No worries guys, already on to it.

@jbrider I will leave the SLN functionality you have included in there and let you remove it.  Is that OK

**Comment by jbrider** [comment]
@HamishBrownPFR Not a problem.

**Comment by HamishBrownPFR** [comment]
@hol430 I think there is a problem with Jenkins, this one has been sitting nearly complete for about 20 min

**Comment by hol430** [comment]
I think Jenkins heard you

**Comment by HamishBrownPFR** [comment]
@hol353 this is good to merge if you are happy with it.  I have dropped a little bit of detail out of the N demand calculations in pushing them out into functions so was expecting some changes.  There are a number of red crosses but they are all trivial reductions and mostly on stats that were already poor.  This is balanced by a number of green ticks which are also trivial.  Overall the models are all still working as well as they were before the change.  

This resolves #2202

**Comment by HamishBrownPFR** [comment]
Killing this because there are unrelated files showing up in the pull request.  Yet again these are not actually part of my pull request and don't show up on the origin pull request.  I wish I knew what was causing this

**Comment by hol430** [comment]
@HamishBrownPFR which version control UI do you use?

**Comment by HamishBrownPFR** [comment]
Im using SmartGit.  I think I have worked out what is causing this.  Only been happening since I got a new computer and seems the default option when you do a pull is rebase rather than merge.  This sometimes gives a detached head which is when I see this behavior.   I have changed now to merge rather than rebase so hopefully that fixes it

**Pull request closed without merging**
