### PR TITLE
merge with priority allocation

### PR DESCRIPTION
**Pull request by junqi108**
working on #1822

### CODE REVIEW

**Comment by junqi108** [comment]
retest this please jenkins

**Comment by junqi108** [comment]
@hol353 @HamishBrownPFR 
hi Dean and Hamish: could you give some tips about how to resolve this pull request error? 
image

**Comment by hol353** [comment]
The build system is broken at the moment. @hol430 is working on it.

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
