### PR TITLE
Initial work on a sorghum validation set

### PR DESCRIPTION
**Pull request by hol430**
Working on #572

### CODE REVIEW

**Comment by hut104** [comment]
note spelling mistake in error message
  throw new Exception("Imvalid demand property");

**Comment by hol430** [comment]
Yeah there's more than a few spelling mistakes to be found around the place (seem to recall a 'wether' which should be 'whether' among others). I didn't want to touch anything I didn't have to in this pull request though.

Maybe we need some more converters like this one:

```csharp
/// <summary> Upgrades to version 6. Make sure all KLModifier, KNO3, KNH4 nodes have value XProperty values. </summary>
private static void UpgradeToVersion6(XmlNode node, string fileName)
{
	foreach (XmlNode n in XmlUtilities.FindAllRecursivelyByType(node, "XProperty"))
	{
		if (n.InnerText == "[Root].RootLengthDensity" ||
			n.InnerText == "[Root].RootLengthDenisty" ||
			n.InnerText == "[Root].LengthDenisty")
			n.InnerText = "[Root].LengthDensity";
	}
}
```

**Comment by zur003** [comment]
In the Apsim context, "wether" (or maybe "weather") seems every bit as likely to be the intended word as "whether".

**Comment by hol430** [comment]
`//wether the retranslocation is added or removed is confusing`

**Pull request merged**
