### PR TITLE
8836 add FAR data

### LINKED ISSUE #8836: Add FAR datasets to wheat validation
### Describe the new feature

Add 2016-2022 FAR high yielding experiment data to wheat validation

### PR DESCRIPTION
**Pull request by bj-far**
Resolves #8836

Add simulations and data for FAR experiments 2016-2022 (via GRDC FAR2304-002RTX) as per #8836. 
Selected simulations have cultivars already in APSIM and either many NDVI (Greenseeker) measurements, or a combination of at least several, and some dry matter measurements. SILO weather data has been adjusted to match on-site weather stations (indicated with '8' in codes in .met file).
Still needs appropriate memos written for each experiment, but would appreciate an initial assessment of anything else that needs to be done in preparation for inclusion!

### CODE REVIEW

**Comment by par456** [comment]
retest this please jenkins

**Comment by par456** [comment]
Looks like one of the experiments have a report that is throwing.

`
ERROR in file: ./Tests/Validation/Wheat/Wheat.apsimx
Simulation name: YanYean2020TOS8CvAxe
Models.Core.SimulationException
 ---> System.Exception: Error in report DailyReport: Invalid report variables found:
NDVIModel.Script.NDVI: Unable to find any model with name or type NDVIModel in scope of DailyReport
   at Models.Report.DoOutput() in /tmp/ApsimX/Models/Report/Report.cs:line 246
   at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in /tmp/ApsimX/Models/Clock.cs:line 506
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 320
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 320
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 214
YanYean2020TOS8CvAxe (./Tests/Validation/Wheat/Wheat.apsimx) has finished. Elapsed time was 1.2 seconds.
WaterByNFactorialIrrigationWetNitrogen400 (./Tests/Validation/Barley/Barley.apsimx) has finished. Elapsed time was 7.8 econds.
MaizeScen1N300 (./Tests/Validation/System/FACTS_CornSoy/FACTS_Ames.apsimx) has finished. Elapsed time was 111.4 seconds.
BRI_6Cane (./Tests/Validation/Grapevine/grapevine.apsimx) has finished. Elapsed time was 33.3 seconds.
FSA703A (./Tests/Validation/Pinus/Pinus.apsimx) has finished. Elapsed time was 98.3 seconds.
SobolMethodExampleSimulation249 (./Examples/Tutorials/Sensitivity_SobolMethod.apsimx) has finished. Elapsed time was 11.2 seconds.
WinchmoreWaterMgmtIrrigated (./Tests/Validation/AgPasture/AgPasture.apsimx) has finished. Elapsed time was 152.9 seconds.
MorrisMethodExampleSimulation99 (./Examples/Tutorials/Sensitivity_MorrisMethod.apsimx) has finished. Elapsed time was 37.9 seconds.
ExperimentSOC7.5Load250DUL0.4 (./Examples/Tutorials/Sensitivity_FactorialANOVA.apsimx) has finished. Elapsed time was 50.4 seconds.
ERRORS FOUND!!
Elapsed time was 1032.0 seconds
script returned exit code 123
`

**Comment by bj-far** [comment]
I added the NDVIModel.Script.NDVI model to the daily report in Replacements so that the NDVI graphs would work. 
Could remove it (and the NDVI graphs out of the FAR experiments) - or is there a better way of making it work for all of the experiments where the NDVIModel exists, without adding to the proliferation of reports?

> Looks like one of the experiments have a report that is throwing.
> 
> `ERROR in file: ./Tests/Validation/Wheat/Wheat.apsimx Simulation name: YanYean2020TOS8CvAxe Models.Core.SimulationException ---> System.Exception: Error in report DailyReport: Invalid report variables found: NDVIModel.Script.NDVI: Unable to find any model with name or type NDVIModel in scope of DailyReport at Models.Report.DoOutput() in /tmp/ApsimX/Models/Report/Report.cs:line 246 at Models.Clock.OnDoCommence(Object _, CommenceArgs e) in /tmp/ApsimX/Models/Clock.cs:line 506 at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 320 --- End of inner exception stack trace --- at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) in /tmp/ApsimX/Models/Core/Simulation.cs:line 320 at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in /tmp/ApsimX/APSIM.Shared/JobRunning/JobRunner.cs:line 214 YanYean2020TOS8CvAxe (./Tests/Validation/Wheat/Wheat.apsimx) has finished. Elapsed time was 1.2 seconds. WaterByNFactorialIrrigationWetNitrogen400 (./Tests/Validation/Barley/Barley.apsimx) has finished. Elapsed time was 7.8 econds. MaizeScen1N300 (./Tests/Validation/System/FACTS_CornSoy/FACTS_Ames.apsimx) has finished. Elapsed time was 111.4 seconds. BRI_6Cane (./Tests/Validation/Grapevine/grapevine.apsimx) has finished. Elapsed time was 33.3 seconds. FSA703A (./Tests/Validation/Pinus/Pinus.apsimx) has finished. Elapsed time was 98.3 seconds. SobolMethodExampleSimulation249 (./Examples/Tutorials/Sensitivity_SobolMethod.apsimx) has finished. Elapsed time was 11.2 seconds. WinchmoreWaterMgmtIrrigated (./Tests/Validation/AgPasture/AgPasture.apsimx) has finished. Elapsed time was 152.9 seconds. MorrisMethodExampleSimulation99 (./Examples/Tutorials/Sensitivity_MorrisMethod.apsimx) has finished. Elapsed time was 37.9 seconds. ExperimentSOC7.5Load250DUL0.4 (./Examples/Tutorials/Sensitivity_FactorialANOVA.apsimx) has finished. Elapsed time was 50.4 seconds. ERRORS FOUND!! Elapsed time was 1032.0 seconds script returned exit code 123`

**Comment by par456** [comment]
There isn't really a way to do it where you don't add an NDVI specific report to those sims. I wouldn't remove the graphs though, maybe just disable those if they aren't going to work, as you might want to pull them up again in the future.

So I guess, remove it from DailyReport and mark the related graphs as disabled.

**Comment by par456** [comment]
retest this please jenkins

**Pull request closed without merging**
