### PR TITLE
Use InvariantCulture when writing doubles to the data store. Also fix…

### LINKED ISSUE #2318: impossible to display summary file
as for example with attached image:
summary_file

### PR DESCRIPTION
**Pull request by zur003**
… recent bugs in summary report generation and clearing of the datastore.
Resolves #2318 

This may have the side effect of displaying doubles using the InvariantCulture settings in the GUI as well. Will this be a problem?

### CODE REVIEW

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by zur003** [comment]
Retest this please jenkins

**Comment by zur003** [comment]
retest this please jenkins

**Pull request merged**
