### PR TITLE
Avoid trying to read data values when all we really want are the unit…

### LINKED ISSUE #6612: Annoying exceptions
If one tries to run the Wheat Validation simulations under the IDE debugger, with settings to stop on all exceptions (whether handled or not) one sees a lot of exceptions (well, mostly Null Reference exceptions when trying to get a value for root depth, I think). Things seem to run correctly, but stopping for all these exceptions make debugging problematic. The triggering condition should be handled in some other way, rather than relying on silent exceptions.

### PR DESCRIPTION
**Pull request by zur003**
…s of measurement of a variable. Resolves #6612

### CODE REVIEW

**Review by hol430 — COMMENTED** [review]
Thanks Eric - looks good to me. Out of interest, what's the idea behind the break statements you've added to the locator? If I'm reading this correctly, we're about to exit the loop anyway when `j == namePathBits.Length - 1` evaluates to true(?).

**Comment by zur003** [comment]
@hol430 - No particularly good reason for the "break" statements, other than it being one way to prevent the immediately following statements from being executed. "If" statements could have been used to similar effect. I know that many coders are philosophically opposed to the use of "break" statements, but in this instance I personally find it slightly easier to read (it being a case of "we've now got all the information we need; let's get out of here"). Feel free to modify it, if you wish.

**Comment by hol430** [comment]
Yeah, I don't really have a strong preference either way.

**Comment by her123** [comment]
Avoid break statements where possible.

**Comment by hut104** [comment]
Agree.

**Comment by hol353** [comment]
I prefer to use if/else statements but am ok with break statements if they improve readability (i.e. sometimes the if/else statements can lead to complex code). In this case I see no harm in the breaks.

**Pull request merged**
