### PR TITLE
Change build settings for Release builds as well as Debug builds.

### PR DESCRIPTION
**Pull request by zur003**
Working on #2199.

### CODE REVIEW

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
@hol353 - The differences showing up in the performance testing appears to be real, since with this change, the test models will be run using 64-bit code instead of 32-bit (in Jenkins "Run Tests and Prototypes", which runs Models.exe from the command line). Apparently this is resulting in some small differences in model outputs. What do you suggest I do?

**Comment by hol353** [comment]
I've looked at the diffs and they are only minor so I've 'accepted' the new stats and merged this.

**Pull request merged**
