### PR TITLE
Refactor summary and its UI

### PR DESCRIPTION
**Pull request by hol430**
Working on #6112

- Can filter messages based on severity (error, warning, info, diagnostic, all)
- Can control which messages are captured when sim is run (again based on severity)
- `ISummary` now has only a single method in which the caller specifies message severity (previously we had `WriteMessage()`, `WriteWarning()`, etc). I've written a converter to fix any manager scripts which use this API

Still to be implemented:

- Filter based on model name
- Tabular display of messages
- Control which messages are saved on a file-wide basis (currently can only control this on a per-summary basis)

### CODE REVIEW

**Comment by lie112** [comment]
I think there should be a lot more "borked unit tests" (see last commit)

Can you explain what these new changes mean
- verbosity level
- just making sure all the links to summary in CLEM are still appropriate

**Comment by hol430** [comment]
I've added a verbosity level in this PR, as suggested in #6112. `ISummary` now has only a single method:

```csharp
void WriteMessage(IModel model, string message, MessageType messageType);
```

Previously it had `WriteMessage()`, `WriteWarning()`, and `WriteError()`. Whenever you write to summary now, you provide the message type (error, warning, info, debug) as a parameter rather than as part of the method name. The idea being that we can easily add more verbosity levels in the future, and more verbosity levels means more fine-grained filtering of summary messages in the GUI. I could imagine some models in the future using a debug/diagnostic verbosity level to report their logic/decision making to users.

As part of this, I've done a find-replace over the repository to fix the summary API usage from all models (including clem). I've also written a converter function to fix manager scripts.

Not sure what you mean by "there should be more borked unit tests". Is there a test you'd like to see that would have failed on a change like this? I do agree though with the general principle of "there should be more unit tests"...

**Comment by hol353** [comment]
Do you want this merged or is there more to do?

**Comment by hol430** [comment]
This is good to go if you're happy with the approach and the implementation.

**Review by hol353 — APPROVED** [review]
I like it. I can see lots of grazing/cutting manager scripts using this to show diagnostic info rather than their current approach using custom manager code.

**Pull request merged**
