### PR TITLE
Fixes all the plant available N variables for pseudo patches

### PR DESCRIPTION
**Pull request by sno036**
Working on #2192

### CODE REVIEW

**Comment by sno036** [comment]
@hol353 @hol430 - would you mind checking this?  It is beyond Rogerio and me!  Thanks in anticipation.

**Comment by hol353** [comment]
@sno036 & @rcichota The error you're getting is exactly the same as what we were originally debugging i.e. null in the MathUtilities.Multiply function. The difference is that this is happening now beyond AgPasture i.e. in all the PMF models. I suspect that you will have to add in default values for PlantAvailableNO3 and PlantAvailableNH4 into PMF somewhere (root?). Rogerio, would you know where?

**Comment by rcichota** [comment]
Thanks @hol353 . Yes, I believe I know where to change this. I will see if I can get @sno036 branch and work from there...

**Comment by rcichota** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
