### PR TITLE
Photosynthesis to function

### LINKED ISSUE #292: Functionify RUE model
Because RUEModel is its own type Phothsynthesis can't be substituted with other function types.

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #292 

Have conformed RUEmodel class in Ifunction and changed Photosynthesis in leaf classes to IFunction type.

Each PMF model has had to have a RadnInt function added so photosynthesis can get this value and an extra function FRGRFunction has been added to provide FRGR values as the RUEmodel can't do it if it is an IFunction.

### CODE REVIEW

**Comment by hol353** [comment]
Hmmm this has conflicts. Need to do a pull first Hamish.

**Comment by HamishBrownPFR** [comment]
I am happy for this to be merged in now if you are.  There are lots of changes in .apsimx files that came about from opening files and running to test.

**Comment by hol353** [comment]
Is this complete? Can I change "working on" to resolves in the first comment?

**Comment by HamishBrownPFR** [comment]
Yes, this is complete

**Comment by hol353** [comment]
Hamish

I hadn't merged this one yet and now you've deleted your branch by the look of it. What do we do now?

The pull request still seems to have the changed files. Can we recreate it?

Dean



On 1/09/2015 9:02 AM, Hamish Brown wrote:

Closed #293<https://github.com/APSIMInitiative/ApsimX/pull/293>.

**Comment by HamishBrownPFR** [comment]
Sorry, got a bit carried away with cleaning up.

Will work out how to restor the branch

**Comment by HamishBrownPFR** [comment]
The branch is back up now https://github.com/PlantandFoodResearch/ApsimX/tree/Photosynthesis-to-function

**Comment by HamishBrownPFR** [comment]
Have reopened the branch

**Comment by HamishBrownPFR** [comment]
resolves #292

**Comment by HamishBrownPFR** [comment]
The merge of the documentation we are doing for SCUM brought in a reference to PotentialBiomass function which was deleted for this issue.  Removed this now so should be fine

**Pull request merged**
