### PR TITLE
Adding wheat test and fixing Slurp test

### LINKED ISSUE #621: Add Slurp and Wheat tests

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #621

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
retest this please Jenkins

**Comment by HamishBrownPFR** [comment]
Retest this please Jenkins

**Comment by HamishBrownPFR** [comment]
Retest this please Jenkins or else I will get grumpy!

**Pull request merged**
