### PR TITLE
Refactored ExplorerView

### PR DESCRIPTION
**Pull request by hol353**
Working on #2770

Refactored ExplorerView to remove as much functionality out of the view class and into presenter class. This is the first step towards speeding up loading of a .apsimx file in the GUI.

### CODE REVIEW

**Comment by hol430** [comment]
retest this now jenkins

**Comment by hol430** [comment]
@hol353 Did you mean to commit these .apsimx files?

**Comment by hol430** [comment]
retest this now jenkins

**Comment by hol430** [comment]
retest this now jenkins

**Comment by hol430** [comment]
retest this now jenkins

**Comment by hol353** [comment]
retest this now jenkins

**Pull request merged**
