### PR TITLE
Added a filter to the add model/function view.

### PR DESCRIPTION
**Pull request by hol430**
Working on #3498 

This is a case-sensitive search - is that ok?

### CODE REVIEW

**Comment by hol353** [comment]
Probably better if it was case in-sensitive. Otherwise @hut104 will whinge.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
@hol353 have you guys done something to break the performance tests? This pull request only touches ApsimNG, so I don't see how this could possibly impact the stats.

**Comment by hol353** [comment]
The stats were changed this morning because of a new barley model. When I accepted the stats this morning it doesn't seem to have worked. Done it again now.

**Pull request merged**
