### PR TITLE
Fodderbeet storage changes

### PR DESCRIPTION
**Pull request by RobZys**
Working on #3122

### CODE REVIEW

**Comment by hol353** [comment]
@RobZys This PR has a bunch of files that aren't related to FodderBeet i.e. the branch isn't clean. Can you please fix?

**Comment by hol430** [comment]
Is the builds directory actually used though?

**Comment by hol353** [comment]
Probably not but why is it on this PR?

**Comment by RobZys** [comment]
I don't think so I aplogise for not noticing I had 36 files change, I had just pulled from aspsim master before
Pushing

**Comment by RobZys** [comment]
I just created anew clean branch where the only change will be tho fodderbeet.apsimx

**Pull request closed without merging**
