### PR TITLE
Ensure previous presenter is cleared before displaying the AddModelPresenter

### PR DESCRIPTION
**Pull request by zur003**
Working on #2123 
I think this will correct the issue, but don't want to close this completely until further testing by @HamishBrownPFR, as I'm not sure I've correctly replicated the original problem.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@zur003 if you give me the URL for you repo, I can pull it and test it now

**Comment by zur003** [comment]
@HamishBrownPFR It's
https://github.com/zur003/ApsimX/tree/gtk or something like that. I'm not entirely certain how GitHub URLs work. In this case, my GitHub account name is zur003, the repository is ApsimX, and the branch is gtk.

Or if you want to try manually, take a look at https://github.com/APSIMInitiative/ApsimX/pull/2124/files and insert the one additional line into ContextMenu.cs (the other file with changes is irrelevant to this problem).

**Comment by HamishBrownPFR** [comment]
Yep, I have tested @zur003 fix and it is working on my computer, thanks Eric

**Comment by zur003** [comment]
Resolves #2123

**Comment by zur003** [comment]
@hol353 Can this be merged now?

**Pull request merged**
