### PR TITLE
Factor control and cloud job submission

### PR DESCRIPTION
**Pull request by holzworthd-agr**
Working on #1137 and #806.

### CODE REVIEW

**Comment by hol353** [comment]
@holzworthd-agr This didn't compile Drew. Click 'Details' above on 'Jenkins' line. Then click 'Console Output' link to see compile errors.

**Comment by holzworthd-agr** [comment]
Yeah, I see that. Seems like a problem with the System.Data.SQLite reference, which was used in the MARS implementation of the downloader. I see there's a SQLite class in APSIM.Shared though, which I'm currently using to rewrite that part of the code.

**Comment by hol353** [comment]
@zur003 Any thoughts on why this didn't compile? Wrong version of msbuild on Jenkins perhaps?

**Comment by hol353** [comment]
@zur003  Also lots of warnings about ToolsVersions on Jenkins. Need to get that cleaned up as well.

**Comment by holzworthd-agr** [comment]
@hol353 Should I revert my change to the tool version then?

**Comment by hol353** [comment]
Give it a go and see what happens.

**Comment by zur003** [comment]
I don't think the ToolsVersion stuff really matters all that much. See Microsoft's description of this issue at https://msdn.microsoft.com/en-us/library/bb383796(v=vs.120).aspx. To some extent, though, it does raise the issue of which version(s) of Visual Studio we want to "officially" target. 

It appears to me that the main reason the build failed was the absence of System.Data.SQLite. I suggest adding it as a NuGet package, so that fetching it happens automatically. 

There also error messages for code in AzureJobDisplayView.cs, but the problem there is not obvious to me.

**Comment by holzworthd-agr** [comment]
I've added System.Data.SQLite as a NuGet package, but after looking at it some more I'm still not sure what's wrong with AzureJobDisplayView.cs - it compiles locally just fine.

**Comment by hol353** [comment]
OK I'll pull your branch and have a look on my computer. It might take me a hour to get around to it though.

**Comment by hol353** [comment]
I've had a look at this and it compiles fine on my computer as well. Eric is looking into it now. I'm guessing Jenkins is using an old msbuild version

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
For reasons that remain a mystery to me, getting scoop to use the latest MSBuild.exe seems to have fixed the compile problem. However, there's an error in the UITests phase that won't be obvious at first glance: The .cs files in Tests\UserInterfaceTests will require explicit conversions from IPresenter to ExplorerPresenter.  Similarly, a cast is needed in Documentation\CreateModelDocumentation.cs.

**Comment by hol353** [comment]
@zur003 Can you give Drew the modified UserInterfaceTests files that he needs - or push to his branch? I'm not around tomorrow and I've run out of time today.

**Comment by holzworthd-agr** [comment]
@zur003 I added the changes you mentioned, but I'm not sure that this is going to work - I used the IEnumerable.OfType() method which requires System.Linq. To use this I manually added System.Core.dll to the referenced assemblies in the CompileTextToAssembly() method of the APSIM.Shared.Utilities.ReflectionUtilities class. 

If I get this change merged into APSIM.Shared, will it affect this build?

**Comment by zur003** [comment]
Keep it simple. Couldn't you just use an (ExplorererPresenter) cast, or else "as ExplorerPresenter"?
For example:
    ExplorerPresenter presenter = tabbedExplorerPresenter.Presenters[0] as ExplorerPresenter;

That should work, and doesn't require pulling in the  Linq baggage.

**Comment by holzworthd-agr** [comment]
You're right - that's definitely easier - I've made the changes you suggested. I ran the generate documentation batch script, and it appears to work for Chicory but fails on the subsequent tests (it couldn't find the PO table in the apsimx file). I suspect this is because I have run the chicory simulation in Apsim but none of the others.

I'm not sure how to test the 2 files under \Tests\UserInterfaceTests, so I didn't.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
Drew, you've committed potato.apsimx which has affected the stats. Can you remove it by going to SourceTree, clicking on the specific commit that has potato.apsimx in it, right click on it and select Log Selected. The move to the previous commit in the list, right click and select 'Reset to commit..'. If you need help, set up a meeting with me next week (Mon 10-3pm QLD time is OK for me).

**Comment by holzworthd-agr** [comment]
@hol353 It seems to have failed the performance test again, even after I reset potato.apsimx to the commit at which it was last modified.

**Pull request merged**
