### PR TITLE
Canola

### PR DESCRIPTION
**Pull request by hut104**
working on #3467

### CODE REVIEW

**Comment by hol353** [comment]
Why have you changed SeriesDefinition.cs in this PR? Bad merge?

**Comment by hol430** [comment]
Those changes are appearing because he merged one of my branches which touched the graphing code. @hut104 I think if you pull from master and then push back to this branch those diffs should go away.

**Comment by hut104** [comment]
I'm not sure how the source files got changed in this pull request.  We need to sort this out ASAP.

**Comment by hol430** [comment]
> @hut104 I think if you pull from master and then push back to this branch those diffs should go away.

**Comment by hut104** [comment]
@hol353 Right, I think this can probably be merged now.

**Pull request merged**
