### PR TITLE
Biomass demand refactor

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #2202.  Some progress made but want to test some stuff

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
@hol430 why is this one failing.  We both just called for a retest at the same time

**Comment by hol430** [comment]
ah, you beat me to it. I made the mistake of restarting Scoop while he was in the middle of a job. Jenkins just about had a stroke

**Comment by HamishBrownPFR** [comment]
Murderer

**Comment by hol430** [comment]
Eh, he had it coming, he hasn't been behaving himself recently

**Comment by HamishBrownPFR** [comment]
@hol430 this can be merged if there are no objections.  Performance tests failed with a trivial reduction in NSE for Stem.N which was already very poor so this change can be accepted.

@hut104, @jbrider, @byzheng. @Xiumei2017, @junqi108, @rcichota  I have refactored the DM demands of most organs so that instead of having a DMDemandFunction and a StructuralFraction parameter, each organ now has a DMDemands class which has three child functions, (Structural, Storage and Metabolic) that each return a DM demand for their respective pool in g/m2.  The intent of this change is to give greater flexibility in parameterising demands and to make enable to autodoc to describe organs DM demands better.  
I have written a new function (StorageDemandFunction) which replicated the behavior of the previous code for predicting storage demands and added a converter method to move models in .apsim files onto this new configuration.  The parameter structure the converter produces for Storage demand is a bit cumbersome but this was necessary to get the converter to work generically and can easily be simplified by model builders.  If anyone is having problems with this let me know.
My intention is to do the same refactor with N demands soon unless anyone has any objections.  i haven't changed the Leaf because that will be done as part of a refactor of that class and I haven't changed PerennialLeaf yet because I need to talk to @hut104 about a few things there.

**Pull request merged**
