### PR TITLE
Input models are now run at the beginning of simulation run

### LINKED ISSUE #3609: DataStore database duplicate records in _Messages table
Consecutive runs appear to add duplicate records to the _Messages table. They either need a different index or should be cleaned up before the run.

### LINKED ISSUE #3610: DataStore database duplicate records in _Factors table
Consecutive runs appear to add duplicate records to the _Factors table.

### PR DESCRIPTION
**Pull request by hol353**
Working on #3509 
Resolves #3609 
Resolves #3610

### CODE REVIEW

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@jbrider Can you do a pull and see if this improves you runtime speed for SorghumLeaf? It did for me.

**Comment by jbrider** [comment]
I'm getting an exception after doing the pull - Models.PMF.Organs.Root.PlantZone.get returned null - on line 335 of root.cs.
Not sure what my local changes would have done to make that happen.

**Comment by jbrider** [comment]
I went back to the latest master and it crashes as well... not sure why yours doesn't then.

**Comment by jbrider** [comment]
@hol353 I have tried it on another machine and it crashes in the same place. It appears to be happening before the simulation starts running.

**Comment by hol353** [comment]
@hol430 Are you seeing this? My machine and Jenkins aren't.

**Comment by hol430** [comment]
Yep, I'm getting this on latest master branch, using the f5 job runner. The error disappears if you use the multi-process (f6) job runner.

The simulation actually runs green if you let it, which is why jenkins didn't report this failure.

**Comment by hol353** [comment]
Pull request: https://github.com/APSIMInitiative/ApsimX/pull/3623 should fix this.

**Comment by jbrider** [comment]
@hol353 @zur003 Thanks for your efforts on speeding it up. After your fixes and an upgrade to Win10 -sorghum leaf is now running in 2.5s.  Nice work.

**Pull request merged**
