### PR TITLE
Corrected case, so Linux builds will still work.

### PR DESCRIPTION
**Pull request by zur003**
Working on #78

### CODE REVIEW

**Comment by hol353** [comment]
retest this please jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by zur003** [comment]
Can someone explain to me how just changing the case of a single image file name for the GUI can possibly cause the performance tests to fail?

**Comment by hol353** [comment]
Yes, I've seen this a lot in the last few days. Seems to always be the same stat in Fodderbeet. Rob noticed a problem last week: https://github.com/APSIMInitiative/ApsimX/pull/3983. I'll investigate.

**Comment by hol353** [comment]
@rcichota I think I've found a problem. The Fodderbeet simulation WaikatoNit0Splits2 always seems to fail the performance tests randomly. The performance site says it is a problem with the observed data being swapped around each run. When I look at the observed file is see this:

image

Notice how each date is duplicated i.e. there are two 2017-01-11. This is a problem. Can you fix this ASAP as it is holding up all builds?

**Comment by rcichota** [comment]
Sorry @hol353 I haven't seen this earlier. The FodderBeet model is being handled by @RobZys and I will talk to him tomorrow and this should explain the weird results he was commenting on. I guess, in the mean time you can delete those lines as you've started...

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
This has failed in PlantainGrazing.apsimx, specifically in grazparam.cs:line line 1013. I've seen this happen randomly several times over the last week or two. @zur003, @her123 do you have time to look into it? I've tried reproducing on my computer without success. I don't understand what grazparam is doing at this line.

**Comment by her123** [comment]
I'll look into it Dean.

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
