### PR TITLE
Swim testing

### PR DESCRIPTION
**Pull request by sno036**
working on #1254

### CODE REVIEW

**Comment by hol353** [comment]
@hol430 Don't merge this yet.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@hol430 This is ready for review and merging if ok. It solves minor bugs in AgPasture and Nutrient and a lot of problems with SWIM.

**Review by hol430 — APPROVED** [review]

**Pull request merged**
