### PR TITLE
Update some of the nuget packages.

### PR DESCRIPTION
**Pull request by zur003**
Working on #2127

### CODE REVIEW

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
@zur003 Does this resolve the issue? If so can you update the comment in the top box.

**Comment by zur003** [comment]
@hol353 The Excel reader stuff should probably also be updated, but that will require some minor code changes, as the ExcelReader API has changed. So resolution is not yet complete.

**Comment by hol353** [comment]
OK, I'll leave this pull request open for now.

**Comment by zur003** [comment]
@hol353 Would you be willing to merge the pull request, but leave the issue open?

**Pull request merged**
