### PR TITLE
Try to get scoop to build the GtkSharp GUI

### PR DESCRIPTION
**Pull request by zur003**
Working on #626

### CODE REVIEW

**Comment by zur003** [comment]
Retest this please jenkins

**Comment by zur003** [comment]
Retest this please Jenkins

**Comment by hol353** [comment]
Some of the changed files are from Neil's refactoring work. Why do they appear as diffs?

**Comment by zur003** [comment]
I think it may be a result of pulling Neil's changes into this branch. If you're not comfortable with it, I can try to tidy things up and issue a fresh pull request.

**Comment by hol353** [comment]
Only 2 of the changed files are yours. Normally GitHub doesn't show files changed by someone else so I'm suspicious. Can you take your two files and create a fresh pull request? Might be safer.

**Comment by zur003** [comment]
Closing this request, but about to open a new one.

**Pull request closed without merging**
