### PR TITLE
Maize

### LINKED ISSUE #2205: Improvements to Maize model
I have found and corrected a number of issues in the maize model and test set

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #2205 

Working on a paper describing and testing the PMF arbitrator (#1352 ) I have found an number of issues in the maize model and corrected them.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@hol353 My interpretation is that over all this pull request gives a small improvement in the model but specifically improves the models performance significantly for the Lincoln2012 experiment (the experiment that we have the best data for and that I am using for the arbitrator paper (#1352 ).  I recommend merging this but it would be good to get the opinion of @hut104

**Comment by hut104** [comment]
@hol353 I've had a look at this and I'm happy with this.

**Comment by HamishBrownPFR** [comment]
@hol353 I think this one is good to merge now if you are happy with it

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
