### PR TITLE
Wheat Heading Date

### PR DESCRIPTION
**Pull request by hut104**
working on #5204

### CODE REVIEW

**Comment by hut104** [comment]
@hol353 and @hol430 OK, so this failed the test, but there is nothing different in the tables.

I think this is because I added a new field "HeadingDAS" but it doesn't appear in the table. It is correct that the stats are different.  It just doesn't seem to be showing all the results.

**Comment by hol430** [comment]
Looks like the observed data has changed somehow:

image

**Comment by hut104** [comment]
retest this please jenkins

**Comment by hut104** [comment]
@hol353 I think we can merge this.  I've added new data and these are the only things that have changed.

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
