### PR TITLE
Updates and fixes to APSIM NG documentation

### LINKED ISSUE #6748: Move model to release - documentation
Thanks for all the updated APSIM Next Gen documentation. I am learning new things.

One suggestion. We need a new better resolution or svg APSIM logo. Upon entering the documentation it looks like I stumbled upon an 80's website. Once the right hand panel displays it looks good and contemporary.

Q: Should this documentation now refer to json files rather than xml?

### LINKED ISSUE #6749: Version control - documentation
New pull requests can also be initiated from Git hub APSIMInitiative/ApsimX, Pull requests tab and clicking the "New pull request". This may help users new to source control understand what is being pulled here. Pulling from your own repo is always a bit confusing until you understand the source code/Git terminology.

In the "Merging with the master repo" sections (both approaches) it would be good to add:

_Any Pull request authorised to be merged, that was flagged as resolving an issue (e.g. resolves #45, not working on) will start the automated upgrade building process and an upgrade with the following name structure will be created and available for all users in the Upgrade menu of the user interface within XX hours_ 
[Date of merge yyyy.mm.dd].[resolved issue number] "Issue description"
e.g. _2021.08.12.6699 Predicted-observed graphs not displaying_

Note: this is the resolved issue details not the merge id and description
Note: All working on merges will be included in a following (resolves) merge. ?? do all resolved merges get build or can some of these happening close together be combined?

Links to Jenkins progress page would be useful. I always leave an open tab in browser for this.
Also, I think there was also a link @hol430 gave me to show the upgrade manager progress, even if to identify restarts needed rather than keep waiting.

In Jenkins error report, there's a button at top to display all that's easily missed.
A quick description for newbies of how to find the error message might be useful.

### LINKED ISSUE #6750: Documentation continued
Model design
Communicating With Other Models - Links example 
The private variable Clock should start with a lower case 'c'

Auto documentation
Paragraph 3, unneeded hard return

Software interfaces
First line is missing a word "be" I think. Doesn't quite make sense

User interface
Model view presenter
Change all xml - json to reflect latest approach

Build a model tutorail
At end. For advanced users and further understanding of APSIM Next Gen and the ordering of models all responding to a single published event.
Note: Two instances of this model in the Explorer tree structure would apply their cumulative changes in the order that they are provided in the simulation tree. The logic would hold that they both respond to the published PreparingNewWeatherData event, with the second model using the altered rainfall as a result of the first model and it's OriginalRain reporting the first altered ranfall.

### PR DESCRIPTION
**Pull request by lie112**
resolves #6750 
resolves #6749 
resolves #6748 

I assume I am correct in xml should now be json throughout documentation.

I think these changes are all correct and add some useful additional information not help elsewhere.

### CODE REVIEW

**Comment by lie112** [comment]
Not sure here. Maybe I broke the md file by adding escape sequence
there was one that included <summary> in the text which caused a line break and no printing of summary

**Comment by lie112** [comment]
Ha, it did it here too /< summary />

**Comment by hol430** [comment]
You'll need to pull from master and push back up to this branch. This will probably be a problem with any other open pull requests, as a result of #6678.

**Comment by lie112** [comment]
Thanks. Should have known that. It seems it hasn't been latest updates causing problems lately, so ignored that option.

**Review by hol430 — APPROVED** [review]
Thanks, looks good.

**Pull request merged**
