### PR TITLE
Add new cultivar Suntop

### LINKED ISSUE #839: Add new cultivar Suntop in wheat validation

### PR DESCRIPTION
**Pull request by byzheng**
Resolves #839

### CODE REVIEW

**Comment by hol353** [comment]
Bangyou, your first comment box needs to say 'Resolves' rather than 'Solve'. You can edit the comment by clicking the pencil icon at the top right of the box.

**Comment by byzheng** [comment]
working on #903

**Comment by hol353** [comment]
retest this please Jenkins

**Comment by hol353** [comment]
Bangyou which issue does this pull request relate to? You seem to reference multiple issues (839, 903). We only want one issue per pull request.

**Comment by byzheng** [comment]
Hi Dean, I think it is caused by my first pull request #839 don't merge into master. When I submit a new pull request, github automatically attached the unmerged pull request. 

Cheers,
Bangyou

**Comment by hol353** [comment]
OK. You can close this pull request if you don't need it anymore. I think you can only have one pull request per branch.

On 27/06/2016 5:27:08 PM, Bangyou Zheng <notifications@github.com> wrote:

Hi Dean, I think it is caused by my first pull request #839<https://github.com/APSIMInitiative/ApsimX/issues/839> don't merge into master. When I submit a new pull request, github automatically attached the unmerged pull request.

Cheers,
Bangyou

**Comment by byzheng** [comment]
Hi Dean, I still need my changes.

**Comment by hol353** [comment]
Yes you need your changed files but I am closing this pull request as it addresses two separate issues and Jenkins doesn't run green anyway. Create a new branch called e.g. suntop. Put the changes related to the SunTop cultivar on it and then create a new pull request for that branch. Create a second branch for the remaining changes and then raise a another pull request for it. Keeping your changes separate is important for several reasons. @ver078  can help you with this.

**Pull request closed without merging**
