### PR TITLE
tweeks to functions to facilitate DEROPAPY implementation

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #8551

### CODE REVIEW

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
@HamishBrownPFR: The problem with this PR is that it took more than 45 minutes to run (instead of 35 minutes). We have a rule that aborts a PR if it takes too long.

**Comment by HamishBrownPFR** [comment]
Thanks @hol353.  How would you go about diagnosing what is causing it to be slow?

**Comment by HamishBrownPFR** [comment]
There is something funny about this PR.  There are loads of file changes that should not be there.  Will close and try again

**Pull request closed without merging**
