### PR TITLE
Refactor grid presenters and views

### PR DESCRIPTION
**Pull request by hol353**
Working on #8760

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
hi @hol353 I have some stuff with Deropapy out on a branch that is doing some different things with grids.  Reading data from a csv into a grid and writing it back.  I will be keen to have a quick discussion to see how this refactor will affect that.  It is not working quite right but I need it to keep working to finish a project off.

**Comment by hol353** [comment]
Hi @HamishBrownPFR. This refactor is purely a code clean-up. No bug fixes or new featues. Hopefully no new bugs either. This will probably be ongoing for a month or so - it's a bit of a side project.

If you have problems with the grids or want something new then now is a good time to chat.

**Comment by hol353** [comment]
@par456 @ric394 When you get a chance can you pull this branch and test. Any issues you find, add to this PR.

**Comment by hol353** [comment]
@par456 This is ready for another test.

**Comment by par456** [comment]
Problems I've found so far:

- Physical: If I delete/edit a cell, then click to edit the cell again, the original number comes back
- Physical: Sometimes when I click to edit a cell, the number disappears, and the edit box is empty (only happens after I clear a different cell)
- Physical: If I select a group of cells (say a 3x3 block) and then try and paste it to the last row, I get a bunch of exceptions, however it still pastes and creates new half-filled rows with a lot of error output in the message panel
- Solute: If I edit a depth cell, the wrong value comes up in the edit box (same in Water)
- Water: If I try to multiple rows past the end of the last row, I get a different error to the physical one, but the paste still happens

**Comment by par456** [comment]
Physical: If I create a bunch of new rows by entering data, then delete the content, the empty rows remain even after reopening the file.
Solute: If I try to add a new row (either by copying in or typing in) I get an exception warning, however the data is still added.
Chemical: If I try to edit a value, I get an exception then I can't edit any values in the table.

I ran the wheat example and looked at the datastore and got this:
image

**Pull request merged**
