### PR TITLE
Fix the maintenance respiration

### LINKED ISSUE #2098: MaintenanceRespiration in organs
There are not consistent implementation of `MaintenanceRespiration` in all organs.

* No `MaintenanceRespiration` in `Root`. No cause for wheat model as there are no metabolic and storage in Root.
* No reset to 0 at `GenericOrgan`. The output of `MaintenanceRespiration` for `Stem` and `Spike` are accumulate value, not the daily value. 
* `Leaf` use`MaintenanceRespirationFunction` under `CohortParameters`, instead of under `Leaf`. No `MaintenanceRespiration` of leaf as `MaintenanceRespirationFunction` under `CohortParameters` is set as `0`.

### PR DESCRIPTION
**Pull request by byzheng**
resolves #2098

### CODE REVIEW

**Comment by byzheng** [comment]
@hol353 How about this pull request? Do I need to do anything before merging it?

**Comment by hol353** [comment]
It hasn't run green Bangyou. Jenkins failed - click the 'Details' link beside  'Jenkins - Merged build finished' to see the APSIM errors

**Comment by byzheng** [comment]
@hol353 I am trying to make green for all my pull request now. But it seems the compile errors relate with "Excel". Are there errors in Jenkins?

**Comment by byzheng** [comment]
Retest this please Jenkins

**Comment by byzheng** [comment]
Can be merged? I don't know why this change can impact on "AgroforestrySystem.apsimx" and "Nutrient.apsimx". Should not any impact.

**Comment by hol353** [comment]
Can't be merged until Jenkins passes. Looks like the Agroforestry and nutrient simulations now run differently. They must have a plant model in them. You will need to investigate why they are running differently.

Also, can you remove chicory.apsimx from pull request? No need for it to be there.

**Comment by byzheng** [comment]
I am run out of my option now. Can anyone help out for this problem?

I comment out all changes. All tests in AgroforestrySystem.apsimx are passed only with tiny changes (<E-10).

Then I add two line codes (See below) and check whether `MaintenanceRespiration` is more than zero. The whole simulation doesn't stop in the if statement. It seems I don't add anything to MaintenanceRespiration. However, the simulation is failed with lots of changes in test. 

```csharp
MaintenanceRespiration  = 0;
MaintenanceRespiration += Live.MetabolicWt * MaintenanceRespirationFunction.Value();
double a = 0;
 if (MaintenanceRespiration > 0)
 {
        a = MaintenanceRespiration;
}
```

Then I change to 
```csharp
MaintenanceRespiration  = 0
```
The simulation is still passed.

**Comment by byzheng** [comment]
Even I just try to retrieve value. The simulation still failed.

```csharp
double b = Live.MetabolicWt;
```

```csharp
double b = Live.MetabolicWt;
```

**Comment by byzheng** [comment]
I find the problem which is related with `needToRecalculateLiveDead`. 

In the function `OnDoActualPlantGrowth`, `needToRecalculateLiveDead` is still `true`. Any codes to retrieve values of `Live` and `Dead` will call function`RecalculateLiveDead` to update `LiveBiomass` and `DeadBiomass`. This is the only reason the simulation is failed. 

It it out of my knowledge to fix it. Someone may provide a solution.

**Comment by hol353** [comment]
If you change Live or Dead you have to remember to set 'needToRecalculateLiveDead' to true. These lines of yours do change Live:

Live.MetabolicWt *= (1 - MaintenanceRespirationFunction.Value());
MaintenanceRespiration += Live.StorageWt * MaintenanceRespirationFunction.Value();
Live.StorageWt *= (1 - MaintenanceRespirationFunction.Value());

so after you change Live, add this line:
needToRecalculateLiveDead = true;

Needing to remember to set needToRecalculateLiveDead  to true is dangerous. I've done it this way because calculating Live and Dead every time it is used is very SLOW. We need a better design.

**Comment by byzheng** [comment]
It seems it is not a right way to implement root MaintenanceRespirationFunction. We should directly change the biomass in each root zone, not directly  Live and Dead. Will look at this problem later.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request merged**
