### PR TITLE
Fix the documentation of variable in the ReproduciveOrgan.

### LINKED ISSUE #3059: Update the documentation for reproductive organ
For a clear description about the reproductive organ.

### PR DESCRIPTION
**Pull request by behnamxa**
resolves  #3059

### CODE REVIEW

**Comment by hol353** [comment]
add to whitelist jenkins

**Comment by hol353** [comment]
@behnamxa This pull request hasn't been merged yet because you closed it before I got a chance to look at it. I can reopen the pull request and merge if you like.

**Comment by behnamxa** [comment]
Hi Dean,

 

Sorry for that. I am a little bit lost here! I deleted the branch Bangyou had created. Can I restore it? 

 

Ben.

**Comment by hol353** [comment]
GitHub thinks you have already restored the branch. I'll reopen the pull request.

**Pull request merged**
