### PR TITLE
Sorghum leaf

### PR DESCRIPTION
**Pull request by jbrider**
working on #572

### CODE REVIEW

**Comment by hol353** [comment]
The stats are different. Can you provide advice on why they are difference and whether you're happy with them?

**Comment by hol353** [comment]
I came across a PlantAvailableWaterSupply method in Root. It seems to be sorghum specific but isn't used anymore. Can you please remove it if not needed?

**Comment by jbrider** [comment]
The changes are due to a fix made to the phenology water stress which resulted in changes to the phenology in some water stressed simulations - 2 of which no longer reach harvest.  This was an expected outcome that we are happy with. The same change will be made to Classic as well.

**Comment by jbrider** [comment]
@hol353 This would be a good time to merge.
If it's only comments now, then I will be working on them and improving the documentation before it gets released.

**Review by hol353 — APPROVED** [review]

**Pull request merged**
