### PR TITLE
Rice

### PR DESCRIPTION
**Pull request by andomariot**
Working on #5197 Updating the rice folder  with files of observed data templates and draft model deleted

### CODE REVIEW

**Comment by hol353** [comment]
Hi @andomariot: In the top comment box can you add the words:

Working on #xxxx

where xxxx is the issue that this pull request is related to i.e. 

Working on #5197.

You can edit a comment by clicking on the ... button on the comment.

Second problem. This branch isn't up to date with the master branch. Can you pull from ApsimInitiative:master and then push back to this rice branch?

**Comment by andomariot** [comment]
Thanks @hol353 ,
I have updated the comment.

**Comment by hol353** [comment]
retest this please jenkins

**Comment by hol353** [comment]
retest this please jenkins

**Pull request closed without merging**
