### PR TITLE
Tidy up bits in test simulations

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
working on #1352.  Cosmetic changes to simulation set ups to make sure I can get all the variables needed for graphs.  I have deconvoluted some of the variable names in maize (eg changed Stem.Live.Wt to Stem.Wt because there is no dead fraction).  This may effect stats which were using the other variable

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
Diffs in maize test are all OK, for a couple of variables it is picking up some observations and doing tests that were previously missing.  For the other, the diffs are due to change variable names.

Wheat diffs are all very small but need to work out why they are there at all

**Comment by HamishBrownPFR** [comment]
Wheat diffs are OK as well.  I have removed the EndCrop from the Lincoln2015 simulation (so biomass remains until the final observed date) which has changed the stats on DailyObsPred.  This is expected and the performance of the model has not changed so this can be merged.

Also noticed some diffs coming from a data duplication/order issue.  It appears there are duplicate instances of data rows on some dates, one which has a value for   Structure.TotalStemPopulation and one which has a zero.  The order of these is changing which is causing false diffs. 

image

**Comment by hol353** [comment]
@cla473 The duplicates problem looks like a bug to me.

**Comment by HamishBrownPFR** [comment]
@hol353.  I am happy for this to be merged now if you are.

**Comment by hol353** [comment]
Jenkins didn't run clean. Maize auto-doc fail by the look of it.

**Comment by HamishBrownPFR** [comment]
all good to merge now?

**Pull request merged**
