### PR TITLE
Dynamic tillering in sorghum

### PR DESCRIPTION
**Pull request by hol430**
Working on #4767

### CODE REVIEW

**Comment by hol430** [comment]
@jbrider I've had a look at the changes in stats and they seem pretty minor. When I run the simulations and look at the old vs new graphs I see some moderate-large differences but those particular stats/simulations aren't showing differences in the performance tests (e.g. LeafGreenWt in Sorghum_HE1_T1). In fact if you look at the drilldown graphs on the performance tests site, the changes all look pretty minor as far as I can see.

**Comment by jbrider** [comment]
I'll have a closer look at what changed - thought it should be the same.

**Comment by jbrider** [comment]
Did the stats update properly?
I'm happy with the changes that I saw in the sims - so maybe the few individual changes I took note of just didn't change again.

**Comment by hol430** [comment]
It looks like there are no accepted stats for a large proportion of our simulations. No idea why, but hopefully accepting the changes here will fix that problem.

**Comment by jbrider** [comment]
@hol353 These can be accepted.

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Comment by hol430** [comment]
retest this please jenkins

**Pull request merged**
