### PR TITLE
Fodder beet release

### PR DESCRIPTION
**Pull request by RobZys**
Working on #78

Preparation for Fodderbeet release 
Added Fodderbeet to resources, 
Modified toolboxes
Added Fodderbeet validation to tests

To do - Clean up documentation - May need a pull for Edith

### CODE REVIEW

**Comment by RobZys** [comment]
@hol353 Dean I am migrating from under review to test\validation  can you accept the stats for the first time

**Comment by HamishBrownPFR** [comment]
@hol353 is there any reason you have not merged this in yet.  Failed performance tests because first commit of results.  This pull request will get Fodder beat into release.

Hamish

**Comment by hol353** [comment]
I haven't noticed this one until now. I tend to only look at green PRs unless someone asks me. This isn't the first time the performance tests have seen fodderbeet. It collected the stats while it was in UnderReview and now they have changed. Why is that?

**Comment by hol353** [comment]
Actually I see Rob did tag me into this PR. I must have missed that while I was in the U.S. a couple of weeks ago. Sorry about that.

**Pull request merged**
