### PR TITLE
Feature/i leaf

### LINKED ISSUE #610: Need to add a Leaf Interface to get 'SimpleLeaf' to work with 'Structure'

### PR DESCRIPTION
**Pull request by aldoherty**
resolves #610

### CODE REVIEW

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by hol353** [comment]
Al can you change to initial comment to say 'resolves' rather than 'fixes issue'

**Comment by hol353** [comment]
@HamishBrownPFR, can you have a look at this change from Al? OK?

**Comment by HamishBrownPFR** [comment]
This looks OK to me.  I would like to get the tests set up again before merging this in.  Working on that now.

**Comment by hol353** [comment]
Can one of the admins verify this patch?

**Comment by HamishBrownPFR** [comment]
I want to get the tests for Scum and Slurp sorted first but need the last issue that I posted resolved first.  Can’t recall the number but to do with date formate in observed date frame

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Comment by HamishBrownPFR** [comment]
Jenkins not testing this properly.  Try again

**Comment by HamishBrownPFR** [comment]
retest this please jenkins

**Pull request closed without merging**
