### PR TITLE
Working on #1822

### PR DESCRIPTION
**Pull request by junqi108**
update the leaf appearance for making it faster for low rank leaves

Working on #1822.

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
Hi @junqi108.  You need to put the following in your pull request 

Working on #1822.

1822 is an issue number.  I have just logged the issue.

**Comment by HamishBrownPFR** [comment]
I will edit your pull request message for you

**Comment by HamishBrownPFR** [comment]
retest this please Jenkins

**Comment by junqi108** [comment]
retest this please Jenkins

**Pull request merged**
