### PR TITLE
Grapevine

### PR DESCRIPTION
**Pull request by junqi108**
working on #1822

### CODE REVIEW

**Comment by junqi108** [comment]
@HamishBrownPFR @sno036 @rcichota 
hi Val: I wonder whether you would like to review the stock simulation. I added the stock and grazing method in both row and alley.
I try to create two non-grazing windows as well according to vineyard practice: one in winter and one for leaf plucking.  It seems working well, although it seems sheep did not graze much in the vine row after the first year. According to summary, grazing is happening in both row and alley.

**Comment by sno036** [comment]
Hi @junqi108 - will do but will be later in the week. OK with you?

**Comment by junqi108** [comment]
@sno036  yeah, no problem.

**Comment by junqi108** [comment]
@hol430 Do you know why the model documentation is doing the model description twice? 
image

**Comment by sno036** [comment]
@junqi108 - I just looked and could only find ...apsimNextGen\Prototypes\Grapevine\grapevine.apsimx but couldn't see anything obvious there about stock. Can you point me in the right direction?

**Comment by junqi108** [comment]
> @junqi108 - I just looked and could only find ...apsimNextGen\Prototypes\Grapevine\grapevine.apsimx but couldn't see anything obvious there about stock. Can you point me in the right direction?

Hi Val: it is probably because the latest changes hasn't been merged in the master branch yet. I can send the latest apsimx file  to you or we can wait dean to merge the changes.

**Comment by junqi108** [comment]
@hol430 reference issues
hi Drew: 
I have added the bib reference type to the APSIM.bib file and cite them using square bracket and name in the memo, however APSIM auto-documentation seems did not pick them up. Do you know the possible reasons for this?
image


image

**Comment by sno036** [comment]
Hi @junqi108  - great start. I pulled just the grazing part out of the simulation file you sent me and have done a few things with it. See attached.

- I had to disable "Reset on date" from the Alley. Even when I deleted the Link to Wheat the simulation still complained that it couldn't find it. Very odd that it should be looking for a link that is not mentioned. I think you should follow this up with @HamishBrownPFR (totally beyond me!)
- I replaced the plantain with ryegrass and clover in the Alley, replaced the ewes with weathers (fewer complications), and removed the silage feeding (we want the stock grazing the vines)

There is a problem with the stock management. In Alley, as soon as I enable the no-graze window no grazing happens and in Row the grazing seems to be totally controlled by the no-grazing window. I see that you added a second no-graze window. Perhaps the logic was broken when you did that?

The purpose of this simulation is to make sure that the right things are being eaten. In the Row outputs can you add in information to see what is being eaten by the stock please? I assume that there should be minimal grazing of the trucks/stems and I don't know what other plant parts exist. I know that the no-graze windows are biologically sensible but it is essential to have some stock in there when there are grapes etc. to see if sensible consumption happens.

@hol353  - is that nifty location thing (right-click, or was it just click on the shaded bars) broken? The bars are showing by no text.

Longer term will need a grazing component that manages the two zones as a unit.
[GrazeVineyard.zip](https://github.com/APSIMInitiative/ApsimX/files/6490391/GrazeVineyard.zip)

**Comment by junqi108** [comment]
@sno036  hi Val: thanks for the revise. I have copied your setup to the grapevine model. I will address your comments.

**Comment by hol353** [comment]
>  is that nifty location thing (right-click, or was it just click on the shaded bars) broken? The bars are showing but no text.

The stock example has graphs with these shaded bars. They seem to work ok. You need to right click on the graph series and select 'Add model' and then choose 'ShadedBarsOnGraph'.

**Comment by junqi108** [comment]
> In Alley, as soon as I enable the no-graze window no grazing happens and in Row the grazing seems to be totally controlled by the no-grazing window.
hi @sno036: 
I did some tests with different alley species. The simulation was OK with plantain is sowed, and got problems with AGP white clover and ryegrass. At first, I was puzzled by the result that the grazing at the alley stopped after some time while the biomass of the alley is still going up and down with Ryegrass and white clover presented.  When i checked the biomass of Ryegrass and white clover, it seems the biomass simulation for one of the species is wrong and goes to a very low value. This also happens when i add one of the species together to grow with Plantain. 
image

image

I guess there were some issues two species with the stock management script. but this is probably beyond my knowledge to fix it. 
@hol353 
by the way, Do you know how to output which component of the grapevine is eaten by the stock?

**Comment by junqi108** [comment]
@sno036 the double grazing window works well with the Plaintain.
image
image

**Comment by hol353** [comment]
>  Do you know how to output which component of the grapevine is eaten by the stock?

I don't think it is possible currently to output the organ that the animals are eating. They will eat whatever is available and aboveground.

**Comment by sno036** [comment]
> > is that nifty location thing (right-click, or was it just click on the shaded bars) broken? The bars are showing but no text.
> 
> The stock example has graphs with these shaded bars. They seem to work ok. You need to right click on the graph series and select 'Add model' and then choose 'ShadedBarsOnGraph'.

@hol353  - yes that works but what seems to have been lost is the ability to then click (or right-click?) on one of those bars and understand what location each colour stands for. Make sense?

**Comment by sno036** [comment]
> > Do you know how to output which component of the grapevine is eaten by the stock?
> 
> I don't think it is possible currently to output the organ that the animals are eating. They will eat whatever is available and aboveground.

This would be a desirable thing to have from Stock (because it is that model that is doing the defoliation I seem to remember?) but in the interim @junqi108 surely you can capture (say) leaf biomass before and after the grazing in a Manager (there are enough stages in the day to do this) to find out what is being eaten. This is the main point of putting in this as a sensibility check I think.

**Comment by junqi108** [comment]
> > Do you know how to output which component of the grapevine is eaten by the stock?
> 
> I don't think it is possible currently to output the organ that the animals are eating. They will eat whatever is available and aboveground.

i think there is some variable record which component it is grazing because the summary output it. The tally in the report does not give options of the organ type after input grapevine. do you know how to ouput the grazed biomass in the report? thanks very much. 
2005-02-28 Row.Grapevine.Berry

Removing 4.8% of berry biomass from Grapevine. Of this 100.0% is removed from the system and 0.0% is returned to the surface organic matter.
Removed 6.9 g/m2 of dry matter weight and 0.1 g/m2 of N.

2005-03-01 Row.Grapevine.Leaf

Removing 5.2% of leaf biomass from Grapevine. Of this 100.0% is removed from the system and 0.0% is returned to the surface organic matter.
Removed 4.6 g/m2 of dry matter weight and 0.1 g/m2 of N.

**Comment by sno036** [comment]
> > In Alley, as soon as I enable the no-graze window no grazing happens and in Row the grazing seems to be totally controlled by the no-grazing window.
> > hi @sno036:
> > I did some tests with different alley species. The simulation was OK with plantain is sowed, and got problems with AGP white clover and ryegrass. At first, I was puzzled by the result that the grazing at the alley stopped after some time while the biomass of the alley is still going up and down with Ryegrass and white clover presented.  When i checked the biomass of Ryegrass and white clover, it seems the biomass simulation for one of the species is wrong and goes to a very low value. This also happens when i add one of the species together to grow with Plantain.
> I guess there were some issues two species with the stock management script. but this is probably beyond my knowledge to fix it.

@junqi108 - Don't worry about the clover (and anyway with all the fertiliser you are putting on plus no defoliation it is perhaps a sensible grass-clover response!).

**Comment by hol353** [comment]
> i think there is some variable record which component it is grazing because the summary output it. The tally in the report does not give options of the organ type after input grapevine. do you know how to ouput the grazed biomass in the report? thanks very much.

Ok you may be right. The summary output comes from a 'Removed' property which is in each organ I think. Try outputting 'Removed.Wt' from leaf and stem.

**Comment by hol353** [comment]
The agpasture ryegrass and white clover models won't have a 'removed'. It is probably called 'harvested' or something similar instead.

**Comment by junqi108** [comment]
> The agpasture ryegrass and white clover models won't have a 'removed'. It is probably called 'harvested' or something similar instead.

thanks Dean. this works well
image

**Comment by junqi108** [comment]
> @hol430 reference issues
> hi Drew:
> I have added the bib reference type to the APSIM.bib file and cite them using square bracket and name in the memo, however APSIM auto-documentation seems did not pick them up. Do you know the possible reasons for this?
> image
> 
> image

@hol353 hi dean, while you are online, do you know what could be the issue that my autodocumentation is not picking up the references i put in the bib file? thanks very much.

**Comment by hol430** [comment]
It seems to be working for me. Did you rebuild (and restart) apsim after modifying the .bib file? If not, that could explain the problem. Also worth noting that when you click on the memo the references to the bib file won't be rendered as links. I'll file a separate issue for that.

image

**Comment by junqi108** [comment]
> It seems to be working for me. Did you rebuild (and restart) apsim after modifying the .bib file? If not, that could explain the problem. Also worth noting that when you click on the memo the references to the bib file won't be rendered as links. I'll file a separate issue for that.
> 
> image
Interesting. I retried it. it works with my custom build version, but not with the released version....
image

**Comment by hol430** [comment]
Yep, because your changes to the APSIM.bib file haven't made it into the released version. That will happen once this pull request is merged.

**Comment by junqi108** [comment]
> Yep, because your changes to the APSIM.bib file haven't made it into the released version. That will happen once this pull request is merged.

oh, yes, they use different files.....

**Comment by sno036** [comment]
> > The agpasture ryegrass and white clover models won't have a 'removed'. It is probably called 'harvested' or something similar instead.
> 
> thanks Dean. this works well
> image

But what is it (leaves, grapes, trunk, ...) that the sheep are eating?

**Comment by junqi108** [comment]
> > > The agpasture ryegrass and white clover models won't have a 'removed'. It is probably called 'harvested' or something similar instead.
> > 
> > 
> > thanks Dean. this works well
> > image
> 
> But what is it (leaves, grapes, trunk, ...) that the sheep are eating?

I think if no other events, e.g. leaf plucking or winter pruning hapens, the removed biomass is what eaten by sheep.

**Comment by hol430** [comment]
Sorry Junqi, this is probably going to fail on Jenkins until #6463 is merged. The validation tests and P/O stats should work fine, it's the other parts that won't work for now.

**Comment by junqi108** [comment]
> Sorry Junqi, this is probably going to fail on Jenkins until #6463 is merged. The validation tests and P/O stats should work fine, it's the other parts that won't work for now.

Thanka for letting me know. it is fine for me.

**Comment by junqi108** [comment]
> > > > The agpasture ryegrass and white clover models won't have a 'removed'. It is probably called 'harvested' or something similar instead.
> > > 
> > > 
> > > thanks Dean. this works well
> > > image
> > 
> > 
> > But what is it (leaves, grapes, trunk, ...) that the sheep are eating?
> 
> I think if no other events, e.g. leaf plucking or winter pruning hapens, the removed biomass is what eaten by sheep.

Hi there: the sheep is eating my trunk and root. Is there a way to restrict which component that sheep can eat? or we need to wait for some further development on this?

**Comment by hol353** [comment]
The sheep shouldn't eat root as they are a below ground organ. How do you know they are?

Note there is already an issue on this subject - #6258

**Comment by junqi108** [comment]
> The sheep shouldn't eat root as they are a below ground organ. How do you know they are?
> 
> Note there is already an issue on this subject - #6258

sorry my mistake. i did not check all the y variables, and one was unchanged. 
The discussion looks very interesting. Hope the new digestibility feature will come soon. 
image

**Comment by sno036** [comment]
@junqi108  - I am glad you found this! Perhaps discuss with @hol353 but to make sure that the stem and roots are not being eaten again in the future should there be one of those manager components that tests for intake > 0 and crashes the simulation if found?

**Pull request merged**
