### PR TITLE
Updated version of RuminantManage activity and associated models

### LINKED ISSUE #7107: Refactor the Ruminant Manage Activity
Performed fixes and added new features, improvements and performed sensibility tests in order to achieve simulation requirements of current grazing system users.

### PR DESCRIPTION
**Pull request by lie112**
Resolves #7107

### CODE REVIEW

**Review by hol430 — APPROVED** [review]
Looks good to me, though may have been worth making a separate PR for the change to PropertyPresenter, which is a more general bugfix.

**Comment by lie112** [comment]
noted. I am at least getting these separate style changed into their own commits.
I am working on refactoring and therefore fix bugs and implement the required changes as I go.
How can you pull changes out of the workflow and submit as individual pull request?
After I have finished this next big refactor, I will be able to address change by change as pull requests.

**Comment by hol430** [comment]
Not sure what you mean by workflow exactly, but when you commit your changes, you can commit all the related changes, then change to another branch and commit the unrelated changes (ie some bugfix) to the other branch. Then you can make PRs on both branches.

**Comment by lie112** [comment]
I could be working across a number of branches, but in working along the commits waiting for approval in other branch will be holding up the continued work won't they. It gets messy as they are often intertwined with what I am doing as that's the reason they came up.

**Pull request merged**
