### PR TITLE
Negative DoThin correction

### PR DESCRIPTION
**Pull request by sme016**
Working on #8091 
Eliminate -ve DoThins in Pinus validation

### CODE REVIEW

**Comment by sme016** [comment]
That seems to be ok for the Pinus model. 
Now I need to do similar for the Eucalyptus model

**Comment by sme016** [comment]
Does the error message imply a problem wuith the Datastore, which I don't think I touched in the changes I made?
What do you suggest?

**Comment by hol353** [comment]
retest this please jenkins

**Comment by sme016** [comment]
Thanks for the retest. The changes in stemspha stats was expected, becuase the obs data still contain the negative mortality data. The changes in the other stats are I think acceptable.
I suggest merge.

**Comment by sme016** [comment]
I'll have another commit soon to that branch on a different issue that I haven't yet raised

**Comment by sme016** [comment]
Resolved

**Comment by sme016** [comment]
Resolves #8091

**Pull request merged**
