### PR TITLE
Use https when accessing resources on apsim.info site.

### LINKED ISSUE #2550: Upgrade functionality is broken
The upgrade form is currently unable to connect to the web service used to generate the upgrade list, most likely due to the recent move to https on the apsim.info site.

### PR DESCRIPTION
**Pull request by hol430**
Resolves #2550

### CODE REVIEW

**Comment by hol430** [comment]
Although this will fix the issue in the long run, the problem remains that users will be unable to upgrade to this version due to their upgrade form being broken.

**Comment by zur003** [comment]
Can we have the web site do a re-direct?

**Comment by hol353** [comment]
Yep. I'm looking at it now.

**Comment by hol353** [comment]
OK fixed. http works as well as https

**Pull request merged**
